<!--
SPDX-FileCopyrightText: 2025 Legiayayana

SPDX-License-Identifier: EUPL-1.2
-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<_MagickNETVersion>14.4.0</_MagickNETVersion>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Libraries\BCDecNet\BCDecNet\BCDecNet.csproj"/>
		<ProjectReference Include="..\Libraries\glTFScaffold\glTFScaffold.csproj"/>
		<ProjectReference Include="..\Libraries\Pepper\Pepper\Pepper.csproj"/>
		<ProjectReference Include="..\Rivet\Rivet.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AssetRipper.TextureDecoder" Version="2.2.1"/>
	</ItemGroup>

	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
		<PackageReference Include="Magick.NET-Q16-OpenMP-x64" Version="$(_MagickNETVersion)"/>
	</ItemGroup>

	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-arm64'">
		<PackageReference Include="Magick.NET-Q16-OpenMP-arm64" Version="$(_MagickNETVersion)"/>
	</ItemGroup>

	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
		<PackageReference Include="Magick.NET-Q16-OpenMP-x64" Version="$(_MagickNETVersion)"/>
	</ItemGroup>

	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">
		<PackageReference Include="Magick.NET-Q16-OpenMP-arm64" Version="$(_MagickNETVersion)"/>
	</ItemGroup>

	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'osx-x64'">
		<PackageReference Include="Magick.NET-Q16-OpenMP-x64" Version="$(_MagickNETVersion)"/>
	</ItemGroup>

	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'osx-arm64'">
		<PackageReference Include="Magick.NET-Q16-arm64" Version="$(_MagickNETVersion)"/>
	</ItemGroup>

	<ItemGroup Condition="'$(RuntimeIdentifier)' == ''">
		<PackageReference Include="Magick.NET-Q16-AnyCPU" Version="$(_MagickNETVersion)"/>
	</ItemGroup>

</Project>
