// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xdaed9f2du)]
public class AddStatusEffectShotEffectPrius : ScriptedShotEffectBasePrius, IDDLObjectType<AddStatusEffectShotEffectPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xdaed9f2du);

	public AddStatusEffectShotEffectPrius(DDLObject ddl) : base(ddl) {
		Effect = ddl.GetObject<StatusEffectBasePrius>(0x8818df95u);
	}

	[DDLRegistration(0x8818df95u)]
	public StatusEffectBasePrius? Effect { get; set; } = default;

	public new static AddStatusEffectShotEffectPrius Create(DDLObject ddl) => new(ddl);
}

