// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x4036f83eu)]
public class AimModGimpPrius : AimModifierPrius, IDDLObjectType<AimModGimpPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x4036f83eu);

	public AimModGimpPrius(DDLObject ddl) : base(ddl) { }

	public new static AimModGimpPrius Create(DDLObject ddl) => new(ddl);
}

