// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x3a2f6c21u)]
public class AnimAwarenessChangedEvent : EventBase, IDDLObjectType<AnimAwarenessChangedEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x3a2f6c21u);

	public AnimAwarenessChangedEvent(DDLObject ddl) : base(ddl) {
		IsEngaged = ddl.GetValue<bool>(0x2563c2e7u, IsEngaged);
	}

	[DDLRegistration(0x2563c2e7u)]
	public bool IsEngaged { get; set; } = false;

	public new static AnimAwarenessChangedEvent Create(DDLObject ddl) => new(ddl);
}

