// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x949cd751u)]
public class AnimDamageEvent : EventBase, IDDLObjectType<AnimDamageEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x949cd751u);

	public AnimDamageEvent(DDLObject ddl) : base(ddl) {
		AttackIndex = ddl.GetValue<uint>(0x6650a828u, AttackIndex);
		DamageDuration = ddl.GetValue<float>(0xdd944989u, DamageDuration);
		OverrideLocator = ddl.GetString(0x3121f9b3) ?? OverrideLocator;
	}

	[DDLRegistration(0x949cd751u)]
	public uint AttackIndex { get; set; } = 0x00000000;

	[DDLRegistration(0x949cd751u)]
	public float DamageDuration { get; set; } = 0.25f;

	[DDLRegistration(0x949cd751u)]
	public string? OverrideLocator { get; set; } = default;

	public new static AnimDamageEvent Create(DDLObject ddl) => new(ddl);
}

