// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xd74b4378u)]
public class AssetSizeRequest : DDLObjectType, IDDLObjectType<AssetSizeRequest> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xd74b4378u);

	public AssetSizeRequest(DDLObject ddl) : base(ddl) {
		AssetPaths = ddl.GetValues<RivetAssetId>(0x280c42ffu);
	}

	[DDLRegistration(0xd74b4378u, description: "List of assets paths, relative to the asset source root, that you want to get the size of.")]
	public List<RivetAssetId> AssetPaths { get; set; } = [];

	public static AssetSizeRequest Create(DDLObject ddl) => new(ddl);
}

