// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x8e01d091u)]
public class AttackStartEvent : EventBase, IDDLObjectType<AttackStartEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x8e01d091u);

	public AttackStartEvent(DDLObject ddl) : base(ddl) { }

	public new static AttackStartEvent Create(DDLObject ddl) => new(ddl);
}

