// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x2f57bd77u)]
public class BataliaTurretUnchargedEvent : EventBase, IDDLObjectType<BataliaTurretUnchargedEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x2f57bd77u);

	public BataliaTurretUnchargedEvent(DDLObject ddl) : base(ddl) { }

	public new static BataliaTurretUnchargedEvent Create(DDLObject ddl) => new(ddl);
}

