// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x27ad9e6fu)]
public class BoltCrankAttachEvent : EventBase, IDDLObjectType<BoltCrankAttachEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x27ad9e6fu);

	public BoltCrankAttachEvent(DDLObject ddl) : base(ddl) { }

	public new static BoltCrankAttachEvent Create(DDLObject ddl) => new(ddl);
}

