// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x5131ea41u)]
public class BossBotCordelionNefariousPlasmaShotPrius : BasicBulletPrius, IDDLObjectType<BossBotCordelionNefariousPlasmaShotPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x5131ea41u);

	public BossBotCordelionNefariousPlasmaShotPrius(DDLObject ddl) : base(ddl) {
		ImpactActor = ddl.GetValue<RivetAssetId>(0x6c4233f5u, ImpactActor);
		ShockwaveImpact = ddl.GetObject<ShockwavePrius>(0xe77cc68eu);
	}

	[DDLRegistration(0x6c4233f5u, "Impact Actor")]
	public RivetAssetId ImpactActor { get; set; } = default;

	[DDLRegistration(0xe77cc68eu)]
	public ShockwavePrius? ShockwaveImpact { get; set; } = default;

	public new static BossBotCordelionNefariousPlasmaShotPrius Create(DDLObject ddl) => new(ddl);
}

