// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xafebbe10u)]
public class BossBotNefariousBlimpPrius : BotPrius, IDDLObjectType<BossBotNefariousBlimpPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xafebbe10u);

	public BossBotNefariousBlimpPrius(DDLObject ddl) : base(ddl) {
		AllowCelebrates = ddl.GetValue<bool>(0x6a3ad847u, AllowCelebrates);
		HoverShuffleData = ddl.GetObject<HoverShuffleData>(0x5d8cb773u);
		UseFirepointFacingForShuffle = ddl.GetValue<bool>(0xafd04b08u, UseFirepointFacingForShuffle);
		NefariousPilotAsset = ddl.GetValue<RivetAssetId>(0xaa27ccc1u, NefariousPilotAsset);
		LocatorToAttachPilot = ddl.GetString(0x0d1ba870) ?? LocatorToAttachPilot;
		NefariousPilotScale = ddl.GetValue<float>(0x44ceb319u, NefariousPilotScale);
	}

	[DDLRegistration(0xafebbe10u)]
	public bool AllowCelebrates { get; set; } = true;

	[DDLRegistration(0xafebbe10u)]
	public HoverShuffleData? HoverShuffleData { get; set; } = default;

	[DDLRegistration(0xafebbe10u)]
	public bool UseFirepointFacingForShuffle { get; set; } = false;

	[DDLRegistration(0xafebbe10u)]
	public RivetAssetId NefariousPilotAsset { get; set; } = default;

	[DDLRegistration(0xafebbe10u)]
	public string? LocatorToAttachPilot { get; set; } = "igLoc_nefarious_attach";

	[DDLRegistration(0xafebbe10u)]
	public float NefariousPilotScale { get; set; } = 1.00f;

	public new static BossBotNefariousBlimpPrius Create(DDLObject ddl) => new(ddl);
}

