// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x3e6ffb9cu)]
public class BotComboEntry : DDLObjectType, IDDLObjectType<BotComboEntry> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x3e6ffb9cu);

	public BotComboEntry(DDLObject ddl) : base(ddl) {
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		RandomWeighting = ddl.GetValue<float>(0xf4124721u, RandomWeighting);
		StartingCooldown = ddl.GetValue<float>(0xa589f45fu, StartingCooldown);
		Cooldown = ddl.GetValue<float>(0x246291a9u, Cooldown);
		SelectDistanceMin = ddl.GetValue<float>(0x6e4b941du, SelectDistanceMin);
		SelectDistanceMax = ddl.GetValue<float>(0x5246ab44u, SelectDistanceMax);
		SelectHeightMin = ddl.GetValue<float>(0x04bd9fecu, SelectHeightMin);
		SelectHeightMax = ddl.GetValue<float>(0x38b0a0b5u, SelectHeightMax);
		SelectHeightDiffMin = ddl.GetValue<float>(0xe132314eu, SelectHeightDiffMin);
		SelectHeightDiffMax = ddl.GetValue<float>(0xdd3f0e17u, SelectHeightDiffMax);
		SelectNavDistanceMax = ddl.GetValue<float>(0x52ba7e01u, SelectNavDistanceMax);
		Directional = ddl.GetValue<bool>(0xcadb15c2u, Directional);
		FaceTargetAngleTolerance = ddl.GetValue<float>(0x5f80a8dcu, FaceTargetAngleTolerance);
		CanBeResumed = ddl.GetValue<bool>(0xcd367664u, CanBeResumed);
		IsTopiaryRetaliate = ddl.GetValue<bool>(0xa3d1645cu, IsTopiaryRetaliate);
		ComboConditionList = ddl.GetObjects<BotComboConditionListEntry>(0x23425be8u);
		Moves = ddl.GetObjects<BotComboMoveContainer>(0x5c6cc4f3u);
	}

	[DDLRegistration(0x3e6ffb9cu, description: "Use to label this combo")]
	public string? Name { get; set; } = "";

	[DDLRegistration(0x3e6ffb9cu, "Random Weighting", "Relative chance of being chosen")]
	public float RandomWeighting { get; set; } = 1.00f;

	[DDLRegistration(0x3e6ffb9cu, "Starting Cooldown", "Initialize the combo with this cooldown")]
	public float StartingCooldown { get; set; } = 0.00f;

	[DDLRegistration(0x3e6ffb9cu, description: "Time until chosen again")]
	public float Cooldown { get; set; } = 0.00f;

	[DDLRegistration(0x3e6ffb9cu, "Select Distance Min", "We need to be at least this far from our target to select this combo")]
	public float SelectDistanceMin { get; set; } = 0.00f;

	[DDLRegistration(0x3e6ffb9cu, "Select Distance Max", "We need to be at least this close to our target to select this combo")]
	public float SelectDistanceMax { get; set; } = 1000.00f;

	[DDLRegistration(0x3e6ffb9cu, "Select Height Min", "Target can be a min of this high below nav mesh to select this combo")]
	public float SelectHeightMin { get; set; } = -1000.00f;

	[DDLRegistration(0x3e6ffb9cu, "Select Height Max", "Target can be a max of this high above nav mesh to select this combo")]
	public float SelectHeightMax { get; set; } = 1000.00f;

	[DDLRegistration(0x3e6ffb9cu, "Select Height Diff Min", "Difference in height of me and Target can be a min of this to select this combo")]
	public float SelectHeightDiffMin { get; set; } = -1000.00f;

	[DDLRegistration(0x3e6ffb9cu, "Select Height Diff Max", "Difference in height of me and Target can be a max of this to select this combo")]
	public float SelectHeightDiffMax { get; set; } = 1000.00f;

	[DDLRegistration(0x3e6ffb9cu, "Select Nav Distance Max", "The maximum XZ distance the target can be from navmesh for this to be a valid attack.")]
	public float SelectNavDistanceMax { get; set; } = -1.00f;

	[DDLRegistration(0x3e6ffb9cu, description: "Directional attacks don't need to be facing the target in order to begin.")]
	public bool Directional { get; set; } = false;

	[DDLRegistration(0x3e6ffb9cu, description: "Facing Angle toward the target greater than this makes bot re-orient and steer/turn towards target until within this angle")]
	public float FaceTargetAngleTolerance { get; set; } = 45.00f;

	[DDLRegistration(0x3e6ffb9cu, "Can Be Resumed", "Can this combo be continued if it gets interrupted?")]
	public bool CanBeResumed { get; set; } = false;

	[DDLRegistration(0x3e6ffb9cu, "Use for Topiary Retaliate", "If true, this combo will specifically only be used after getting shrubbed from topiary and target the topiary turret")]
	public bool IsTopiaryRetaliate { get; set; } = false;

	[DDLRegistration(0x3e6ffb9cu)]
	public List<BotComboConditionListEntry?> ComboConditionList { get; set; } = [];

	[DDLRegistration(0x3e6ffb9cu, description: "A sequence of moves in a combo")]
	public List<BotComboMoveContainer?> Moves { get; set; } = [];

	public static BotComboEntry Create(DDLObject ddl) => new(ddl);
}

