// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x388535efu)]
public class BotComboShockwave : BotComboMoveMelee, IDDLObjectType<BotComboShockwave> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x388535efu);

	public BotComboShockwave(DDLObject ddl) : base(ddl) {
		AnimDriver = ddl.GetString(0x10f54dce) ?? AnimDriver;
		SourceLocator = ddl.GetString(0xc54e6703) ?? SourceLocator;
		SourceIsActorEffectiveGround = ddl.GetValue<bool>(0x13119462u, SourceIsActorEffectiveGround);
		SourceOffset = ddl.GetObject<DDLVector3>(0x8e18c0c5u);
		Radius = ddl.GetValue<float>(0x0504203du, Radius);
		Thickness = ddl.GetValue<float>(0xece213a3u, Thickness);
		Height = ddl.GetValue<float>(0xcb35ab68u, Height);
		Duration = ddl.GetValue<float>(0x7c5e3db0u, Duration);
		GrowDuration = ddl.GetValue<float>(0xecfa5c44u, GrowDuration);
		Damage = ddl.GetValue<float>(0x2fb01a0bu, Damage);
		DamageType = ddl.GetEnum<DamageTypesGame>(0x840c154du, DamageTypesGameValues.Lookup);
		Knockback = ddl.GetEnum<KnockbackLevels>(0x2e553fddu, KnockbackLevelsValues.Lookup);
		DamageFriends = ddl.GetValue<byte>(0x3be354f0u, DamageFriends);
		StatusAmount = ddl.GetValue<float>(0x37e1f098u, StatusAmount);
		KnockbackForce = ddl.GetValue<float>(0x28d6ed59u, KnockbackForce);
	}

	[DDLRegistration(0x388535efu)]
	public string? AnimDriver { get; set; } = default;

	[DDLRegistration(0x388535efu)]
	public string? SourceLocator { get; set; } = default;

	[DDLRegistration(0x388535efu, description: "If true, instead of actor position or sourcelocator, we will have the shockwave start at mover's ground position below it")]
	public bool SourceIsActorEffectiveGround { get; set; } = false;

	[DDLRegistration(0x388535efu)]
	public DDLVector3? SourceOffset { get; set; } = default;

	[DDLRegistration(0x388535efu)]
	public float Radius { get; set; } = 0.00f;

	[DDLRegistration(0x388535efu)]
	public float Thickness { get; set; } = 0.00f;

	[DDLRegistration(0x388535efu)]
	public float Height { get; set; } = 0.00f;

	[DDLRegistration(0x388535efu)]
	public float Duration { get; set; } = 0.00f;

	[DDLRegistration(0x388535efu, description: "If greater than 0.0f, the shockwave will grow to radius by this time and then stick around til duration")]
	public float GrowDuration { get; set; } = -1.00f;

	[DDLRegistration(0x388535efu)]
	public float Damage { get; set; } = 0.00f;

	[DDLRegistration(0x388535efu, description: "Type of damage.")]
	public DamageTypesGame DamageType { get; set; } = DamageTypesGame.None;

	[DDLRegistration(0x388535efu, description: "Level of knockback applied.")]
	public KnockbackLevels Knockback { get; set; } = KnockbackLevels.Four;

	[DDLRegistration(0x388535efu)]
	public byte DamageFriends { get; set; } = 0x00;

	[DDLRegistration(0x388535efu)]
	public float StatusAmount { get; set; } = 0.00f;

	[DDLRegistration(0x388535efu)]
	public float KnockbackForce { get; set; } = 1.00f;

	public new static BotComboShockwave Create(DDLObject ddl) => new(ddl);
}

