// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x27163500u)]
public class BotCommandJumpToScriptActionPrius : DDLObjectType, IDDLObjectType<BotCommandJumpToScriptActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x27163500u);

	public BotCommandJumpToScriptActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.EnemyBot;

	public static BotCommandJumpToScriptActionPrius Create(DDLObject ddl) => new(ddl);
}

