// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xca9ad18eu)]
public class BotComboSelectMoveNodeBaseDef : ComboNodeBaseDef, IDDLObjectType<BotComboSelectMoveNodeBaseDef> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xca9ad18eu);

	public BotComboSelectMoveNodeBaseDef(DDLObject ddl) : base(ddl) {
		Queue = ddl.GetObject<InputPlugSignal>(0x66aeb3a2u);
		Weight = ddl.GetObject<InputPlugFloat>(0x39b51b26u);
		Selected = ddl.GetObject<OutputPlugSignal>(0x62a802f6u);
		MoveName = ddl.GetString(0xfacff3ba) ?? MoveName;
		ExcludeFromDebugMenu = ddl.GetValue<bool>(0x6ae3b41au, ExcludeFromDebugMenu);
	}

	[DDLRegistration(0xca9ad18eu)]
	public InputPlugSignal? Queue { get; set; } = default;

	[DDLRegistration(0xca9ad18eu)]
	public InputPlugFloat? Weight { get; set; } = default;

	[DDLRegistration(0xca9ad18eu)]
	public OutputPlugSignal? Selected { get; set; } = default;

	[DDLRegistration(0xca9ad18eu, "Move Name")]
	public string? MoveName { get; set; } = default;

	[DDLRegistration(0xca9ad18eu, "Exclude From Debug Menu")]
	public bool ExcludeFromDebugMenu { get; set; } = false;

	public new static BotComboSelectMoveNodeBaseDef Create(DDLObject ddl) => new(ddl);
}

