// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xb26bda52u)]
public class BotGeneratorComponentPrius : SpawnerObjectPrius, IDDLObjectType<BotGeneratorComponentPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xb26bda52u);

	public BotGeneratorComponentPrius(DDLObject ddl) : base(ddl) {
		SetBotDataFromSpawner = ddl.GetValue<bool>(0x2c40fa88u, SetBotDataFromSpawner);
	}

	[DDLRegistration(0x2c40fa88u)]
	public bool SetBotDataFromSpawner { get; set; } = true;

	public new static BotGeneratorComponentPrius Create(DDLObject ddl) => new(ddl);
}

