// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xd2123e7eu)]
public class BotGroundResponseBasePrius : GroundResponseBasePrius, IDDLObjectType<BotGroundResponseBasePrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xd2123e7eu);

	public BotGroundResponseBasePrius(DDLObject ddl) : base(ddl) { }

	public new static BotGroundResponseBasePrius Create(DDLObject ddl) => new(ddl);
}

