// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xbc4a2b4au)]
public class BotLaserShotMotionPrius : ShotMotionBasePrius, IDDLObjectType<BotLaserShotMotionPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xbc4a2b4au);

	public BotLaserShotMotionPrius(DDLObject ddl) : base(ddl) {
		CollRadius = ddl.GetValue<float>(0xc7f69ee3u, CollRadius);
		BotLaserCollType = ddl.GetEnum<x2056dab2>(0x180c3197u, x2056dab2Values.Lookup);
		UseLaserStartPos = ddl.GetValue<bool>(0x2df4b671u, UseLaserStartPos);
		UpdateLastHitPos = ddl.GetValue<bool>(0x6fcc4404u, UpdateLastHitPos);
	}

	[DDLRegistration(0xc7f69ee3u)]
	public float CollRadius { get; set; } = 0.10f;

	[DDLRegistration(0x180c3197u, "Laser Collision Type", "kDefault hits everything, kHeroOnly only looks for hero domain physics, kBotOnly in bot domain")]
	public x2056dab2 BotLaserCollType { get; set; } = x2056dab2.Default;

	[DDLRegistration(0x2df4b671u, "Use Laser Start Pos", "Use the laser start position from shot motion for beam VFX.")]
	public bool UseLaserStartPos { get; set; } = false;

	[DDLRegistration(0x6fcc4404u, "Update last Hit Pos", "If this is true, the beam VFX will stop/impact at the first hit position. Otherwise the laser will just go thru everything")]
	public bool UpdateLastHitPos { get; set; } = true;

	public new static BotLaserShotMotionPrius Create(DDLObject ddl) => new(ddl);
}

