// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x05f793ccu)]
public class BotSetupData : DDLObjectType, IDDLObjectType<BotSetupData> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x05f793ccu);

	public BotSetupData(DDLObject ddl) : base(ddl) {
		SpawnEngagedWithHero = ddl.GetValue<bool>(0xfcf12cc6u, SpawnEngagedWithHero);
		ForceHoverPathIntro = ddl.GetValue<bool>(0xb7777f84u, ForceHoverPathIntro);
		IntroIsInterruptibleByDamage = ddl.GetValue<bool>(0xe1fbf750u, IntroIsInterruptibleByDamage);
		IntroIsInterruptibleByDamageOnLand = ddl.GetValue<bool>(0xfea77be4u, IntroIsInterruptibleByDamageOnLand);
		IntroIsInterruptibleByMeleeRange = ddl.GetValue<bool>(0x4aa10542u, IntroIsInterruptibleByMeleeRange);
		IntroIsInterruptibleByAwareness = ddl.GetValue<bool>(0x814cc204u, IntroIsInterruptibleByAwareness);
		IntroIsInterruptibleByModeControl = ddl.GetValue<bool>(0x39192ff5u, IntroIsInterruptibleByModeControl);
		InterruptedIntroCanBeResumed = ddl.GetValue<bool>(0xb11e7b36u, InterruptedIntroCanBeResumed);
		IntroSpeed = ddl.GetEnum<MovementStyleGame>(0x236586cbu, MovementStyleGameValues.Lookup);
		SkipAlertAnim = ddl.GetValue<bool>(0x88656e30u, SkipAlertAnim);
		DisableIdleWander = ddl.GetValue<bool>(0xba0dad77u, DisableIdleWander);
		AllowRetaliation = ddl.GetValue<bool>(0x68b17a10u, AllowRetaliation);
		IdleWanderMinCooldown = ddl.GetValue<float>(0x123cb9aau, IdleWanderMinCooldown);
		IdleWanderMaxCooldown = ddl.GetValue<float>(0xde31c2a5u, IdleWanderMaxCooldown);
		AllowHibernationBasedOnLoadedRegion = ddl.GetValue<bool>(0xc7e3238bu, AllowHibernationBasedOnLoadedRegion);
		HomeContainerRegion = ddl.GetValue<RivetAssetId>(0xbcc039c0u, HomeContainerRegion);
	}

	[DDLRegistration(0x05f793ccu)]
	public bool SpawnEngagedWithHero { get; set; } = false;

	[DDLRegistration(0x05f793ccu, description: "Forces bots to use the hover class to do spawn path intros.")]
	public bool ForceHoverPathIntro { get; set; } = false;

	[DDLRegistration(0x05f793ccu, description: "Bot will interrupt its intro and try go engaged when damaged")]
	public bool IntroIsInterruptibleByDamage { get; set; } = false;

	[DDLRegistration(0x05f793ccu, description: "Bot will interrupt its intro and try go engaged when damaged if the damage happens after landing on the ground")]
	public bool IntroIsInterruptibleByDamageOnLand { get; set; } = true;

	[DDLRegistration(0x05f793ccu, description: "Bot will interrupt its intro and try go engaged when target within melee range")]
	public bool IntroIsInterruptibleByMeleeRange { get; set; } = true;

	[DDLRegistration(0x05f793ccu, description: "Bot will interrupt its intro and try go engaged when target within awareness and confirmed")]
	public bool IntroIsInterruptibleByAwareness { get; set; } = false;

	[DDLRegistration(0x05f793ccu, description: "Bot will interrupt its intro and try go engaged/modecontrolled when setup with ModeControl node")]
	public bool IntroIsInterruptibleByModeControl { get; set; } = true;

	[DDLRegistration(0x05f793ccu, description: "If the intro is interrupted, should we return to the intro once we are done with the interruption?")]
	public bool InterruptedIntroCanBeResumed { get; set; } = false;

	[DDLRegistration(0x05f793ccu)]
	public MovementStyleGame IntroSpeed { get; set; } = MovementStyleGame.Run;

	[DDLRegistration(0x05f793ccu, description: "Alert Behavior will just face and skip Alert Anims")]
	public bool SkipAlertAnim { get; set; } = false;

	[DDLRegistration(0x05f793ccu)]
	public bool DisableIdleWander { get; set; } = false;

	[DDLRegistration(0x05f793ccu)]
	public bool AllowRetaliation { get; set; } = true;

	[DDLRegistration(0x05f793ccu)]
	public float IdleWanderMinCooldown { get; set; } = 2.00f;

	[DDLRegistration(0x05f793ccu)]
	public float IdleWanderMaxCooldown { get; set; } = 6.00f;

	[DDLRegistration(0x05f793ccu)]
	public bool AllowHibernationBasedOnLoadedRegion { get; set; } = true;

	[DDLRegistration(0x05f793ccu, description: "Region where bot will be forced to call home. When this region unloads, bot will hibernate until it is loaded in again. By default bot just chooses whatever current loaded in container region is")]
	public RivetAssetId HomeContainerRegion { get; set; } = default;

	public static BotSetupData Create(DDLObject ddl) => new(ddl);
}

