// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x7a97bcf7u)]
public class BuildSettings : DDLObjectType, IDDLObjectType<BuildSettings> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x7a97bcf7u);

	public BuildSettings(DDLObject ddl) : base(ddl) {
		AssetBranch = ddl.GetString(0x2e958d29) ?? AssetBranch;
		VersionTag = ddl.GetString(0xcd0f4d6f) ?? VersionTag;
		ArchiveAssetsChangelist = ddl.GetValue<int>(0x6f3622cdu, ArchiveAssetsChangelist);
		TimeZone = ddl.GetString(0x6d32a0d9) ?? TimeZone;
	}

	[DDLRegistration(0x2e958d29u)]
	public string? AssetBranch { get; set; } = "";

	[DDLRegistration(0xcd0f4d6fu)]
	public string? VersionTag { get; set; } = "";

	[DDLRegistration(0x6f3622cdu)]
	public int ArchiveAssetsChangelist { get; set; } = -1;

	[DDLRegistration(0x6d32a0d9u)]
	public string? TimeZone { get; set; } = "";

	public static BuildSettings Create(DDLObject ddl) => new(ddl);
}

