// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xa5e2adfeu)]
public class BurstPistolInaccuracyData : DDLObjectType, IDDLObjectType<BurstPistolInaccuracyData> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xa5e2adfeu);

	public BurstPistolInaccuracyData(DDLObject ddl) : base(ddl) {
		InitialAngle = ddl.GetValue<float>(0x158e06dbu, InitialAngle);
		MinShotsToIncrease = ddl.GetValue<uint>(0x3ee300c4u, MinShotsToIncrease);
		AngleMax = ddl.GetValue<float>(0x475aea60u, AngleMax);
		IncreaseAnglePerShot = ddl.GetValue<float>(0xea409f8bu, IncreaseAnglePerShot);
		IncreaseAngleMax = ddl.GetValue<float>(0xc7fe4fd8u, IncreaseAngleMax);
		DecreaseDelay = ddl.GetValue<float>(0x4f49c248u, DecreaseDelay);
		DecreaseAnglePerSec = ddl.GetValue<float>(0xe33c63c7u, DecreaseAnglePerSec);
	}

	[DDLRegistration(0xa5e2adfeu, "Initial Angle")]
	public float InitialAngle { get; set; } = 0.50f;

	[DDLRegistration(0xa5e2adfeu, "Min Shots To Increase")]
	public uint MinShotsToIncrease { get; set; } = 0x00000003;

	[DDLRegistration(0xa5e2adfeu, "Angle Max")]
	public float AngleMax { get; set; } = 4.00f;

	[DDLRegistration(0xa5e2adfeu, "Increase Angle Per Shot")]
	public float IncreaseAnglePerShot { get; set; } = 0.10f;

	[DDLRegistration(0xa5e2adfeu, "Increase Angle Max")]
	public float IncreaseAngleMax { get; set; } = 0.50f;

	[DDLRegistration(0xa5e2adfeu, "Decrease Delay")]
	public float DecreaseDelay { get; set; } = 0.20f;

	[DDLRegistration(0xa5e2adfeu, "Decrease Angle Per Sec")]
	public float DecreaseAnglePerSec { get; set; } = 5.00f;

	public static BurstPistolInaccuracyData Create(DDLObject ddl) => new(ddl);
}

