// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x3ae61082u)]
public class BurstSequence : DDLObjectType, IDDLObjectType<BurstSequence> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x3ae61082u);

	public BurstSequence(DDLObject ddl) : base(ddl) {
		PrimaryBurst = ddl.GetObject<Burst>(0x8bc798e7u);
		SubBursts = ddl.GetObjects<SubBurst>(0x333f5038u);
		TotalDuration = ddl.GetValue<float>(0xc004400cu, TotalDuration);
		TotalBurstShots = ddl.GetValue<int>(0xd2ed5de5u, TotalBurstShots);
		WaitDurationMin = ddl.GetValue<float>(0xd348255du, WaitDurationMin);
		WaitDurationMax = ddl.GetValue<float>(0xef451a04u, WaitDurationMax);
		WaitDuration = ddl.GetValue<float>(0xe3655ff0u, WaitDuration);
	}

	[DDLRegistration(0x3ae61082u)]
	public Burst? PrimaryBurst { get; set; } = default;

	[DDLRegistration(0x3ae61082u)]
	public List<SubBurst?> SubBursts { get; set; } = [];

	[DDLRegistration(0x3ae61082u)]
	public float TotalDuration { get; set; } = 0.00f;

	[DDLRegistration(0x3ae61082u)]
	public int TotalBurstShots { get; set; } = 0;

	[DDLRegistration(0x3ae61082u)]
	public float WaitDurationMin { get; set; } = 1.00f;

	[DDLRegistration(0x3ae61082u)]
	public float WaitDurationMax { get; set; } = 2.00f;

	[DDLRegistration(0x3ae61082u)]
	public float WaitDuration { get; set; } = 0.00f;

	public static BurstSequence Create(DDLObject ddl) => new(ddl);
}

