// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x9f685b25u)]
public class CentipedeFlyoverDeathEvent : EventBase, IDDLObjectType<CentipedeFlyoverDeathEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x9f685b25u);

	public CentipedeFlyoverDeathEvent(DDLObject ddl) : base(ddl) { }

	public new static CentipedeFlyoverDeathEvent Create(DDLObject ddl) => new(ddl);
}

