// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xd2b0eda2u)]
public class ChangeLocationEvent : LocationChangeEvent, IDDLObjectType<ChangeLocationEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xd2b0eda2u);

	public ChangeLocationEvent(DDLObject ddl) : base(ddl) { }

	public new static ChangeLocationEvent Create(DDLObject ddl) => new(ddl);
}

