// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x4a1e78f3u)]
public class ChemicalRenderOverride : DDLObjectType, IDDLObjectType<ChemicalRenderOverride> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x4a1e78f3u);

	public ChemicalRenderOverride(DDLObject ddl) : base(ddl) {
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		Type = ddl.GetEnum<x18f892a3>(0xbc4e9799u, x18f892a3Values.Lookup);
		Constants = ddl.GetObject<DDLVector4>(0x11306034u);
		Color = ddl.GetObject<DDLVector3>(0x7f058428u);
		Texture = ddl.GetValue<RivetAssetId>(0x838c6e4au, Texture);
	}

	[DDLRegistration(0x6eb3beb6u, description: "Name of the node in the materialgraph this is overriding.")]
	public string? Name { get; set; } = default;

	[DDLRegistration(0xbc4e9799u, description: "What type of node is this overriding?")]
	public x18f892a3 Type { get; set; } = x18f892a3.Constant;

	[DDLRegistration(0x11306034u)]
	public DDLVector4? Constants { get; set; } = default;

	[DDLRegistration(0x7f058428u)]
	public DDLVector3? Color { get; set; } = default;

	[DDLRegistration(0x838c6e4au)]
	public RivetAssetId Texture { get; set; } = default;

	public static ChemicalRenderOverride Create(DDLObject ddl) => new(ddl);
}

