// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x2aeac8e5u)]
public class ChildDiedEvent : EventBase, IDDLObjectType<ChildDiedEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x2aeac8e5u);

	public ChildDiedEvent(DDLObject ddl) : base(ddl) {
		ChildActorHandle = ddl.GetValue<uint>(0x789058e3u, ChildActorHandle);
	}

	[DDLRegistration(0x789058e3u)]
	public uint ChildActorHandle { get; set; } = 0x00000000;

	public new static ChildDiedEvent Create(DDLObject ddl) => new(ddl);
}

