// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xc22aaf9cu)]
public class Cinematic2ActorVfxTrackDef : DDLObjectType, IDDLObjectType<Cinematic2ActorVfxTrackDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xc22aaf9cu);

	public Cinematic2ActorVfxTrackDef(DDLObject ddl) : base(ddl) {
		Id = ddl.GetValue<RivetAssetId>(0x8a514a8du, Id);
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		PlatformFilter = ddl.GetBitset<xb52df7e7>(0x92542397u, xb52df7e7Values.Lookup);
		Tags = ddl.GetObject<Cinematic2TrackTagsDef>(0x5f2c5496u);
		Global = ddl.GetValue<bool>(0xd67dc5e4u, Global);
		Actions = ddl.GetDictionary<RivetAssetId, Cinematic2VfxActionDef>(0x04a292d7, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2VfxActionDef>(mapId));
		Modifiers = ddl.GetDictionary<RivetAssetId, Cinematic2VfxModifierDef>(0x5a54617f, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2VfxModifierDef>(mapId));
	}

	[DDLRegistration(0xc22aaf9cu)]
	public RivetAssetId Id { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0xc22aaf9cu)]
	public string? Name { get; set; } = default;

	[DDLRegistration(0xc22aaf9cu, description: "Track will only run on the defined platform(s)")]
	public xb52df7e7 PlatformFilter { get; set; } = (xb52df7e7) 0x00000007;

	[DDLRegistration(0xc22aaf9cu, description: "A set of gameplay-defined values to determine if this track should be processed.")]
	public Cinematic2TrackTagsDef? Tags { get; set; } = default;

	[DDLRegistration(0xc22aaf9cu, description: "If set to true, actions on this track will not move when shots are reordered.")]
	public bool Global { get; set; } = false;

	[DDLRegistration(0xc22aaf9cu)]
	public Dictionary<RivetAssetId, Cinematic2VfxActionDef?> Actions { get; set; } = [];

	[DDLRegistration(0xc22aaf9cu)]
	public Dictionary<RivetAssetId, Cinematic2VfxModifierDef?> Modifiers { get; set; } = [];

	public static Cinematic2ActorVfxTrackDef Create(DDLObject ddl) => new(ddl);
}

