// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xca6a194cu)]
public class Cinematic2Def : DDLObjectType, IDDLObjectType<Cinematic2Def> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xca6a194cu);

	public Cinematic2Def(DDLObject ddl) : base(ddl) {
		VaultMetaData = ddl.GetObject<VaultMetaData>(0x037889aau);
		IconPath = ddl.GetValue<RivetAssetId>(0xbf5b007fu, IconPath);
		AtmospherePath = ddl.GetValue<RivetAssetId>(0x37ea75eeu, AtmospherePath);
		PreviewLightingZonePath = ddl.GetValue<RivetAssetId>(0x705b4298u, PreviewLightingZonePath);
		PreviewLightingCondition = ddl.GetEnum<LightingConditions>(0x0fd8f05au, LightingConditionsValues.Lookup);
		Looping = ddl.GetValue<bool>(0x36c12525u, Looping);
		Letterboxed = ddl.GetValue<bool>(0x196a29f4u, Letterboxed);
		EnableStreaming = ddl.GetValue<bool>(0xda704640u, EnableStreaming);
		IsQte = ddl.GetValue<bool>(0x292c4c30u, IsQte);
		Skippable = ddl.GetValue<bool>(0xf0dc1233u, Skippable);
		ResetOnFinished = ddl.GetValue<bool>(0x4aa36328u, ResetOnFinished);
		MayaPlayBackCompensate = ddl.GetValue<bool>(0xe7529d9bu, MayaPlayBackCompensate);
		OnEnterCameraTransitionDuration = ddl.GetValue<float>(0x288a5cd6u, OnEnterCameraTransitionDuration);
		OnExitCameraTransitionDuration = ddl.GetValue<float>(0x0206b18au, OnExitCameraTransitionDuration);
		AspectBlur = ddl.GetObject<Cinematic2AspectBlurDef>(0xa4c85069u);
		Tags = ddl.GetObject<Cinematic2TagsDef>(0x5f2c5496u);
		RunGameOptions = ddl.GetObject<Cinematic2RunGameOptions>(0x98cf3861u);
		ToTexture = ddl.GetObject<Cinematic2ToTextureDef>(0x10c740fcu);
		FromTexture = ddl.GetObject<Cinematic2FromTextureDef>(0xb405f966u);
		ActorCustomizationConfig = ddl.GetValue<RivetAssetId>(0x5d0f4089u, ActorCustomizationConfig);
		ShotOrder = ddl.GetValues<RivetAssetId>(0xb153f7e6u);
		AtmosphereTrack = ddl.GetObject<Cinematic2GlobalAtmosphereTrackDef>(0xd3d07b3bu);
		AudioListenerTrack = ddl.GetObject<Cinematic2GlobalAudioListenerTrackDef>(0xcbfe62f1u);
		MasterFaderTrack = ddl.GetObject<Cinematic2GlobalAudioFaderTrackDef>(0x5ef83290u);
		MusicTrack = ddl.GetObject<Cinematic2GlobalMusicTrackDef>(0xc500fd1bu);
		RateTrack = ddl.GetObject<Cinematic2GlobalRateTrackDef>(0x37fe8abau);
		SyncTrack = ddl.GetObject<Cinematic2GlobalSyncTrackDef>(0x9a2c94fau);
		TransitionTrack = ddl.GetObject<Cinematic2GlobalTransitionTrackDef>(0xf7c6e718u);
		VfxModifierTrack = ddl.GetObject<Cinematic2GlobalVfxModifierTrackDef>(0x5b97322fu);
		ZoneTrack = ddl.GetObject<Cinematic2GlobalZoneTrackDef>(0x5a02f910u);
		TagTrack = ddl.GetObject<Cinematic2GlobalTagTrackDef>(0x5e09a57fu);
	}

	[DDLRegistration(0xca6a194cu)]
	public VaultMetaData? VaultMetaData { get; set; } = default;

	[DDLRegistration(0xca6a194cu)]
	public RivetAssetId IconPath { get; set; } = "";

	[DDLRegistration(0xca6a194cu, description: "Specifies the atmosphere to use during the cinematic.")]
	public RivetAssetId AtmospherePath { get; set; } = default;

	[DDLRegistration(0xca6a194cu, description: "Zone used for previewing lighting conditions in the cine-editor (if different from the lighting zone used in project.set). This field has no impact in game.")]
	public RivetAssetId PreviewLightingZonePath { get; set; } = default;

	[DDLRegistration(0xca6a194cu, description: "Default lighting condition used by the cine-editor. This field has no impact in game.")]
	public LightingConditions PreviewLightingCondition { get; set; } = LightingConditions.Day;

	[DDLRegistration(0xca6a194cu, description: "Specifies whether or not the cinematic loops.")]
	public bool Looping { get; set; } = false;

	[DDLRegistration(0xca6a194cu, description: "Specifies whether or not the cinematic is letterboxed at 2.4 aspect ratio.")]
	public bool Letterboxed { get; set; } = false;

	[DDLRegistration(0xca6a194cu, description: "Specifies whether to stream the animation data.")]
	public bool EnableStreaming { get; set; } = false;

	[DDLRegistration(0xca6a194cu, description: "Specifies this is a QTE (gameplay driven) cinematic.")]
	public bool IsQte { get; set; } = false;

	[DDLRegistration(0xca6a194cu, description: "Allows cinematic to be skipped in game.")]
	public bool Skippable { get; set; } = false;

	[DDLRegistration(0xca6a194cu, description: "When cinematic finishes, reinitialize to ready state. Enable this if want a cine to get back to ready state after finishing.")]
	public bool ResetOnFinished { get; set; } = true;

	[DDLRegistration(0xca6a194cu, description: "When music is scored with maya play back for i29 and i31")]
	public bool MayaPlayBackCompensate { get; set; } = false;

	[DDLRegistration(0xca6a194cu, description: "Specifies the transition from the game camera to the cinematic camera when the cinematic starts.")]
	public float OnEnterCameraTransitionDuration { get; set; } = 0.00f;

	[DDLRegistration(0xca6a194cu, description: "Specifies the transition from the cinematic camera to the game camera when the cinematic ends.")]
	public float OnExitCameraTransitionDuration { get; set; } = 0.00f;

	[DDLRegistration(0xca6a194cu, description: "Aspect Blur Settings")]
	public Cinematic2AspectBlurDef? AspectBlur { get; set; } = default;

	[DDLRegistration(0xca6a194cu, description: "A set of gameplay-defined values used when processing this cine.")]
	public Cinematic2TagsDef? Tags { get; set; } = default;

	[DDLRegistration(0xca6a194cu, description: "Options to automatically populate in the Tools Hub's Run Game panel when clicking Run Game from the Cinematic Editor or from the Asset Editor with a Cinematic open.")]
	public Cinematic2RunGameOptions? RunGameOptions { get; set; } = default;

	[DDLRegistration(0xca6a194cu, description: "Specifies the render-to-texture settings")]
	public Cinematic2ToTextureDef? ToTexture { get; set; } = default;

	[DDLRegistration(0xca6a194cu, description: "Specified the render-from-texture settings ")]
	public Cinematic2FromTextureDef? FromTexture { get; set; } = default;

	[DDLRegistration(0xca6a194cu, description: "This specifies the Hero customization config file.")]
	public RivetAssetId ActorCustomizationConfig { get; set; } = "configs/Cinematic2ActorCustomization/Cinematic2ActorCustomization.config";

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, RivetAssetId> PreviewRegions { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2UserRegionDef?> UserRegions { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2CameraTrackDef?> Cameras { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2LightGroupDef?> LightGroups { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public List<RivetAssetId> ShotOrder { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2ShotDef?> Shots { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2ActorDef?> Actors { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2LightDef?> Lights { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2LocatorDef?> Locators { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Cinematic2GlobalAtmosphereTrackDef? AtmosphereTrack { get; set; } = default;

	[DDLRegistration(0xca6a194cu)]
	public Cinematic2GlobalAudioListenerTrackDef? AudioListenerTrack { get; set; } = default;

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2GlobalAudioGameSyncGroupTrackDef?> AudioStateGroupTracks { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2GlobalEventTrackDef?> EventTracks { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2GlobalMovieTrackDef?> MovieTracks { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Cinematic2GlobalAudioFaderTrackDef? MasterFaderTrack { get; set; } = default;

	[DDLRegistration(0xca6a194cu)]
	public Cinematic2GlobalMusicTrackDef? MusicTrack { get; set; } = default;

	[DDLRegistration(0xca6a194cu)]
	public Cinematic2GlobalRateTrackDef? RateTrack { get; set; } = default;

	[DDLRegistration(0xca6a194cu)]
	public Cinematic2GlobalSyncTrackDef? SyncTrack { get; set; } = default;

	[DDLRegistration(0xca6a194cu)]
	public Cinematic2GlobalTransitionTrackDef? TransitionTrack { get; set; } = default;

	[DDLRegistration(0xca6a194cu)]
	public Cinematic2GlobalVfxModifierTrackDef? VfxModifierTrack { get; set; } = default;

	[DDLRegistration(0xca6a194cu)]
	public Cinematic2GlobalZoneTrackDef? ZoneTrack { get; set; } = default;

	[DDLRegistration(0xca6a194cu)]
	public Cinematic2GlobalTagTrackDef? TagTrack { get; set; } = default;

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2FolderDef?> Folders { get; set; } = [];

	[DDLRegistration(0xca6a194cu)]
	public Dictionary<RivetAssetId, Cinematic2GlobalOrphanTrackDef?> OrphanTracks { get; set; } = [];

	public static Cinematic2Def Create(DDLObject ddl) => new(ddl);
}

