// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x57c000e8u)]
public class CritterLocationWeights : DDLObjectType, IDDLObjectType<CritterLocationWeights> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x57c000e8u);

	public CritterLocationWeights(DDLObject ddl) : base(ddl) {
		DistanceFactor = ddl.GetValue<float>(0xf4e39365u, DistanceFactor);
		AngleFactor = ddl.GetValue<float>(0x85b1ef42u, AngleFactor);
		VisibleFactor = ddl.GetValue<float>(0xa2dc7d9eu, VisibleFactor);
		ActiveBias = ddl.GetValue<float>(0x1a1b7ea4u, ActiveBias);
	}

	[DDLRegistration(0x57c000e8u, "Distance Factor", "How much distance from the hero factors into the critter spawn location selection.")]
	public float DistanceFactor { get; set; } = 1.00f;

	[DDLRegistration(0x57c000e8u, "Angle Factor", "How much the angle the location makes to the camera factors into critter spawn location selection.")]
	public float AngleFactor { get; set; } = 1.00f;

	[DDLRegistration(0x57c000e8u, "On-Screen Factor", "How much being on-screen factors into the location selection. This will penalize inactive locations that are on-screen.")]
	public float VisibleFactor { get; set; } = 1.00f;

	[DDLRegistration(0x57c000e8u, "Active Location Bias", "Bias towards locations that are already active by this amount to prevent critter spawn thrashing.")]
	public float ActiveBias { get; set; } = 0.25f;

	public static CritterLocationWeights Create(DDLObject ddl) => new(ddl);
}

