// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x051a56c1u)]
public class DamageModifierExplosionTargetTypePrius : DDLObjectType, IDDLObjectType<DamageModifierExplosionTargetTypePrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x051a56c1u);

	public DamageModifierExplosionTargetTypePrius(DDLObject ddl) : base(ddl) {
		Damages = ddl.GetObjects<TargetTypeDamage>(0x5ef14914u);
	}

	[DDLRegistration(0x051a56c1u)]
	public List<TargetTypeDamage?> Damages { get; set; } = [];

	public static DamageModifierExplosionTargetTypePrius Create(DDLObject ddl) => new(ddl);
}

