// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xa5be23efu)]
public class DeactivateAnimDriverLayerEngineItem : DDLObjectType, IDDLObjectType<DeactivateAnimDriverLayerEngineItem> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xa5be23efu);

	public DeactivateAnimDriverLayerEngineItem(DDLObject ddl) : base(ddl) {
		AnimDriverName = ddl.GetString(0x45f98c1e) ?? AnimDriverName;
	}

	[DDLRegistration(0x45f98c1eu)]
	public string? AnimDriverName { get; set; } = default;

	public static DeactivateAnimDriverLayerEngineItem Create(DDLObject ddl) => new(ddl);
}

