// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x267e76e5u)]
public class DebugLink : ActivityLinkBase, IDDLObjectType<DebugLink> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x267e76e5u);

	public DebugLink(DDLObject ddl) : base(ddl) {
		ActivityState = ddl.GetEnum<DebugLinkState>(0x03cab4e3u, DebugLinkStateValues.Lookup);
	}

	[DDLRegistration(0x267e76e5u)]
	public DebugLinkState ActivityState { get; set; } = DebugLinkState.ActiveAndAvailable;

	public new static DebugLink Create(DDLObject ddl) => new(ddl);
}

