// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x0a1cae18u)]
public class DepthOfFieldSettingsDef : DDLObjectType, IDDLObjectType<DepthOfFieldSettingsDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x0a1cae18u);

	public DepthOfFieldSettingsDef(DDLObject ddl) : base(ddl) {
		Enabled = ddl.GetValue<bool>(0x5113d8bcu, Enabled);
		NearFocusDistance = ddl.GetValue<float>(0xd6c519d5u, NearFocusDistance);
		NearApertureScale = ddl.GetValue<float>(0x172fcbcfu, NearApertureScale);
		FocusDistance = ddl.GetValue<float>(0x546334a6u, FocusDistance);
		ApertureScale = ddl.GetValue<float>(0x9589e6bcu, ApertureScale);
	}

	[DDLRegistration(0x0a1cae18u)]
	public bool Enabled { get; set; } = false;

	[DDLRegistration(0x0a1cae18u, "Near Focus Distance")]
	public float NearFocusDistance { get; set; } = 0.00f;

	[DDLRegistration(0x0a1cae18u, "Near Aperture Scale")]
	public float NearApertureScale { get; set; } = 0.00f;

	[DDLRegistration(0x0a1cae18u, "Far Focus Distance")]
	public float FocusDistance { get; set; } = 100.00f;

	[DDLRegistration(0x0a1cae18u, "Far Aperture Scale")]
	public float ApertureScale { get; set; } = 0.00f;

	public static DepthOfFieldSettingsDef Create(DDLObject ddl) => new(ddl);
}

