// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xbc3eea41u)]
public class DevstatsPlayerDeathDealtEvent : EventBase, IDDLObjectType<DevstatsPlayerDeathDealtEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xbc3eea41u);

	public DevstatsPlayerDeathDealtEvent(DDLObject ddl) : base(ddl) {
		EventId = ddl.GetString(0x2ac4d854) ?? EventId;
		Victim = ddl.GetValue<uint>(0x3bb4414eu, Victim);
		DevstatsName = ddl.GetString(0x74ba9afa) ?? DevstatsName;
		PlayerPosInfo = ddl.GetObject<DevstatsPlayerPositionInfo>(0xeadcc3e4u);
		PrimarySegmentInfo = ddl.GetObject<DevstatsPrimarySegmentInfo>(0x9e8725dbu);
	}

	[DDLRegistration(0xbc3eea41u)]
	public string? EventId { get; set; } = default;

	[DDLRegistration(0xbc3eea41u)]
	public uint Victim { get; set; } = 0x00000000;

	[DDLRegistration(0xbc3eea41u)]
	public string? DevstatsName { get; set; } = default;

	[DDLRegistration(0xbc3eea41u)]
	public DevstatsPlayerPositionInfo? PlayerPosInfo { get; set; } = default;

	[DDLRegistration(0xbc3eea41u)]
	public DevstatsPrimarySegmentInfo? PrimarySegmentInfo { get; set; } = default;

	public new static DevstatsPlayerDeathDealtEvent Create(DDLObject ddl) => new(ddl);
}

