// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x2a7d73c9u)]
public class DevstatsPlayerWeaponFiredEvent : EventBase, IDDLObjectType<DevstatsPlayerWeaponFiredEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x2a7d73c9u);

	public DevstatsPlayerWeaponFiredEvent(DDLObject ddl) : base(ddl) {
		EventId = ddl.GetString(0x2ac4d854) ?? EventId;
		DevstatsName = ddl.GetString(0x74ba9afa) ?? DevstatsName;
		PlayerPosInfo = ddl.GetObject<DevstatsPlayerPositionInfo>(0xeadcc3e4u);
		PrimarySegmentInfo = ddl.GetObject<DevstatsPrimarySegmentInfo>(0x9e8725dbu);
	}

	[DDLRegistration(0x2a7d73c9u)]
	public string? EventId { get; set; } = default;

	[DDLRegistration(0x2a7d73c9u)]
	public string? DevstatsName { get; set; } = default;

	[DDLRegistration(0x2a7d73c9u)]
	public DevstatsPlayerPositionInfo? PlayerPosInfo { get; set; } = default;

	[DDLRegistration(0x2a7d73c9u)]
	public DevstatsPrimarySegmentInfo? PrimarySegmentInfo { get; set; } = default;

	public new static DevstatsPlayerWeaponFiredEvent Create(DDLObject ddl) => new(ddl);
}

