// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x2e683e16u)]
public class DialogGroupSingleLine : DDLObjectType, IDDLObjectType<DialogGroupSingleLine> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x2e683e16u);

	public DialogGroupSingleLine(DDLObject ddl) : base(ddl) {
		LocTag = ddl.GetString(0x06f8b0e5) ?? LocTag;
	}

	[DDLRegistration(0x2e683e16u, "Localization Tag")]
	public string? LocTag { get; set; } = default;

	public static DialogGroupSingleLine Create(DDLObject ddl) => new(ddl);
}

