// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x22e3b5bbu)]
public class ECMEventDef : DDLObjectType, IDDLObjectType<ECMEventDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x22e3b5bbu);

	public ECMEventDef(DDLObject ddl) : base(ddl) {
		EventName = ddl.GetString(0x2048921d) ?? EventName;
		Filters = ddl.GetDictionary<RivetAssetId, ECMFilterDef>(0x799d04b5, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<ECMFilterDef>(mapId));
	}

	[DDLRegistration(0x2048921du)]
	public string? EventName { get; set; } = default;

	[DDLRegistration(0x799d04b5u)]
	public Dictionary<RivetAssetId, ECMFilterDef?> Filters { get; set; } = [];

	public static ECMEventDef Create(DDLObject ddl) => new(ddl);
}

