// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xb7d4348eu)]
public class ElectricArcEvent : EventBase, IDDLObjectType<ElectricArcEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xb7d4348eu);

	public ElectricArcEvent(DDLObject ddl) : base(ddl) {
		TargetHandle = ddl.GetValue<uint>(0x63316affu, TargetHandle);
	}

	[DDLRegistration(0xb7d4348eu)]
	public uint TargetHandle { get; set; } = 0x00000000;

	public new static ElectricArcEvent Create(DDLObject ddl) => new(ddl);
}

