// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xbfef7520u)]
public class FarmOpenRegionData : DDLObjectType, IDDLObjectType<FarmOpenRegionData> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xbfef7520u);

	public FarmOpenRegionData(DDLObject ddl) : base(ddl) {
		AtmosphereZone = ddl.GetValue<RivetAssetId>(0x9c553ee6u, AtmosphereZone);
		RegionFile = ddl.GetValue<RivetAssetId>(0xcabd3504u, RegionFile);
		LevelFile = ddl.GetValue<RivetAssetId>(0xc002f04bu, LevelFile);
		GlobalRegions = ddl.GetValues<RivetAssetId>(0x44015029u);
		ExtraZonesPerTile = ddl.GetObjects<FarmExtraTileZoneData>(0x1ed0234cu);
	}

	[DDLRegistration(0xbfef7520u, "Atmosphere Zone", "specifies atmospheres to use for capture.")]
	public RivetAssetId AtmosphereZone { get; set; } = default;

	[DDLRegistration(0xbfef7520u, "Region", ".region file")]
	public RivetAssetId RegionFile { get; set; } = default;

	[DDLRegistration(0xbfef7520u, "Level", ".level file for this region. If not specified, the default level is used.")]
	public RivetAssetId LevelFile { get; set; } = default;

	[DDLRegistration(0xbfef7520u, "Region", "regions that should be checked for zones that are always loaded when capturing tiles")]
	public List<RivetAssetId> GlobalRegions { get; set; } = [];

	[DDLRegistration(0xbfef7520u, "Extra Zones Per Tile", "Extra zones to load for various tiles. Use for zones that do not match the naming convention")]
	public List<FarmExtraTileZoneData?> ExtraZonesPerTile { get; set; } = [];

	public static FarmOpenRegionData Create(DDLObject ddl) => new(ddl);
}

