// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x1b0a01cdu)]
public class FarmInstanceRegionData : DDLObjectType, IDDLObjectType<FarmInstanceRegionData> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x1b0a01cdu);

	public FarmInstanceRegionData(DDLObject ddl) : base(ddl) {
		AtmosphereZone = ddl.GetValue<RivetAssetId>(0x9c553ee6u, AtmosphereZone);
		RegionFile = ddl.GetValue<RivetAssetId>(0xcabd3504u, RegionFile);
		LevelFile = ddl.GetValue<RivetAssetId>(0xc002f04bu, LevelFile);
		ExtraZones = ddl.GetValues<RivetAssetId>(0x56657350u);
	}

	[DDLRegistration(0x9c553ee6u, "Atmosphere Zone", "specifies atmospheres to use for capture.")]
	public RivetAssetId AtmosphereZone { get; set; } = default;

	[DDLRegistration(0xcabd3504u, "Region", ".region file")]
	public RivetAssetId RegionFile { get; set; } = default;

	[DDLRegistration(0xc002f04bu, "Level", ".level file for this region. If not specified, the default level is used.")]
	public RivetAssetId LevelFile { get; set; } = default;

	[DDLRegistration(0x56657350u, "Extra Zones", "Additional zones to load when capturing this region")]
	public List<RivetAssetId> ExtraZones { get; set; } = [];

	public static FarmInstanceRegionData Create(DDLObject ddl) => new(ddl);
}

