// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x84462aceu)]
public class FiringBasePrius : DDLObjectType, IDDLObjectType<FiringBasePrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x84462aceu);

	public FiringBasePrius(DDLObject ddl) : base(ddl) {
		BurstSequence = ddl.GetObject<BurstSequence>(0x3ae61082u);
		TriggerIndex = ddl.GetValue<uint>(0xee73b5b3u, TriggerIndex);
		MinFiringDot = ddl.GetValue<float>(0x9e5cb03du, MinFiringDot);
		ShortRange = ddl.GetValue<float>(0xb49295fau, ShortRange);
		IdealRange = ddl.GetValue<float>(0x4a596da2u, IdealRange);
		LongRange = ddl.GetValue<float>(0x8d74c10fu, LongRange);
		MaxRange = ddl.GetValue<float>(0x8a199ddeu, MaxRange);
		NeedsLos = ddl.GetValue<bool>(0x9c24d08eu, NeedsLos);
		NeedsJob = ddl.GetValue<bool>(0xf2198cceu, NeedsJob);
		RankTargetLocs = ddl.GetValue<bool>(0xf36caef5u, RankTargetLocs);
		AimType = ddl.GetEnum<x4f5e74b9>(0xf2b63172u, x4f5e74b9Values.Lookup);
		HoldFireForVictimStates = ddl.GetValue<bool>(0xfa0f2332u, HoldFireForVictimStates);
		AvoidShootingFriends = ddl.GetValue<bool>(0x64355aafu, AvoidShootingFriends);
		FireAtUnseenTargetsTime = ddl.GetValue<float>(0x58a02877u, FireAtUnseenTargetsTime);
		TargetLocation = ddl.GetEnum<x457f748b>(0x4a90422fu, x457f748bValues.Lookup);
		TargetLocationName = ddl.GetString(0xb352ca76) ?? TargetLocationName;
		Aiming = ddl.GetObject<AimingBasePrius>(0x7ed24ba4u);
		AimMods = ddl.GetObjects<AimModWrapper>(0x1d7694a1u);
		BotConfigAiming = ddl.GetValue<RivetAssetId>(0x8d73a96bu, BotConfigAiming);
	}

	[DDLRegistration(0x3ae61082u)]
	public BurstSequence? BurstSequence { get; set; } = default;

	[DDLRegistration(0xee73b5b3u)]
	public uint TriggerIndex { get; set; } = 0x00000000;

	[DDLRegistration(0x9e5cb03du)]
	public float MinFiringDot { get; set; } = 0.97f;

	[DDLRegistration(0xb49295fau)]
	public float ShortRange { get; set; } = 1.00f;

	[DDLRegistration(0x4a596da2u)]
	public float IdealRange { get; set; } = 20.00f;

	[DDLRegistration(0x8d74c10fu)]
	public float LongRange { get; set; } = 40.00f;

	[DDLRegistration(0x8a199ddeu)]
	public float MaxRange { get; set; } = 100.00f;

	[DDLRegistration(0x9c24d08eu)]
	public bool NeedsLos { get; set; } = true;

	[DDLRegistration(0xf2198cceu)]
	public bool NeedsJob { get; set; } = false;

	[DDLRegistration(0xf36caef5u)]
	public bool RankTargetLocs { get; set; } = false;

	[DDLRegistration(0xf2b63172u)]
	public x4f5e74b9 AimType { get; set; } = x4f5e74b9.BestVisibleLocation;

	[DDLRegistration(0xfa0f2332u)]
	public bool HoldFireForVictimStates { get; set; } = true;

	[DDLRegistration(0x64355aafu)]
	public bool AvoidShootingFriends { get; set; } = true;

	[DDLRegistration(0x58a02877u)]
	public float FireAtUnseenTargetsTime { get; set; } = -1.00f;

	[DDLRegistration(0x4a90422fu, description: "If AimType is kTargetLocation, target this particular location")]
	public x457f748b TargetLocation { get; set; } = x457f748b.Unknown;

	[DDLRegistration(0xb352ca76u, description: "If the body part is kLocationNamed, this identifies the specific part")]
	public string? TargetLocationName { get; set; } = default;

	[DDLRegistration(0x7ed24ba4u)]
	public AimingBasePrius? Aiming { get; set; } = default;

	[DDLRegistration(0x1d7694a1u)]
	public List<AimModWrapper?> AimMods { get; set; } = [];

	[DDLRegistration(0x8d73a96bu)]
	public RivetAssetId BotConfigAiming { get; set; } = default;

	public static FiringBasePrius Create(DDLObject ddl) => new(ddl);
}

