// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xcb01aa04u)]
public class FixedCameraPrius : PlacedCameraPrius, IDDLObjectType<FixedCameraPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xcb01aa04u);

	public FixedCameraPrius(DDLObject ddl) : base(ddl) {
		YawMin = ddl.GetValue<float>(0x975af737u, YawMin);
		YawMax = ddl.GetValue<float>(0xab57c86eu, YawMax);
		PitchMin = ddl.GetValue<float>(0xfb99e53bu, PitchMin);
		PitchMax = ddl.GetValue<float>(0xc794da62u, PitchMax);
		InitialPitch = ddl.GetValue<float>(0x3290fd0bu, InitialPitch);
		InitialYaw = ddl.GetValue<float>(0x7ddfeff9u, InitialYaw);
		ZeroSettle = ddl.GetValue<bool>(0xc455894bu, ZeroSettle);
		LockPosition = ddl.GetValue<bool>(0x68b14458u, LockPosition);
		ResetOnActivate = ddl.GetValue<bool>(0x5a8accb9u, ResetOnActivate);
		StickConfig = ddl.GetValue<RivetAssetId>(0x3bc8f276u, StickConfig);
	}

	[DDLRegistration(0xcb01aa04u, "Yaw Min")]
	public float YawMin { get; set; } = 0.00f;

	[DDLRegistration(0xcb01aa04u, "Yaw Max")]
	public float YawMax { get; set; } = 0.00f;

	[DDLRegistration(0xcb01aa04u, "Pitch Min")]
	public float PitchMin { get; set; } = 0.00f;

	[DDLRegistration(0xcb01aa04u, "Pitch Max")]
	public float PitchMax { get; set; } = 0.00f;

	[DDLRegistration(0xcb01aa04u, "Initial Pitch")]
	public float InitialPitch { get; set; } = 0.00f;

	[DDLRegistration(0xcb01aa04u, "Initial Yaw")]
	public float InitialYaw { get; set; } = 0.00f;

	[DDLRegistration(0xcb01aa04u, "Apply Settle")]
	public bool ZeroSettle { get; set; } = true;

	[DDLRegistration(0xcb01aa04u, "Lock Position")]
	public bool LockPosition { get; set; } = true;

	[DDLRegistration(0xcb01aa04u, "Reset On Activate")]
	public bool ResetOnActivate { get; set; } = true;

	[DDLRegistration(0xcb01aa04u, "Stick Config")]
	public RivetAssetId StickConfig { get; set; } = default;

	public new static FixedCameraPrius Create(DDLObject ddl) => new(ddl);
}

