// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xc1616e86u)]
public class FormationUserDiedEvent : EventBase, IDDLObjectType<FormationUserDiedEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xc1616e86u);

	public FormationUserDiedEvent(DDLObject ddl) : base(ddl) {
		DamagerHandle = ddl.GetValue<uint>(0x14c58735u, DamagerHandle);
		DamageType = ddl.GetEnum<DamageTypesGame>(0x840c154du, DamageTypesGameValues.Lookup);
	}

	[DDLRegistration(0xc1616e86u)]
	public uint DamagerHandle { get; set; } = 0x00000000;

	[DDLRegistration(0xc1616e86u)]
	public DamageTypesGame DamageType { get; set; } = DamageTypesGame.None;

	public new static FormationUserDiedEvent Create(DDLObject ddl) => new(ddl);
}

