// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x51ecd427u)]
public class FrozenL2Event : EventBase, IDDLObjectType<FrozenL2Event> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x51ecd427u);

	public FrozenL2Event(DDLObject ddl) : base(ddl) { }

	public new static FrozenL2Event Create(DDLObject ddl) => new(ddl);
}

