// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xafa8e623u)]
public class FurProperties : DDLObjectType, IDDLObjectType<FurProperties> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xafa8e623u);

	public FurProperties(DDLObject ddl) : base(ddl) {
		LayerCount = ddl.GetValue<uint>(0x163e9e1eu, LayerCount);
		LoDReduction = ddl.GetValue<float>(0x1461d827u, LoDReduction);
		Length = ddl.GetValue<float>(0x3f05d0d5u, Length);
		Density = ddl.GetValue<float>(0xc14209c2u, Density);
		OffsetScale = ddl.GetValue<float>(0x56b049abu, OffsetScale);
		GlossScale = ddl.GetValue<float>(0x0388a1a5u, GlossScale);
		SpecularScale = ddl.GetValue<float>(0xb5d495c8u, SpecularScale);
		TransmittanceScale = ddl.GetValue<float>(0xd1b350ccu, TransmittanceScale);
		LightWrap = ddl.GetValue<float>(0x9aaf5b2eu, LightWrap);
		Wetness = ddl.GetValue<float>(0xb9d9094du, Wetness);
		BaseMapPath = ddl.GetValue<RivetAssetId>(0x146722ebu, BaseMapPath);
		NormalMapPath = ddl.GetValue<RivetAssetId>(0x455116c5u, NormalMapPath);
		GlossMapPath = ddl.GetValue<RivetAssetId>(0xe0c69aadu, GlossMapPath);
		ControlMapPath = ddl.GetValue<RivetAssetId>(0xb6e2ce1du, ControlMapPath);
	}

	[DDLRegistration(0x163e9e1eu, "Layer Count")]
	public uint LayerCount { get; set; } = 0x00000020;

	[DDLRegistration(0x1461d827u, "LoD Reduction")]
	public float LoDReduction { get; set; } = 0.25f;

	[DDLRegistration(0x3f05d0d5u, "Length")]
	public float Length { get; set; } = 0.02f;

	[DDLRegistration(0xc14209c2u, "Density")]
	public float Density { get; set; } = 8.00f;

	[DDLRegistration(0x56b049abu, "Offset Scale")]
	public float OffsetScale { get; set; } = 2.00f;

	[DDLRegistration(0x0388a1a5u, "Gloss Scale")]
	public float GlossScale { get; set; } = 1.00f;

	[DDLRegistration(0xb5d495c8u, "Specular Scale")]
	public float SpecularScale { get; set; } = 1.00f;

	[DDLRegistration(0xd1b350ccu, "Transmittance Scale")]
	public float TransmittanceScale { get; set; } = 0.05f;

	[DDLRegistration(0x9aaf5b2eu, "Light Wrap")]
	public float LightWrap { get; set; } = 0.20f;

	[DDLRegistration(0xb9d9094du, "Wetness")]
	public float Wetness { get; set; } = 0.00f;

	[DDLRegistration(0x146722ebu, "Base Texture")]
	public RivetAssetId BaseMapPath { get; set; } = default;

	[DDLRegistration(0x455116c5u, "Normal Texture")]
	public RivetAssetId NormalMapPath { get; set; } = default;

	[DDLRegistration(0xe0c69aadu, "Gloss Texture")]
	public RivetAssetId GlossMapPath { get; set; } = default;

	[DDLRegistration(0xb6e2ce1du, "Control Texture")]
	public RivetAssetId ControlMapPath { get; set; } = default;

	public static FurProperties Create(DDLObject ddl) => new(ddl);
}

