// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLTypeRoot(0x655f398eu, "PortalZipItemConfig"), DDLTypeRoot(0xb1d8a72fu, "VersaGloveItemConfig"), DDLTypeRoot(0x65a99688u, "SwingshotItemConfig"), DDLTypeRoot(0x9fcdbf29u, "HoverbootItemConfig"), DDLTypeRoot(0xed822e17u, "MagBootItemConfig"), DDLTypeRoot(0x21ae0864u, "GrindBootItemConfig"), DDLTypeRoot(0xaa93a886u, "BoxBreakerItemConfig"), DDLTypeRoot(0xf7fe83f8u, "GlitchProjectorItemConfig"), DDLTypeRoot(0x23a27c05u, "MapOMaticItemConfig"), DDLTypeRoot(0xd0f418c7u, "HelipackItemConfig"), DDLRegistration(0x555b0b91u)]
public class GadgetItemConfig : GameItemConfig, IDDLObjectType<GadgetItemConfig> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x555b0b91u);

	public GadgetItemConfig(DDLObject ddl) : base(ddl) {
		GadgetType = ddl.GetEnum<HudGadgetEnum>(0x03ec9f66u, HudGadgetEnumValues.Lookup);
		HelpTextTag = ddl.GetString(0x4b5c5ca7) ?? HelpTextTag;
	}

	[DDLRegistration(0x03ec9f66u)]
	public HudGadgetEnum GadgetType { get; set; } = HudGadgetEnum.Omniboots;

	[DDLRegistration(0x4b5c5ca7u, description: "Loc tag for help text")]
	public string? HelpTextTag { get; set; } = default;

	public new static GadgetItemConfig Create(DDLObject ddl) => new(ddl);
}

