// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x37fad3c5u)]
public class GameplayDataReferenceDef : DDLObjectType, IDDLObjectType<GameplayDataReferenceDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x37fad3c5u);

	public GameplayDataReferenceDef(DDLObject ddl) : base(ddl) {
		AssetPath = ddl.GetValue<RivetAssetId>(0x0efa614bu, AssetPath);
		DataType = ddl.GetString(0xdf0abd28) ?? DataType;
	}

	[DDLRegistration(0x0efa614bu)]
	public RivetAssetId AssetPath { get; set; } = default;

	[DDLRegistration(0xdf0abd28u, "Type")]
	public string? DataType { get; set; } = default;

	public static GameplayDataReferenceDef Create(DDLObject ddl) => new(ddl);
}

