// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x61b80ffdu)]
public class GameManagerPrius : DDLObjectType, IDDLObjectType<GameManagerPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x61b80ffdu);

	public GameManagerPrius(DDLObject ddl) : base(ddl) { }

	public static GameManagerPrius Create(DDLObject ddl) => new(ddl);
}

