// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x1c9c7798u)]
public class GenericChunks : DDLObjectType, IDDLObjectType<GenericChunks> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x1c9c7798u);

	public GenericChunks(DDLObject ddl) : base(ddl) {
		Chunks = ddl.GetValues<RivetAssetId>(0xf9358ad2u);
		Min = ddl.GetValue<uint>(0x8b2e3419u, Min);
		Max = ddl.GetValue<uint>(0xb7230b40u, Max);
	}

	[DDLRegistration(0xf9358ad2u)]
	public List<RivetAssetId> Chunks { get; set; } = [];

	[DDLRegistration(0x8b2e3419u)]
	public uint Min { get; set; } = 0x00000000;

	[DDLRegistration(0xb7230b40u)]
	public uint Max { get; set; } = 0x00000000;

	public static GenericChunks Create(DDLObject ddl) => new(ddl);
}

