// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xef1936dcu)]
public class GetUIActorActionPrius : DDLObjectType, IDDLObjectType<GetUIActorActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xef1936dcu);

	public GetUIActorActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
	}

	[DDLRegistration(0xef1936dcu)]
	public x10228b34 ActionType { get; set; } = x10228b34.UI;

	public static GetUIActorActionPrius Create(DDLObject ddl) => new(ddl);
}

