// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x8d3330d3u)]
public class GiveAmmoActionPrius : DDLObjectType, IDDLObjectType<GiveAmmoActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x8d3330d3u);

	public GiveAmmoActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		GiveFullAmmo = ddl.GetValue<bool>(0x3e048d62u, GiveFullAmmo);
	}

	[DDLRegistration(0x8d3330d3u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Weapon;

	[DDLRegistration(0x8d3330d3u)]
	public bool GiveFullAmmo { get; set; } = true;

	public static GiveAmmoActionPrius Create(DDLObject ddl) => new(ddl);
}

