// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x21ae0864u)]
public class GrindBootItemConfig : GadgetItemConfig, IDDLObjectType<GrindBootItemConfig> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x21ae0864u);

	public GrindBootItemConfig(DDLObject ddl) : base(ddl) { }

	public new static GrindBootItemConfig Create(DDLObject ddl) => new(ddl);
}

