// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xc614f563u)]
public class GroovitronDanceTrophyConfig : ConfigBase, IDDLObjectType<GroovitronDanceTrophyConfig> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xc614f563u);

	public GroovitronDanceTrophyConfig(DDLObject ddl) : base(ddl) {
		DancerList = ddl.GetObjects<UniqueDancerData>(0xca02462fu);
	}

	[DDLRegistration(0xca02462fu)]
	public List<UniqueDancerData?> DancerList { get; set; } = [];

	public new static GroovitronDanceTrophyConfig Create(DDLObject ddl) => new(ddl);
}

