// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x491f7533u)]
public class HandBeamStopEvent : EventBase, IDDLObjectType<HandBeamStopEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x491f7533u);

	public HandBeamStopEvent(DDLObject ddl) : base(ddl) {
		Is_Right_Hand = ddl.GetValue<bool>(0xa24be18du, Is_Right_Hand);
	}

	[DDLRegistration(0xa24be18du)]
	public bool Is_Right_Hand { get; set; } = true;

	public new static HandBeamStopEvent Create(DDLObject ddl) => new(ddl);
}

