// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x75f0d64fu)]
public class HeroRunSpeedSettings : DDLObjectType, IDDLObjectType<HeroRunSpeedSettings> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x75f0d64fu);

	public HeroRunSpeedSettings(DDLObject ddl) : base(ddl) {
		RunSpeedMultiplier = ddl.GetValue<float>(0xbcd4ae64u, RunSpeedMultiplier);
		RunAnimSpeedMultiplier = ddl.GetValue<float>(0xaddd1644u, RunAnimSpeedMultiplier);
		DoJumpScaling = ddl.GetValue<bool>(0xa72bc597u, DoJumpScaling);
	}

	[DDLRegistration(0x75f0d64fu)]
	public float RunSpeedMultiplier { get; set; } = 1.20f;

	[DDLRegistration(0x75f0d64fu)]
	public float RunAnimSpeedMultiplier { get; set; } = 1.15f;

	[DDLRegistration(0x75f0d64fu)]
	public bool DoJumpScaling { get; set; } = true;

	public static HeroRunSpeedSettings Create(DDLObject ddl) => new(ddl);
}

