// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x8e38d7f0u)]
public class HeroPortalTransitionEvent : EventBase, IDDLObjectType<HeroPortalTransitionEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x8e38d7f0u);

	public HeroPortalTransitionEvent(DDLObject ddl) : base(ddl) {
		SourceActor = ddl.GetValue<uint>(0x54c7dd3eu, SourceActor);
		DestinationActor = ddl.GetValue<uint>(0x3a387b17u, DestinationActor);
		Destination = ddl.GetObject<DDLTransform>(0xb31a6f71u);
	}

	[DDLRegistration(0x8e38d7f0u)]
	public uint SourceActor { get; set; } = 0x00000000;

	[DDLRegistration(0x8e38d7f0u)]
	public uint DestinationActor { get; set; } = 0x00000000;

	[DDLRegistration(0x8e38d7f0u)]
	public DDLTransform? Destination { get; set; } = default;

	public new static HeroPortalTransitionEvent Create(DDLObject ddl) => new(ddl);
}

