// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x1c70e4ddu)]
public class HitReactGamePrius : HitReactPrius, IDDLObjectType<HitReactGamePrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x1c70e4ddu);

	public HitReactGamePrius(DDLObject ddl) : base(ddl) {
		Buckets = ddl.GetObjects<BotReactionBucket>(0x25b695d8u);
		KnockbackData = ddl.GetObject<KnockbackData>(0xcc96e476u);
		KnockdownData = ddl.GetObject<KnockdownData>(0x0a615951u);
		DeathData = ddl.GetObject<DeathData>(0xc5c5429eu);
		HitShaderData = ddl.GetObject<BotHitShaderData>(0xbe73a2efu);
		TestCollision = ddl.GetValue<bool>(0x5de60dbeu, TestCollision);
		CollisionTestHeight = ddl.GetValue<float>(0x4015bc6eu, CollisionTestHeight);
		CollisionTestRadius = ddl.GetValue<float>(0x8e24373bu, CollisionTestRadius);
		ApplyCooldownToMeleeDamage = ddl.GetValue<bool>(0x8c884b8du, ApplyCooldownToMeleeDamage);
	}

	[DDLRegistration(0x1c70e4ddu)]
	public List<BotReactionBucket?> Buckets { get; set; } = [];

	[DDLRegistration(0x1c70e4ddu, "Knockback Data")]
	public KnockbackData? KnockbackData { get; set; } = default;

	[DDLRegistration(0x1c70e4ddu, "Knockdown Data")]
	public KnockdownData? KnockdownData { get; set; } = default;

	[DDLRegistration(0x1c70e4ddu, "Death Data")]
	public DeathData? DeathData { get; set; } = default;

	[DDLRegistration(0x1c70e4ddu, "Hit Shader Data")]
	public BotHitShaderData? HitShaderData { get; set; } = default;

	[DDLRegistration(0x1c70e4ddu)]
	public bool TestCollision { get; set; } = false;

	[DDLRegistration(0x1c70e4ddu)]
	public float CollisionTestHeight { get; set; } = 1.50f;

	[DDLRegistration(0x1c70e4ddu)]
	public float CollisionTestRadius { get; set; } = 1.00f;

	[DDLRegistration(0x1c70e4ddu, "Apply Cooldown to Melee Damage")]
	public bool ApplyCooldownToMeleeDamage { get; set; } = false;

	public new static HitReactGamePrius Create(DDLObject ddl) => new(ddl);
}

