// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x527f2755u)]
public class HoldAndReleaseTargetingPrius : WeaponTargetingStyleBasePrius, IDDLObjectType<HoldAndReleaseTargetingPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x527f2755u);

	public HoldAndReleaseTargetingPrius(DDLObject ddl) : base(ddl) { }

	public new static HoldAndReleaseTargetingPrius Create(DDLObject ddl) => new(ddl);
}

