// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x50503620u)]
public class HoverMoverManagerPrius : BotMoverManagerPrius, IDDLObjectType<HoverMoverManagerPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x50503620u);

	public HoverMoverManagerPrius(DDLObject ddl) : base(ddl) {
		CeilingCheckRadius = ddl.GetValue<float>(0xe55d0887u, CeilingCheckRadius);
		CeilingCheckTop = ddl.GetValue<float>(0x5b9c385au, CeilingCheckTop);
		CeilingCheckBottom = ddl.GetValue<float>(0x577e1479u, CeilingCheckBottom);
	}

	[DDLRegistration(0xe55d0887u, "Ceiling Check Radius", "Ceiling check radius")]
	public float CeilingCheckRadius { get; set; } = 0.15f;

	[DDLRegistration(0x5b9c385au, "Ceiling Check Top", "Distance above our actor position that the ceiling check's top is.")]
	public float CeilingCheckTop { get; set; } = 5.00f;

	[DDLRegistration(0x577e1479u, "Ceiling Check Bottom", "Distance above our actor position that the ceiling check's bottom is.")]
	public float CeilingCheckBottom { get; set; } = 1.00f;

	public new static HoverMoverManagerPrius Create(DDLObject ddl) => new(ddl);
}

