// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xb8684678u)]
public class HUDMessageTutorialDisplayEvent : EventBase, IDDLObjectType<HUDMessageTutorialDisplayEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xb8684678u);

	public HUDMessageTutorialDisplayEvent(DDLObject ddl) : base(ddl) { }

	public new static HUDMessageTutorialDisplayEvent Create(DDLObject ddl) => new(ddl);
}

