// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x828aa0cdu)]
public class IconMapData : DDLObjectType, IDDLObjectType<IconMapData> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x828aa0cdu);

	public IconMapData(DDLObject ddl) : base(ddl) {
		Icon = ddl.GetValue<RivetAssetId>(0x5504e96bu, Icon);
		MarkupText = ddl.GetString(0x28b909c2) ?? MarkupText;
		Width = ddl.GetValue<int>(0x954989eeu, Width);
		Height = ddl.GetValue<int>(0xcb35ab68u, Height);
		MinHeight = ddl.GetValue<int>(0x9ed620e3u, MinHeight);
		MaxHeight = ddl.GetValue<int>(0x493d92a2u, MaxHeight);
		Vspace = ddl.GetValue<int>(0xbd91373fu, Vspace);
	}

	[DDLRegistration(0x828aa0cdu)]
	public RivetAssetId Icon { get; set; } = "";

	[DDLRegistration(0x828aa0cdu)]
	public string? MarkupText { get; set; } = "";

	[DDLRegistration(0x828aa0cdu)]
	public int Width { get; set; } = 64;

	[DDLRegistration(0x828aa0cdu)]
	public int Height { get; set; } = 64;

	[DDLRegistration(0x828aa0cdu, description: "If 0 or negative, no minimum height enforced.")]
	public int MinHeight { get; set; } = -1;

	[DDLRegistration(0x828aa0cdu, description: "If 0 or negative, no maximum height enforced.")]
	public int MaxHeight { get; set; } = -1;

	[DDLRegistration(0x828aa0cdu, description: "Pixels offset relative to baseline. Positive for above, negative for below.")]
	public int Vspace { get; set; } = -16;

	public static IconMapData Create(DDLObject ddl) => new(ddl);
}

