// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x7ca388b5u)]
public class InteractShaderEffectPrius : DDLObjectType, IDDLObjectType<InteractShaderEffectPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x7ca388b5u);

	public InteractShaderEffectPrius(DDLObject ddl) : base(ddl) {
		EffectType = ddl.GetEnum<x08f7f2e3>(0x609bd7dbu, x08f7f2e3Values.Lookup);
		ShaderAttribute = ddl.GetString(0xc911b025) ?? ShaderAttribute;
		MinValue = ddl.GetValue<float>(0xe2893042u, MinValue);
		MaxValue = ddl.GetValue<float>(0x04e99fa3u, MaxValue);
		DeltaSpeed = ddl.GetValue<float>(0xa24aed72u, DeltaSpeed);
	}

	[DDLRegistration(0x7ca388b5u, "Effect Type")]
	public x08f7f2e3 EffectType { get; set; } = x08f7f2e3.UseToggle;

	[DDLRegistration(0x7ca388b5u, "Shader Attribute")]
	public string? ShaderAttribute { get; set; } = "";

	[DDLRegistration(0x7ca388b5u, "Min Value")]
	public float MinValue { get; set; } = 0.00f;

	[DDLRegistration(0x7ca388b5u, "Max Value")]
	public float MaxValue { get; set; } = 1.00f;

	[DDLRegistration(0x7ca388b5u, "Delta Speed")]
	public float DeltaSpeed { get; set; } = 0.00f;

	public static InteractShaderEffectPrius Create(DDLObject ddl) => new(ddl);
}

