// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x40d37971u)]
public class InvalidateEnvProbesActionPrius : DDLObjectType, IDDLObjectType<InvalidateEnvProbesActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x40d37971u);

	public InvalidateEnvProbesActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		EnvProbeZone = ddl.GetValue<RivetAssetId>(0x25f5a0c8u, EnvProbeZone);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Render;

	[DDLRegistration(0x25f5a0c8u)]
	public RivetAssetId EnvProbeZone { get; set; } = default;

	public static InvalidateEnvProbesActionPrius Create(DDLObject ddl) => new(ddl);
}

