// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x588cdd4bu)]
public class LevelListGameDataClipboard : DDLObjectType, IDDLObjectType<LevelListGameDataClipboard> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x588cdd4bu);

	public LevelListGameDataClipboard(DDLObject ddl) : base(ddl) {
		Compatability = ddl.GetString(0xcc24cf63) ?? Compatability;
		Data = ddl.GetObject<DDLStructInst>(0x3d519cedu);
	}

	[DDLRegistration(0xcc24cf63u)]
	public string? Compatability { get; set; } = default;

	[DDLRegistration(0x3d519cedu)]
	public DDLStructInst? Data { get; set; } = default;

	public static LevelListGameDataClipboard Create(DDLObject ddl) => new(ddl);
}

