// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x7ee1281cu)]
public class LightningRodSpikeStateEvent : EventBase, IDDLObjectType<LightningRodSpikeStateEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x7ee1281cu);

	public LightningRodSpikeStateEvent(DDLObject ddl) : base(ddl) {
		PercentFull = ddl.GetValue<float>(0x29adde1eu, PercentFull);
	}

	[DDLRegistration(0x7ee1281cu)]
	public float PercentFull { get; set; } = 0.00f;

	public new static LightningRodSpikeStateEvent Create(DDLObject ddl) => new(ddl);
}

