// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x8f8315c6u)]
public class MagShieldShatteringEvent : EventBase, IDDLObjectType<MagShieldShatteringEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x8f8315c6u);

	public MagShieldShatteringEvent(DDLObject ddl) : base(ddl) {
		Red = ddl.GetValue<float>(0xd0347646u, Red);
		Green = ddl.GetValue<float>(0xc9c922e0u, Green);
		Blue = ddl.GetValue<float>(0xaea60a04u, Blue);
	}

	[DDLRegistration(0x8f8315c6u)]
	public float Red { get; set; } = 0.00f;

	[DDLRegistration(0x8f8315c6u)]
	public float Green { get; set; } = 0.00f;

	[DDLRegistration(0x8f8315c6u)]
	public float Blue { get; set; } = 0.00f;

	public new static MagShieldShatteringEvent Create(DDLObject ddl) => new(ddl);
}

