// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xa9a02fcdu)]
public class ManglerSetOverloadLevelEvent : EventBase, IDDLObjectType<ManglerSetOverloadLevelEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xa9a02fcdu);

	public ManglerSetOverloadLevelEvent(DDLObject ddl) : base(ddl) {
		OverloadLevel = ddl.GetValue<uint>(0x91f73e07u, OverloadLevel);
	}

	[DDLRegistration(0x91f73e07u)]
	public uint OverloadLevel { get; set; } = 0x00000000;

	public new static ManglerSetOverloadLevelEvent Create(DDLObject ddl) => new(ddl);
}

