// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xfc82b59fu)]
public class MapRangeElement : DDLObjectType, IDDLObjectType<MapRangeElement> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xfc82b59fu);

	public MapRangeElement(DDLObject ddl) : base(ddl) {
		X = ddl.GetValue<float>(0x5e33418du, X);
		Y = ddl.GetValue<float>(0x2934711bu, Y);
	}

	[DDLRegistration(0x5e33418du, description: "Input.")]
	public float X { get; set; } = 0.00f;

	[DDLRegistration(0x2934711bu, description: "Output.")]
	public float Y { get; set; } = 0.00f;

	public static MapRangeElement Create(DDLObject ddl) => new(ddl);
}

