// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x5384d94bu)]
public class MaterialGraphEngineItem : DDLObjectType, IDDLObjectType<MaterialGraphEngineItem> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x5384d94bu);

	public MaterialGraphEngineItem(DDLObject ddl) : base(ddl) {
		AssetPath = ddl.GetString(0x0efa614b) ?? AssetPath;
		Force = ddl.GetValue<bool>(0x8e3b4fe9u, Force);
		ForceCounter = ddl.GetValue<int>(0x20b26178u, ForceCounter);
		MaterialNodeLibraryList = ddl.GetObject<MaterialNodeLibraryList>(0x755953beu);
		MaterialGraphDef = ddl.GetObject<MaterialGraphDef>(0xb67789c2u);
	}

	[DDLRegistration(0x0efa614bu)]
	public string? AssetPath { get; set; } = default;

	[DDLRegistration(0x8e3b4fe9u)]
	public bool Force { get; set; } = false;

	[DDLRegistration(0x20b26178u)]
	public int ForceCounter { get; set; } = 0;

	[DDLRegistration(0x755953beu)]
	public MaterialNodeLibraryList? MaterialNodeLibraryList { get; set; } = default;

	[DDLRegistration(0xb67789c2u)]
	public MaterialGraphDef? MaterialGraphDef { get; set; } = default;

	public static MaterialGraphEngineItem Create(DDLObject ddl) => new(ddl);
}

