// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x30c0ef01u)]
public class MaterialNodeInputVisibilityCondition : DDLObjectType, IDDLObjectType<MaterialNodeInputVisibilityCondition> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x30c0ef01u);

	public MaterialNodeInputVisibilityCondition(DDLObject ddl) : base(ddl) {
		InternalName = ddl.GetString(0x93971d83) ?? InternalName;
		Values = ddl.GetStrings(0x04df0281u);
	}

	[DDLRegistration(0x93971d83u)]
	public string? InternalName { get; set; } = default;

	[DDLRegistration(0x04df0281u)]
	public List<string?> Values { get; set; } = [];

	public static MaterialNodeInputVisibilityCondition Create(DDLObject ddl) => new(ddl);
}

