// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x181846f2u)]
public class MaterialGraphNode : DDLObjectType, IDDLObjectType<MaterialGraphNode> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x181846f2u);

	public MaterialGraphNode(DDLObject ddl) : base(ddl) {
		XPos = ddl.GetValue<int>(0xf88aee81u, XPos);
		YPos = ddl.GetValue<int>(0x403689e4u, YPos);
		IdLow = ddl.GetValue<uint>(0xaa93a9e7u, IdLow);
		IdHigh = ddl.GetValue<uint>(0xbc80f4acu, IdHigh);
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		VariableName = ddl.GetString(0x11d33588) ?? VariableName;
		PortUIs = ddl.GetObjects<MaterialNodePortUI>(0x6cc36d17u);
		UserInputs = ddl.GetObjects<MaterialNodeUserInput>(0xb701ec85u);
		ConnectedInputs = ddl.GetObjects<MaterialNodeConnectedInputPort>(0x8ca57bf5u);
		ConnectedOutputs = ddl.GetObjects<MaterialNodeConnectedOutputPort>(0x824bee0eu);
		PrependNodeName = ddl.GetValue<bool>(0x5dda1f00u, PrependNodeName);
		IsSubGraph = ddl.GetValue<bool>(0xf2039ed8u, IsSubGraph);
		AssetPath = ddl.GetValue<RivetAssetId>(0x0efa614bu, AssetPath);
		SortOrder = ddl.GetValue<int>(0xbd9f03f1u, SortOrder);
	}

	[DDLRegistration(0x181846f2u)]
	public int XPos { get; set; } = 0;

	[DDLRegistration(0x181846f2u)]
	public int YPos { get; set; } = 0;

	[DDLRegistration(0x181846f2u)]
	public uint IdLow { get; set; } = 0x00000000;

	[DDLRegistration(0x181846f2u)]
	public uint IdHigh { get; set; } = 0x00000000;

	[DDLRegistration(0x181846f2u)]
	public string? Name { get; set; } = default;

	[DDLRegistration(0x181846f2u)]
	public string? VariableName { get; set; } = default;

	[DDLRegistration(0x181846f2u)]
	public List<MaterialNodePortUI?> PortUIs { get; set; } = [];

	[DDLRegistration(0x181846f2u)]
	public List<MaterialNodeUserInput?> UserInputs { get; set; } = [];

	[DDLRegistration(0x181846f2u)]
	public List<MaterialNodeConnectedInputPort?> ConnectedInputs { get; set; } = [];

	[DDLRegistration(0x181846f2u)]
	public List<MaterialNodeConnectedOutputPort?> ConnectedOutputs { get; set; } = [];

	[DDLRegistration(0x181846f2u)]
	public bool PrependNodeName { get; set; } = true;

	[DDLRegistration(0x181846f2u)]
	public bool IsSubGraph { get; set; } = false;

	[DDLRegistration(0x181846f2u)]
	public RivetAssetId AssetPath { get; set; } = default;

	[DDLRegistration(0x181846f2u)]
	public int SortOrder { get; set; } = 0;

	public static MaterialGraphNode Create(DDLObject ddl) => new(ddl);
}

