// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x6f4cd3aau)]
public class MeleeActiveStartEvent : EventBase, IDDLObjectType<MeleeActiveStartEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x6f4cd3aau);

	public MeleeActiveStartEvent(DDLObject ddl) : base(ddl) { }

	public new static MeleeActiveStartEvent Create(DDLObject ddl) => new(ddl);
}

