// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x0c03d7dfu)]
public class MeleeKillEvent : EventBase, IDDLObjectType<MeleeKillEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x0c03d7dfu);

	public MeleeKillEvent(DDLObject ddl) : base(ddl) { }

	public new static MeleeKillEvent Create(DDLObject ddl) => new(ddl);
}

