// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x3e870b52u)]
public class MissionObjectiveCompleteEvent : EventBase, IDDLObjectType<MissionObjectiveCompleteEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x3e870b52u);

	public MissionObjectiveCompleteEvent(DDLObject ddl) : base(ddl) {
		MissionName = ddl.GetString(0xa5c30e60) ?? MissionName;
		ObjectiveName = ddl.GetString(0x58746b9b) ?? ObjectiveName;
		ObjectiveInstanceID = ddl.GetValue<uint>(0x5863bde4u, ObjectiveInstanceID);
		IsSkipping = ddl.GetValue<bool>(0x5cc05663u, IsSkipping);
	}

	[DDLRegistration(0x3e870b52u)]
	public string? MissionName { get; set; } = default;

	[DDLRegistration(0x3e870b52u)]
	public string? ObjectiveName { get; set; } = default;

	[DDLRegistration(0x3e870b52u)]
	public uint ObjectiveInstanceID { get; set; } = 0x00000000;

	[DDLRegistration(0x3e870b52u, description: "True if the objective is being set to 'complete' as a prerequisite for loading straight into a mission from the frontend.")]
	public bool IsSkipping { get; set; } = false;

	public new static MissionObjectiveCompleteEvent Create(DDLObject ddl) => new(ddl);
}

