// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x06f6b3c5u)]
public class MissionNodeBuiltTableEntry : DDLObjectType, IDDLObjectType<MissionNodeBuiltTableEntry> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x06f6b3c5u);

	public MissionNodeBuiltTableEntry(DDLObject ddl) : base(ddl) {
		MissionData = ddl.GetObject<MissionNodeBuiltShared>(0x56138305u);
	}

	[DDLRegistration(0x56138305u)]
	public MissionNodeBuiltShared? MissionData { get; set; } = default;

	public static MissionNodeBuiltTableEntry Create(DDLObject ddl) => new(ddl);
}

