// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x5142d0cdu)]
public class ModelVariantDef : DDLObjectType, IDDLObjectType<ModelVariantDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x5142d0cdu);

	public ModelVariantDef(DDLObject ddl) : base(ddl) {
		EditorModel = ddl.GetValue<RivetAssetId>(0x2c6cecd4u, EditorModel);
	}

	[DDLRegistration(0x5142d0cdu, description: "The model which this variant modifies.")]
	public RivetAssetId EditorModel { get; set; } = default;

	[DDLRegistration(0x5142d0cdu, description: "all the variants contained in this file.")]
	public Dictionary<RivetAssetId, ModelVariantSingle?> Variants { get; set; } = [];

	public static ModelVariantDef Create(DDLObject ddl) => new(ddl);
}

