// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x9628608eu)]
public class MrFunGuyMaxSpawnedFailedToShootEvent : EventBase, IDDLObjectType<MrFunGuyMaxSpawnedFailedToShootEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x9628608eu);

	public MrFunGuyMaxSpawnedFailedToShootEvent(DDLObject ddl) : base(ddl) { }

	public new static MrFunGuyMaxSpawnedFailedToShootEvent Create(DDLObject ddl) => new(ddl);
}

