// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xaeeed169u)]
public class NodeGraphDebugDataContainer : DDLObjectType, IDDLObjectType<NodeGraphDebugDataContainer> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xaeeed169u);

	public NodeGraphDebugDataContainer(DDLObject ddl) : base(ddl) {
		GraphData = ddl.GetObject<NodeGraphDebugDataBase>(0x11a7047fu);
	}

	[DDLRegistration(0xaeeed169u)]
	public NodeGraphDebugDataBase? GraphData { get; set; } = default;

	[DDLRegistration(0xaeeed169u)]
	public Dictionary<RivetAssetId, NodeGraphNodeDebugData?> NodeData { get; set; } = [];

	public static NodeGraphDebugDataContainer Create(DDLObject ddl) => new(ddl);
}

