// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x4f4b50fbu)]
public class NoGrindTransferVolumePrius : DDLObjectType, IDDLObjectType<NoGrindTransferVolumePrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x4f4b50fbu);

	public NoGrindTransferVolumePrius(DDLObject ddl) : base(ddl) { }

	public static NoGrindTransferVolumePrius Create(DDLObject ddl) => new(ddl);
}

