// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x98e5fff2u)]
public class ObjectiveNodeBuiltTableEntry : DDLObjectType, IDDLObjectType<ObjectiveNodeBuiltTableEntry> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x98e5fff2u);

	public ObjectiveNodeBuiltTableEntry(DDLObject ddl) : base(ddl) {
		ObjectiveData = ddl.GetObject<ObjectiveNodeBuiltShared>(0xaba4e6feu);
	}

	[DDLRegistration(0x98e5fff2u)]
	public ObjectiveNodeBuiltShared? ObjectiveData { get; set; } = default;

	public static ObjectiveNodeBuiltTableEntry Create(DDLObject ddl) => new(ddl);
}

