// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x837c07bau)]
public class OldPyrocitorShotMotionPrius : BeamShotMotionPrius, IDDLObjectType<OldPyrocitorShotMotionPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x837c07bau);

	public OldPyrocitorShotMotionPrius(DDLObject ddl) : base(ddl) {
		IgnoreHeroes = ddl.GetValue<bool>(0xeea28f86u, IgnoreHeroes);
	}

	[DDLRegistration(0xeea28f86u, "Ignore heroes?", "Whether to ignore colliding with heroes.")]
	public bool IgnoreHeroes { get; set; } = true;

	public new static OldPyrocitorShotMotionPrius Create(DDLObject ddl) => new(ddl);
}

