// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x98a9f92eu)]
public class OnActorCombatStateChangedActionPrius : DDLObjectType, IDDLObjectType<OnActorCombatStateChangedActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x98a9f92eu);

	public OnActorCombatStateChangedActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		InitiallyListening = ddl.GetValue<bool>(0x51d42fd7u, InitiallyListening);
	}

	[DDLRegistration(0x98a9f92eu)]
	public x10228b34 ActionType { get; set; } = x10228b34.Events;

	[DDLRegistration(0x98a9f92eu)]
	public bool InitiallyListening { get; set; } = true;

	public static OnActorCombatStateChangedActionPrius Create(DDLObject ddl) => new(ddl);
}

