// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xe9cbbbfeu)]
public class OnCinematicCameraActivateEvent : EventBase, IDDLObjectType<OnCinematicCameraActivateEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xe9cbbbfeu);

	public OnCinematicCameraActivateEvent(DDLObject ddl) : base(ddl) {
		CameraHandle = ddl.GetValue<uint>(0xa07a1734u, CameraHandle);
	}

	[DDLRegistration(0xe9cbbbfeu)]
	public uint CameraHandle { get; set; } = 0x00000000;

	public new static OnCinematicCameraActivateEvent Create(DDLObject ddl) => new(ddl);
}

