// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xb93e980fu)]
public class OnDeadActionPrius : DDLObjectType, IDDLObjectType<OnDeadActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xb93e980fu);

	public OnDeadActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		SignalMax = ddl.GetValue<int>(0x9149785eu, SignalMax);
		InitListening = ddl.GetValue<bool>(0xf387b27au, InitListening);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Events;

	[DDLRegistration(0x9149785eu, "Max Times to Fire", "The number of times connected outputs can be signaled (-1 = infinite).")]
	public int SignalMax { get; set; } = 1;

	[DDLRegistration(0xf387b27au, "Start listening on load?", "Whether to start in our listening state when the script is loaded.")]
	public bool InitListening { get; set; } = true;

	public static OnDeadActionPrius Create(DDLObject ddl) => new(ddl);
}

