// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xaa71fc2du)]
public class OnEnterTurretEvent : EventBase, IDDLObjectType<OnEnterTurretEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xaa71fc2du);

	public OnEnterTurretEvent(DDLObject ddl) : base(ddl) {
		UserHandle = ddl.GetValue<uint>(0x25e06c12u, UserHandle);
	}

	[DDLRegistration(0xaa71fc2du)]
	public uint UserHandle { get; set; } = 0x00000000;

	public new static OnEnterTurretEvent Create(DDLObject ddl) => new(ddl);
}

