// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xcbac7b5cu)]
public class OutputPlugEventInitialization : OutputPlugBaseDef, IDDLObjectType<OutputPlugEventInitialization> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xcbac7b5cu);

	public OutputPlugEventInitialization(DDLObject ddl) : base(ddl) {
		Value = ddl.GetObject<EventInitializationPlug>(0x042494f5u);
	}

	[DDLRegistration(0x042494f5u)]
	public EventInitializationPlug? Value { get; set; } = default;

	public new static OutputPlugEventInitialization Create(DDLObject ddl) => new(ddl);
}

