// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x2c033167u)]
public class OverrideHoverbootConfigActionPrius : DDLObjectType, IDDLObjectType<OverrideHoverbootConfigActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x2c033167u);

	public OverrideHoverbootConfigActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		OverrideConfig = ddl.GetValue<RivetAssetId>(0xb8b3c47fu, OverrideConfig);
	}

	[DDLRegistration(0x2c033167u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Hero;

	[DDLRegistration(0x2c033167u, description: "Override hoverboot config to set on Hero.")]
	public RivetAssetId OverrideConfig { get; set; } = default;

	public static OverrideHoverbootConfigActionPrius Create(DDLObject ddl) => new(ddl);
}

