// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x713263ffu)]
public class PathHazardPrius : DDLObjectType, IDDLObjectType<PathHazardPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x713263ffu);

	public PathHazardPrius(DDLObject ddl) : base(ddl) {
		TrackingDistance = ddl.GetValue<float>(0xaf666352u, TrackingDistance);
		TrackingSpeed = ddl.GetValue<float>(0xfe94d1b9u, TrackingSpeed);
		TrackingAccel = ddl.GetValue<float>(0xac4e19aau, TrackingAccel);
		TrackingDecel = ddl.GetValue<float>(0x41c5c906u, TrackingDecel);
		TelegraphTime = ddl.GetValue<float>(0x2085862du, TelegraphTime);
		RetreatTime = ddl.GetValue<float>(0xcc77d1d0u, RetreatTime);
		MovementCurve = ddl.GetValue<RivetAssetId>(0x2c2a8f27u, MovementCurve);
		CurveYPosOffset = ddl.GetValue<float>(0xd5970c69u, CurveYPosOffset);
		IdleSpeed = ddl.GetValue<float>(0xdc7f8c8bu, IdleSpeed);
		IdleAccel = ddl.GetValue<float>(0x8ea54498u, IdleAccel);
		IdleDecel = ddl.GetValue<float>(0x632e9434u, IdleDecel);
	}

	[DDLRegistration(0x713263ffu)]
	public float TrackingDistance { get; set; } = 6.00f;

	[DDLRegistration(0x713263ffu)]
	public float TrackingSpeed { get; set; } = 3.00f;

	[DDLRegistration(0x713263ffu, description: "Accel when tracking the player.")]
	public float TrackingAccel { get; set; } = 1.00f;

	[DDLRegistration(0x713263ffu, description: "Decel when tracking the player.")]
	public float TrackingDecel { get; set; } = 2.00f;

	[DDLRegistration(0x713263ffu)]
	public float TelegraphTime { get; set; } = 2.00f;

	[DDLRegistration(0x713263ffu)]
	public float RetreatTime { get; set; } = 10.00f;

	[DDLRegistration(0x713263ffu, description: "Path we follow.")]
	public RivetAssetId MovementCurve { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0x713263ffu, description: "Y pos offset on the path.")]
	public float CurveYPosOffset { get; set; } = 0.00f;

	[DDLRegistration(0x713263ffu, description: "Speed when idling on the path.")]
	public float IdleSpeed { get; set; } = 2.00f;

	[DDLRegistration(0x713263ffu, description: "Accel when idle on the path.")]
	public float IdleAccel { get; set; } = 2.00f;

	[DDLRegistration(0x713263ffu, description: "Decel when idle on the path.")]
	public float IdleDecel { get; set; } = 2.00f;

	public static PathHazardPrius Create(DDLObject ddl) => new(ddl);
}

