// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x691e88d4u)]
public class PauseCollectiblesTabEvent : EventBase, IDDLObjectType<PauseCollectiblesTabEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x691e88d4u);

	public PauseCollectiblesTabEvent(DDLObject ddl) : base(ddl) { }

	public new static PauseCollectiblesTabEvent Create(DDLObject ddl) => new(ddl);
}

