// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x0823014au)]
public class PhysicsPropertyNodeDef : DDLObjectType, IDDLObjectType<PhysicsPropertyNodeDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x0823014au);

	public PhysicsPropertyNodeDef(DDLObject ddl) : base(ddl) {
		Id = ddl.GetValue<RivetAssetId>(0x8a514a8du, Id);
		Type = ddl.GetEnum<x577f103e>(0xbc4e9799u, x577f103eValues.Lookup);
		Collapsed = ddl.GetValue<bool>(0xf07e7fafu, Collapsed);
		Disabled = ddl.GetValue<bool>(0x7effd393u, Disabled);
		X = ddl.GetValue<float>(0x5e33418du, X);
		Y = ddl.GetValue<float>(0x2934711bu, Y);
		PhysicsComponentPrius = ddl.GetObject<PhysicsComponentPrius>(0xcc30dca6u);
		Output = ddl.GetObject<BlockModifierOutPutSignal>(0xf2a65af9u);
	}

	[DDLRegistration(0x8a514a8du)]
	public RivetAssetId Id { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0xbc4e9799u)]
	public x577f103e Type { get; set; } = x577f103e.Invalid;

	[DDLRegistration(0xf07e7fafu)]
	public bool Collapsed { get; set; } = false;

	[DDLRegistration(0x7effd393u)]
	public bool Disabled { get; set; } = false;

	[DDLRegistration(0x5e33418du)]
	public float X { get; set; } = 0.00f;

	[DDLRegistration(0x2934711bu)]
	public float Y { get; set; } = 0.00f;

	[DDLRegistration(0xcc30dca6u)]
	public PhysicsComponentPrius? PhysicsComponentPrius { get; set; } = default;

	[DDLRegistration(0xf2a65af9u)]
	public BlockModifierOutPutSignal? Output { get; set; } = default;

	public static PhysicsPropertyNodeDef Create(DDLObject ddl) => new(ddl);
}

