// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x490b12e5u)]
public class PickupAboutToResetEvent : EventBase, IDDLObjectType<PickupAboutToResetEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x490b12e5u);

	public PickupAboutToResetEvent(DDLObject ddl) : base(ddl) { }

	public new static PickupAboutToResetEvent Create(DDLObject ddl) => new(ddl);
}

