// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x27d25163u)]
public class PilotSpawnData : ActorSpawnData, IDDLObjectType<PilotSpawnData> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x27d25163u);

	public PilotSpawnData(DDLObject ddl) : base(ddl) {
		VehicleHandle = ddl.GetValue<uint>(0x41c2ab0au, VehicleHandle);
		AssetId = ddl.GetValue<RivetAssetId>(0xb6e788d7u, AssetId);
		AttachLocator = ddl.GetValue<uint>(0xfa8dcd9au, AttachLocator);
	}

	[DDLRegistration(0x41c2ab0au)]
	public uint VehicleHandle { get; set; } = 0x00000000;

	[DDLRegistration(0xb6e788d7u, description: "AssetId for the asset we're spawning")]
	public RivetAssetId AssetId { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0xfa8dcd9au, description: "Locator to attach Pilot on Vehicle")]
	public uint AttachLocator { get; set; } = 0x00000000;

	public new static PilotSpawnData Create(DDLObject ddl) => new(ddl);
}

