// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xeae9919cu)]
public class PlanetMenuViewData : UIViewBaseData, IDDLObjectType<PlanetMenuViewData> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xeae9919cu);

	public PlanetMenuViewData(DDLObject ddl) : base(ddl) {
		BackgroundActor = ddl.GetValue<RivetAssetId>(0x22e8c45au, BackgroundActor);
	}

	[DDLRegistration(0xeae9919cu, "Background Actor")]
	public RivetAssetId BackgroundActor { get; set; } = new RivetAssetId(0x0000000000000000);

	public new static PlanetMenuViewData Create(DDLObject ddl) => new(ddl);
}

