// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x0afc3e29u)]
public class PrimStyleCapsule : PrimStyleBase, IDDLObjectType<PrimStyleCapsule> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x0afc3e29u);

	public PrimStyleCapsule(DDLObject ddl) : base(ddl) {
		LocatorA = ddl.GetString(0xf4af194c) ?? LocatorA;
		LocatorB = ddl.GetString(0x6da648f6) ?? LocatorB;
		Radius = ddl.GetValue<float>(0x0504203du, Radius);
	}

	[DDLRegistration(0x0afc3e29u)]
	public string? LocatorA { get; set; } = default;

	[DDLRegistration(0x0afc3e29u)]
	public string? LocatorB { get; set; } = default;

	[DDLRegistration(0x0afc3e29u)]
	public float Radius { get; set; } = 0.00f;

	public new static PrimStyleCapsule Create(DDLObject ddl) => new(ddl);
}

