// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x7184742eu)]
public class ProtonSeekerAttackActiveEndEvent : EventBase, IDDLObjectType<ProtonSeekerAttackActiveEndEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x7184742eu);

	public ProtonSeekerAttackActiveEndEvent(DDLObject ddl) : base(ddl) { }

	public new static ProtonSeekerAttackActiveEndEvent Create(DDLObject ddl) => new(ddl);
}

