// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xf87c8c31u)]
public class RandomBoolGeneratorNodeDef : LogicNodeBaseDef, IDDLObjectType<RandomBoolGeneratorNodeDef> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xf87c8c31u);

	public RandomBoolGeneratorNodeDef(DDLObject ddl) : base(ddl) {
		GenerateNext = ddl.GetObject<InputPlugSignal>(0x9b44b772u);
		OnGenerateNext = ddl.GetObject<OutputPlugSignal>(0x9691f737u);
		Next = ddl.GetObject<OutputPlugBoolean>(0x34bfd08cu);
	}

	[DDLRegistration(0x9b44b772u)]
	public InputPlugSignal? GenerateNext { get; set; } = default;

	[DDLRegistration(0x9691f737u)]
	public OutputPlugSignal? OnGenerateNext { get; set; } = default;

	[DDLRegistration(0x34bfd08cu)]
	public OutputPlugBoolean? Next { get; set; } = default;

	public new static RandomBoolGeneratorNodeDef Create(DDLObject ddl) => new(ddl);
}

