// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x1f41f4abu)]
public class RCSSyncInput : DDLObjectType, IDDLObjectType<RCSSyncInput> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x1f41f4abu);

	public RCSSyncInput(DDLObject ddl) : base(ddl) {
		Views = ddl.GetStrings(0x08a35046u);
		Force = ddl.GetValue<bool>(0x8e3b4fe9u, Force);
		Preview = ddl.GetValue<bool>(0xb86f4c08u, Preview);
		OverrideRevisionOptions = ddl.GetValue<bool>(0x1303b973u, OverrideRevisionOptions);
		RevisionOptions = ddl.GetObject<RCSRevisionOptions>(0x531b5702u);
	}

	[DDLRegistration(0x1f41f4abu, description: "Can be full paths to files to sync, or paths with wildcards.")]
	public List<string?> Views { get; set; } = [];

	[DDLRegistration(0x1f41f4abu, description: "Force the sync operation, clobbering writable files.")]
	public bool Force { get; set; } = false;

	[DDLRegistration(0x1f41f4abu, description: "Preview the sync operation.")]
	public bool Preview { get; set; } = false;

	[DDLRegistration(0x1f41f4abu, description: "Use the provided revision options instead of the globally active settings.")]
	public bool OverrideRevisionOptions { get; set; } = false;

	[DDLRegistration(0x1f41f4abu, description: "Revision options to use when OverrideRevisionOptions is true. ")]
	public RCSRevisionOptions? RevisionOptions { get; set; } = default;

	public static RCSSyncInput Create(DDLObject ddl) => new(ddl);
}

