// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x12c9a194u)]
public class RefireChargeStopEvent : EventBase, IDDLObjectType<RefireChargeStopEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x12c9a194u);

	public RefireChargeStopEvent(DDLObject ddl) : base(ddl) {
		LocalSource = ddl.GetValue<byte>(0x40245b06u, LocalSource);
	}

	[DDLRegistration(0x12c9a194u)]
	public byte LocalSource { get; set; } = 0x00;

	public new static RefireChargeStopEvent Create(DDLObject ddl) => new(ddl);
}

