// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xe309dce2u)]
public class RegionAuxOverlay : DDLObjectType, IDDLObjectType<RegionAuxOverlay> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xe309dce2u);

	public RegionAuxOverlay(DDLObject ddl) : base(ddl) {
		OverlayFolderId = ddl.GetValue<RivetAssetId>(0x8204c636u, OverlayFolderId);
		OverlayType = ddl.GetString(0x50757acb) ?? OverlayType;
		ShadowingZones = ddl.GetObjects<RegionShadowingZone>(0x253cf949u);
	}

	[DDLRegistration(0xe309dce2u)]
	public RivetAssetId OverlayFolderId { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0xe309dce2u)]
	public string? OverlayType { get; set; } = default;

	[DDLRegistration(0xe309dce2u)]
	public List<RegionShadowingZone?> ShadowingZones { get; set; } = [];

	[DDLRegistration(0xe309dce2u)]
	public Dictionary<RivetAssetId, RegionNamedLink?> NamedLinks { get; set; } = [];

	[DDLRegistration(0xe309dce2u)]
	public Dictionary<RivetAssetId, RivetAssetId> NamedLinkRegions { get; set; } = [];

	public static RegionAuxOverlay Create(DDLObject ddl) => new(ddl);
}

