// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x39a2e421u)]
public class RegionMacroEconomyEntry : DDLObjectType, IDDLObjectType<RegionMacroEconomyEntry> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x39a2e421u);

	public RegionMacroEconomyEntry(DDLObject ddl) : base(ddl) {
		Regions = ddl.GetValues<RivetAssetId>(0xa38d1acbu);
		EconConfig = ddl.GetValue<RivetAssetId>(0xda3a4a5cu, EconConfig);
	}

	[DDLRegistration(0xa38d1acbu, description: "When guys spawn in these regions, they use these economy values")]
	public List<RivetAssetId> Regions { get; set; } = [];

	[DDLRegistration(0xda3a4a5cu)]
	public RivetAssetId EconConfig { get; set; } = default;

	public static RegionMacroEconomyEntry Create(DDLObject ddl) => new(ddl);
}

