// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x6c352121u)]
public class ReplayBranchNodeDef : BranchStartNodeBaseDef, IDDLObjectType<ReplayBranchNodeDef> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x6c352121u);

	public ReplayBranchNodeDef(DDLObject ddl) : base(ddl) {
		FirstPlayThroughOutput = ddl.GetObject<OutputPlugBoolean>(0xdecafe24u);
		ImmediateReplayOutput = ddl.GetObject<OutputPlugBoolean>(0x9a366745u);
		FullReplayOutput = ddl.GetObject<OutputPlugBoolean>(0x6205c167u);
	}

	[DDLRegistration(0x6c352121u)]
	public OutputPlugBoolean? FirstPlayThroughOutput { get; set; } = default;

	[DDLRegistration(0x6c352121u)]
	public OutputPlugBoolean? ImmediateReplayOutput { get; set; } = default;

	[DDLRegistration(0x6c352121u)]
	public OutputPlugBoolean? FullReplayOutput { get; set; } = default;

	public new static ReplayBranchNodeDef Create(DDLObject ddl) => new(ddl);
}

