// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x1dfb5decu)]
public class RetargetWalk : DDLObjectType, IDDLObjectType<RetargetWalk> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x1dfb5decu);

	public RetargetWalk(DDLObject ddl) : base(ddl) {
		Enabled = ddl.GetValue<bool>(0x5113d8bcu, Enabled);
		MinHideTime = ddl.GetValue<float>(0x0c4bc3fcu, MinHideTime);
		DelayBeforeWalk = ddl.GetValue<float>(0x4acbe5dcu, DelayBeforeWalk);
		WalkTime = ddl.GetValue<float>(0x6b41dcdbu, WalkTime);
		WaitingAimMul = ddl.GetValue<float>(0x1c92d996u, WaitingAimMul);
		LowCoverOffsetY = ddl.GetValue<float>(0x5dd4e668u, LowCoverOffsetY);
		LowCoverOffsetZ = ddl.GetValue<float>(0xc4ddb7d2u, LowCoverOffsetZ);
		HighCoverOffsetY = ddl.GetValue<float>(0xfda4440du, HighCoverOffsetY);
		HighCoverOffsetZ = ddl.GetValue<float>(0x64ad15b7u, HighCoverOffsetZ);
	}

	[DDLRegistration(0x1dfb5decu)]
	public bool Enabled { get; set; } = false;

	[DDLRegistration(0x1dfb5decu)]
	public float MinHideTime { get; set; } = 1.00f;

	[DDLRegistration(0x1dfb5decu)]
	public float DelayBeforeWalk { get; set; } = 0.75f;

	[DDLRegistration(0x1dfb5decu)]
	public float WalkTime { get; set; } = 0.50f;

	[DDLRegistration(0x1dfb5decu)]
	public float WaitingAimMul { get; set; } = 0.30f;

	[DDLRegistration(0x1dfb5decu)]
	public float LowCoverOffsetY { get; set; } = 0.80f;

	[DDLRegistration(0x1dfb5decu)]
	public float LowCoverOffsetZ { get; set; } = 0.50f;

	[DDLRegistration(0x1dfb5decu)]
	public float HighCoverOffsetY { get; set; } = 1.60f;

	[DDLRegistration(0x1dfb5decu)]
	public float HighCoverOffsetZ { get; set; } = 0.60f;

	public static RetargetWalk Create(DDLObject ddl) => new(ddl);
}

