// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x3d9f12eau)]
public class RobotestCineFrameActorInfo : DDLObjectType, IDDLObjectType<RobotestCineFrameActorInfo> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x3d9f12eau);

	public RobotestCineFrameActorInfo(DDLObject ddl) : base(ddl) {
		Tuid = ddl.GetValue<ulong>(0x5953f773u, Tuid);
		ActorName = ddl.GetString(0xcc4a4d21) ?? ActorName;
		ActorStatus = ddl.GetString(0x5fcc36f9) ?? ActorStatus;
		Transform = ddl.GetObject<DDLTransform>(0xf54f1ea1u);
		Drivers = ddl.GetObjects<RobotestCineActorDriverInfo>(0xe5faa03fu);
	}

	[DDLRegistration(0x5953f773u, description: "Cinematic Actor")]
	public ulong Tuid { get; set; } = 0x0000000000000000;

	[DDLRegistration(0xcc4a4d21u, description: "Actor Name")]
	public string? ActorName { get; set; } = default;

	[DDLRegistration(0x5fcc36f9u, description: "Actor status")]
	public string? ActorStatus { get; set; } = default;

	[DDLRegistration(0xf54f1ea1u, description: "Transform at the end of the frame")]
	public DDLTransform? Transform { get; set; } = default;

	[DDLRegistration(0xe5faa03fu, description: " Drivers on this actor this frame")]
	public List<RobotestCineActorDriverInfo?> Drivers { get; set; } = [];

	public static RobotestCineFrameActorInfo Create(DDLObject ddl) => new(ddl);
}

