// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x0a73910eu)]
public class SceneEditorScaleSceneNodesInput : DDLObjectType, IDDLObjectType<SceneEditorScaleSceneNodesInput> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x0a73910eu);

	public SceneEditorScaleSceneNodesInput(DDLObject ddl) : base(ddl) {
		NodeWorldIdToScale = ddl.GetDictionary<RivetAssetId, SceneEditorScaleFactor>(0xd2e4a309, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<SceneEditorScaleFactor>(mapId));
	}

	[DDLRegistration(0x0a73910eu)]
	public Dictionary<RivetAssetId, SceneEditorScaleFactor?> NodeWorldIdToScale { get; set; } = [];

	public static SceneEditorScaleSceneNodesInput Create(DDLObject ddl) => new(ddl);
}

