// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x46d591a4u)]
public class ScreenEffectListConfig : ConfigBase, IDDLObjectType<ScreenEffectListConfig> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x46d591a4u);

	public ScreenEffectListConfig(DDLObject ddl) : base(ddl) {
		ScreenEffectList = ddl.GetObjects<ScreenEffectEntry>(0x7dbc6d12u);
	}

	[DDLRegistration(0x7dbc6d12u)]
	public List<ScreenEffectEntry?> ScreenEffectList { get; set; } = [];

	public new static ScreenEffectListConfig Create(DDLObject ddl) => new(ddl);
}

