// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x0e18a83bu)]
public class ShockwaveGrenadeShotPrius : GrenadeShotPrius, IDDLObjectType<ShockwaveGrenadeShotPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x0e18a83bu);

	public ShockwaveGrenadeShotPrius(DDLObject ddl) : base(ddl) {
		InnerRingActor = ddl.GetValue<RivetAssetId>(0x59cfaaf7u, InnerRingActor);
		OuterRingActor = ddl.GetValue<RivetAssetId>(0x14ecfda5u, OuterRingActor);
	}

	[DDLRegistration(0x0e18a83bu)]
	public RivetAssetId InnerRingActor { get; set; } = default;

	[DDLRegistration(0x0e18a83bu)]
	public RivetAssetId OuterRingActor { get; set; } = default;

	public new static ShockwaveGrenadeShotPrius Create(DDLObject ddl) => new(ddl);
}

