// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x526bda7du)]
public class ShotProtoShotgunPrius : SimpleShotPrius, IDDLObjectType<ShotProtoShotgunPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x526bda7du);

	public ShotProtoShotgunPrius(DDLObject ddl) : base(ddl) {
		AudioEndpoint = ddl.GetValue<RivetAssetId>(0x49b26719u, AudioEndpoint);
		CloseRangeDamage = ddl.GetObject<ProtoShotgunDamageRange>(0xf9273eeeu);
		MidRangeDamage = ddl.GetObject<ProtoShotgunDamageRange>(0x34a69b54u);
		LongRangeDamage = ddl.GetObject<ProtoShotgunDamageRange>(0x8f353c5fu);
		EmberDotDamage = ddl.GetValue<float>(0xe020aa92u, EmberDotDamage);
		EmberDotDuration = ddl.GetValue<float>(0x17bc70ffu, EmberDotDuration);
		DamageHashString = ddl.GetString(0x5a2efcb4) ?? DamageHashString;
	}

	[DDLRegistration(0x526bda7du, "Audio Endpoint", "Actor asset to spawn at endpoints that did not hit anything.")]
	public RivetAssetId AudioEndpoint { get; set; } = default;

	[DDLRegistration(0x526bda7du, "Close Range damage")]
	public ProtoShotgunDamageRange? CloseRangeDamage { get; set; } = default;

	[DDLRegistration(0x526bda7du, "Mid Range Damage")]
	public ProtoShotgunDamageRange? MidRangeDamage { get; set; } = default;

	[DDLRegistration(0x526bda7du, "Long Range Damage")]
	public ProtoShotgunDamageRange? LongRangeDamage { get; set; } = default;

	[DDLRegistration(0x526bda7du, "Ember DOT Damage (%)", "Percent of spreadsheet damage amount (for shot #2) to apply as a DOT when a bot is impacted by both projectiles in a blast.")]
	public float EmberDotDamage { get; set; } = 0.10f;

	[DDLRegistration(0x526bda7du, "Ember DOT Duration")]
	public float EmberDotDuration { get; set; } = 3.50f;

	[DDLRegistration(0x526bda7du, "Damage Hash String")]
	public string? DamageHashString { get; set; } = default;

	public new static ShotProtoShotgunPrius Create(DDLObject ddl) => new(ddl);
}

