// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x0d16ca39u)]
public class ShotMotionPitOfDeathPrius : BasicShotMotionPrius, IDDLObjectType<ShotMotionPitOfDeathPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x0d16ca39u);

	public ShotMotionPitOfDeathPrius(DDLObject ddl) : base(ddl) { }

	public new static ShotMotionPitOfDeathPrius Create(DDLObject ddl) => new(ddl);
}

