// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xa10a450fu)]
public class ShotPredatorLauncherPrius : ExplosiveBulletPrius, IDDLObjectType<ShotPredatorLauncherPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xa10a450fu);

	public ShotPredatorLauncherPrius(DDLObject ddl) : base(ddl) {
		MiniMissileConfig = ddl.GetValue<RivetAssetId>(0x71654944u, MiniMissileConfig);
	}

	[DDLRegistration(0xa10a450fu)]
	public RivetAssetId MiniMissileConfig { get; set; } = default;

	public new static ShotPredatorLauncherPrius Create(DDLObject ddl) => new(ddl);
}

