// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x499a948du)]
public class SkinItemTextureOverrideListElement : DDLObjectType, IDDLObjectType<SkinItemTextureOverrideListElement> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x499a948du);

	public SkinItemTextureOverrideListElement(DDLObject ddl) : base(ddl) {
		Available = ddl.GetEnum<x7ecfc969>(0x27723b89u, x7ecfc969Values.Lookup);
		TextureOverride = ddl.GetObject<SkinItemTextureOverride>(0xe2b74ca6u);
	}

	[DDLRegistration(0x27723b89u, "Available", "How does this item become available")]
	public x7ecfc969 Available { get; set; } = x7ecfc969.Always;

	[DDLRegistration(0xe2b74ca6u, "Texture Override", "Texture override parameters")]
	public SkinItemTextureOverride? TextureOverride { get; set; } = default;

	public static SkinItemTextureOverrideListElement Create(DDLObject ddl) => new(ddl);
}

