// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x2f8a9950u)]
public class SkinManagerBasePrius : DDLObjectType, IDDLObjectType<SkinManagerBasePrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x2f8a9950u);

	public SkinManagerBasePrius(DDLObject ddl) : base(ddl) { }

	public static SkinManagerBasePrius Create(DDLObject ddl) => new(ddl);
}

