// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x728f0796u)]
public class SoundPortalingSettings : DDLObjectType, IDDLObjectType<SoundPortalingSettings> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x728f0796u);

	public SoundPortalingSettings(DDLObject ddl) : base(ddl) {
		Enabled = ddl.GetValue<bool>(0x5113d8bcu, Enabled);
		MaxPortals = ddl.GetValue<byte>(0xdc61d32bu, MaxPortals);
		MaxPortalsBetweenTwoVolumes = ddl.GetValue<byte>(0x3e992696u, MaxPortalsBetweenTwoVolumes);
		MaxPortaledPositionsPerSource = ddl.GetValue<byte>(0xd92a4525u, MaxPortaledPositionsPerSource);
		MaxFadingPositionsPerSource = ddl.GetValue<byte>(0x18c3da0eu, MaxFadingPositionsPerSource);
		MaxVolumes = ddl.GetValue<uint>(0x0005eabau, MaxVolumes);
		PortalInterpolationSpeed = ddl.GetValue<float>(0x1b817a67u, PortalInterpolationSpeed);
		PortalInterpolationMode = ddl.GetEnum<x652a90fd>(0x3e78e991u, x652a90fdValues.Lookup);
		PortalRTPC = ddl.GetString(0x7bc8d5ff) ?? PortalRTPC;
	}

	[DDLRegistration(0x728f0796u)]
	public bool Enabled { get; set; } = false;

	[DDLRegistration(0x728f0796u)]
	public byte MaxPortals { get; set; } = 0x40;

	[DDLRegistration(0x728f0796u)]
	public byte MaxPortalsBetweenTwoVolumes { get; set; } = 0x04;

	[DDLRegistration(0x728f0796u)]
	public byte MaxPortaledPositionsPerSource { get; set; } = 0x04;

	[DDLRegistration(0x728f0796u)]
	public byte MaxFadingPositionsPerSource { get; set; } = 0x08;

	[DDLRegistration(0x728f0796u)]
	public uint MaxVolumes { get; set; } = 0x00000080;

	[DDLRegistration(0x728f0796u, description: "The speed at which portals fade in an out, in normalized untis per second")]
	public float PortalInterpolationSpeed { get; set; } = 3.00f;

	[DDLRegistration(0x728f0796u)]
	public x652a90fd PortalInterpolationMode { get; set; } = x652a90fd.PortalBendAggregationRuleAverage;

	[DDLRegistration(0x728f0796u)]
	public string? PortalRTPC { get; set; } = "PortalPower";

	public static SoundPortalingSettings Create(DDLObject ddl) => new(ddl);
}

