// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x690daf0du)]
public class SpawnedShotEmitterConfig : ConfigBase, IDDLObjectType<SpawnedShotEmitterConfig> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x690daf0du);

	public SpawnedShotEmitterConfig(DDLObject ddl) : base(ddl) {
		EmitterPrius = ddl.GetObject<WeaponEmitterBasePrius>(0x814e290fu);
	}

	[DDLRegistration(0x814e290fu)]
	public WeaponEmitterBasePrius? EmitterPrius { get; set; } = default;

	public new static SpawnedShotEmitterConfig Create(DDLObject ddl) => new(ddl);
}

