// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x6327a921u)]
public class StatusEffectResurrectingEvent : EventBase, IDDLObjectType<StatusEffectResurrectingEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x6327a921u);

	public StatusEffectResurrectingEvent(DDLObject ddl) : base(ddl) {
		TimeUntilResurrect = ddl.GetValue<float>(0x91858f44u, TimeUntilResurrect);
	}

	[DDLRegistration(0x6327a921u)]
	public float TimeUntilResurrect { get; set; } = 0.00f;

	public new static StatusEffectResurrectingEvent Create(DDLObject ddl) => new(ddl);
}

