// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xb9868964u)]
public class StaticOrientation : OrientationMode, IDDLObjectType<StaticOrientation> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xb9868964u);

	public StaticOrientation(DDLObject ddl) : base(ddl) {
		OneTimeRotation = ddl.GetObject<DDLVector3>(0x053541dbu);
	}

	[DDLRegistration(0xb9868964u)]
	public DDLVector3? OneTimeRotation { get; set; } = default;

	public new static StaticOrientation Create(DDLObject ddl) => new(ddl);
}

