// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x24508fadu)]
public class StreamingVideoSoundStartStreamEvent : EventBase, IDDLObjectType<StreamingVideoSoundStartStreamEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x24508fadu);

	public StreamingVideoSoundStartStreamEvent(DDLObject ddl) : base(ddl) {
		StreamIndex = ddl.GetValue<uint>(0x265c5066u, StreamIndex);
	}

	[DDLRegistration(0x265c5066u)]
	public uint StreamIndex { get; set; } = 0x00000000;

	public new static StreamingVideoSoundStartStreamEvent Create(DDLObject ddl) => new(ddl);
}

