// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x1f7a8a59u)]
public class SyncedAnimPropAlignPrius : ProceduralJointAlignPrius, IDDLObjectType<SyncedAnimPropAlignPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x1f7a8a59u);

	public SyncedAnimPropAlignPrius(DDLObject ddl) : base(ddl) { }

	public new static SyncedAnimPropAlignPrius Create(DDLObject ddl) => new(ddl);
}

