// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x098c676cu)]
public class TestFlagStructPrius : DDLObjectType, IDDLObjectType<TestFlagStructPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x098c676cu);

	public TestFlagStructPrius(DDLObject ddl) : base(ddl) {
		One = ddl.GetBitset<TestFlags>(0x5039af38u, TestFlagsValues.Lookup);
		Two = ddl.GetBitset<TestFlags>(0x3b9fa3afu, TestFlagsValues.Lookup);
		Third = ddl.GetString(0x3d61eca5) ?? Third;
	}

	[DDLRegistration(0x5039af38u)]
	public TestFlags One { get; set; } = (TestFlags) 0x00000000;

	[DDLRegistration(0x3b9fa3afu)]
	public TestFlags Two { get; set; } = (TestFlags) 0x00000000;

	[DDLRegistration(0x3d61eca5u)]
	public string? Third { get; set; } = default;

	public static TestFlagStructPrius Create(DDLObject ddl) => new(ddl);
}

