// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xf8c4c18du)]
public class TriggerEffectSystemConfig : ConfigBase, IDDLObjectType<TriggerEffectSystemConfig> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xf8c4c18du);

	public TriggerEffectSystemConfig(DDLObject ddl) : base(ddl) {
		TriggerEffectTypeArray = ddl.GetObjects<TriggerEffectArrayItem>(0xfce87888u);
	}

	[DDLRegistration(0xf8c4c18du)]
	public List<TriggerEffectArrayItem?> TriggerEffectTypeArray { get; set; } = [];

	public new static TriggerEffectSystemConfig Create(DDLObject ddl) => new(ddl);
}

