// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x014f4fa8u)]
public class TurretIonCannonShotPrius : BasicBulletPrius, IDDLObjectType<TurretIonCannonShotPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x014f4fa8u);

	public TurretIonCannonShotPrius(DDLObject ddl) : base(ddl) { }

	public new static TurretIonCannonShotPrius Create(DDLObject ddl) => new(ddl);
}

