// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x6fadc6f0u)]
public class UDSWebApiTrophySetMetadata : DDLObjectType, IDDLObjectType<UDSWebApiTrophySetMetadata> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x6fadc6f0u);

	public UDSWebApiTrophySetMetadata(DDLObject ddl) : base(ddl) {
		Name = ddl.GetDictionary<string, string>(0xce811188, DDLMapTypeHandler.VisitString, (mapId, mapDDL) => mapDDL.GetString(mapId));
		Platform = ddl.GetEnums<xcf5dc143>(0x3a250fedu, xcf5dc143Values.Lookup);
		TrophySetVersion = ddl.GetString(0x558d3d7b) ?? TrophySetVersion;
		TrophySchemaVersion = ddl.GetString(0xff91af69) ?? TrophySchemaVersion;
		DefaultLanguage = ddl.GetString(0x204e4dc8) ?? DefaultLanguage;
	}

	[DDLRegistration(0xce811188u)]
	public Dictionary<string, string?> Name { get; set; } = [];

	[DDLRegistration(0x3a250fedu)]
	public List<xcf5dc143> Platform { get; set; } = [];

	[DDLRegistration(0x558d3d7bu)]
	public string? TrophySetVersion { get; set; } = default;

	[DDLRegistration(0xff91af69u)]
	public string? TrophySchemaVersion { get; set; } = default;

	[DDLRegistration(0x204e4dc8u)]
	public string? DefaultLanguage { get; set; } = default;

	public static UDSWebApiTrophySetMetadata Create(DDLObject ddl) => new(ddl);
}

