// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x5444d6f1u)]
public class UI_CinematicInstanceZone : DDLObjectType, IDDLObjectType<UI_CinematicInstanceZone> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x5444d6f1u);

	public UI_CinematicInstanceZone(DDLObject ddl) : base(ddl) {
		IsCinematicOwner = ddl.GetValue<bool>(0x1520cb03u, IsCinematicOwner);
		ParentRegionAssetPath = ddl.GetValue<RivetAssetId>(0x80b18bf0u, ParentRegionAssetPath);
		ShadowZoneAssetPath = ddl.GetValue<RivetAssetId>(0x52d00d23u, ShadowZoneAssetPath);
		ZoneAssetPath = ddl.GetValue<RivetAssetId>(0x37f3578cu, ZoneAssetPath);
	}

	[DDLRegistration(0x1520cb03u)]
	public bool IsCinematicOwner { get; set; } = false;

	[DDLRegistration(0x80b18bf0u)]
	public RivetAssetId ParentRegionAssetPath { get; set; } = default;

	[DDLRegistration(0x52d00d23u)]
	public RivetAssetId ShadowZoneAssetPath { get; set; } = default;

	[DDLRegistration(0x37f3578cu)]
	public RivetAssetId ZoneAssetPath { get; set; } = default;

	public static UI_CinematicInstanceZone Create(DDLObject ddl) => new(ddl);
}

