// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xb236ead1u)]
public class UIDifficultyData : DDLObjectType, IDDLObjectType<UIDifficultyData> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xb236ead1u);

	public UIDifficultyData(DDLObject ddl) : base(ddl) {
		DifficultyID = ddl.GetEnum<DifficultyLevel>(0xd6b6733bu, DifficultyLevelValues.Lookup);
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		Desc = ddl.GetString(0x3b256ce4) ?? Desc;
		EnemyAggressiveness = ddl.GetValue<float>(0x620adc04u, EnemyAggressiveness);
		EnemyDamage = ddl.GetValue<float>(0x8bbafa0eu, EnemyDamage);
		EnemyHealth = ddl.GetValue<float>(0x54a88d71u, EnemyHealth);
	}

	[DDLRegistration(0xd6b6733bu, "Difficulty ID")]
	public DifficultyLevel DifficultyID { get; set; } = DifficultyLevel.Easy;

	[DDLRegistration(0x6eb3beb6u, "Difficulty Name")]
	public string? Name { get; set; } = default;

	[DDLRegistration(0x3b256ce4u, "Difficulty Description")]
	public string? Desc { get; set; } = default;

	[DDLRegistration(0x620adc04u, "Enemy Aggressiveness", "From 0-1, how agressive the enemies are at this difficulty. Only used for display purposes.")]
	public float EnemyAggressiveness { get; set; } = 1.00f;

	[DDLRegistration(0x8bbafa0eu, "Enemy Damage", "From 0-1, how damaging the enemies are at this difficulty. Only used for display purposes.")]
	public float EnemyDamage { get; set; } = 1.00f;

	[DDLRegistration(0x54a88d71u, "Enemy Health", "From 0-1, how much health the enemies ahve at this difficulty. Only used for display purposes.")]
	public float EnemyHealth { get; set; } = 1.00f;

	public static UIDifficultyData Create(DDLObject ddl) => new(ddl);
}

