// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x83816584u)]
public class UIFontMapping : DDLObjectType, IDDLObjectType<UIFontMapping> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x83816584u);

	public UIFontMapping(DDLObject ddl) : base(ddl) {
		Language = ddl.GetEnum<x0572515d>(0x2edaccc5u, x0572515dValues.Lookup);
		Font = ddl.GetString(0xe004c862) ?? Font;
		FontsToReplace = ddl.GetStrings(0x34a083a1u);
	}

	[DDLRegistration(0x83816584u, description: "The language for which to do the swap.")]
	public x0572515d Language { get; set; } = x0572515d.LanguageEnglish;

	[DDLRegistration(0x83816584u, description: "Asset path of font to use for this language.")]
	public string? Font { get; set; } = "ui/MyPath/MyFont.ttf";

	[DDLRegistration(0x83816584u, description: "Asset path of font(s) to be replaced.")]
	public List<string?> FontsToReplace { get; set; } = [];

	public static UIFontMapping Create(DDLObject ddl) => new(ddl);
}

