// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xbb79dbdau)]
public class UIOptionTypeSettingSlider : UIOptionTypeSettingBase, IDDLObjectType<UIOptionTypeSettingSlider> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xbb79dbdau);

	public UIOptionTypeSettingSlider(DDLObject ddl) : base(ddl) {
		SliderMinimum = ddl.GetValue<int>(0x5a3038ceu, SliderMinimum);
		SliderFidelity = ddl.GetValue<int>(0x5ade504fu, SliderFidelity);
		GamePreview = ddl.GetValue<bool>(0x7fe20d3cu, GamePreview);
	}

	[DDLRegistration(0x5a3038ceu, description: "Min value for slider options")]
	public int SliderMinimum { get; set; } = 0;

	[DDLRegistration(0x5ade504fu, description: "Fidelity for slider options")]
	public int SliderFidelity { get; set; } = 10;

	[DDLRegistration(0x7fe20d3cu, description: "Show this slider in-game alone, outside of settings list, with the full game preview (e.g. Brightness)")]
	public bool GamePreview { get; set; } = false;

	public new static UIOptionTypeSettingSlider Create(DDLObject ddl) => new(ddl);
}

