// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x305b331cu)]
public class VanitytSettings : DDLObjectType, IDDLObjectType<VanitytSettings> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x305b331cu);

	public VanitytSettings(DDLObject ddl) : base(ddl) {
		DrawDebugImguiWindow = ddl.GetValue<bool>(0x623d726eu, DrawDebugImguiWindow);
	}

	[DDLRegistration(0x623d726eu, "Draw Vanity Debug ImGui Window", "Should the Vanity Debug ImGui window be displayed?")]
	public bool DrawDebugImguiWindow { get; set; } = false;

	public static VanitytSettings Create(DDLObject ddl) => new(ddl);
}

