// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x10f29a1au)]
public class VanityColorData : DDLObjectType, IDDLObjectType<VanityColorData> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x10f29a1au);

	public VanityColorData(DDLObject ddl) : base(ddl) {
		ColorId = ddl.GetValue<byte>(0xdcecc79bu, ColorId);
	}

	[DDLRegistration(0x10f29a1au)]
	public byte ColorId { get; set; } = 0x00;

	public static VanityColorData Create(DDLObject ddl) => new(ddl);
}

