// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x5da86d84u)]
public class VaultToC : DDLObjectType, IDDLObjectType<VaultToC> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x5da86d84u);

	public VaultToC(DDLObject ddl) : base(ddl) {
		_id = ddl.GetValue<RivetAssetId>(0x7459aa19u, _id);
		Path = ddl.GetValue<RivetAssetId>(0x3bc44bbfu, Path);
		Dir = ddl.GetValue<RivetAssetId>(0x90fe53d9u, Dir);
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		Ext = ddl.GetString(0x2b86bfcb) ?? Ext;
		Crtd = ddl.GetString(0x6ebee2cc) ?? Crtd;
		Mod = ddl.GetString(0x3da17a81) ?? Mod;
		Time = ddl.GetString(0x5f0458f5) ?? Time;
		Stat = ddl.GetValue<uint>(0x10283f91u, Stat);
		Err = ddl.GetValue<uint>(0x380af274u, Err);
	}

	[DDLRegistration(0x5da86d84u, "Vault ID", "Vault ID for this file. Currently equivalent to the AssetId of the file.")]
	public RivetAssetId _id { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0x5da86d84u, "Path", "Relative path to the file.")]
	public RivetAssetId Path { get; set; } = "";

	[DDLRegistration(0x5da86d84u, "Directory", "Directory, relative to the specified root, where this file can be found.")]
	public RivetAssetId Dir { get; set; } = "";

	[DDLRegistration(0x5da86d84u, "File Name", "Name of the file, minus the extension.")]
	public string? Name { get; set; } = "";

	[DDLRegistration(0x5da86d84u, "Extension", "File suffix (value after the last dot in the file path).")]
	public string? Ext { get; set; } = "";

	[DDLRegistration(0x5da86d84u, "Created By", "Username of the person who created the file.")]
	public string? Crtd { get; set; } = "";

	[DDLRegistration(0x5da86d84u, "Last Modified By", "Username of the person who last modified the file.")]
	public string? Mod { get; set; } = "";

	[DDLRegistration(0x5da86d84u, "Modified Time", "Timestamp when the file was last modified, not necessarily when it was last saved.")]
	public string? Time { get; set; } = "";

	[DDLRegistration(0x5da86d84u, "Status", "Indicates current status of this file's dependencies, see enum VaultStatus. This will be the hash of the select value.")]
	public uint Stat { get; set; } = 0x00000000;

	[DDLRegistration(0x5da86d84u, "Error", "Optional; If Stat == kErrorHash, this field will contain the hash of one of the error codes specified in VaultError.")]
	public uint Err { get; set; } = 0x00000000;

	public static VaultToC Create(DDLObject ddl) => new(ddl);
}

