// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xdfcdf8ceu)]
public class VehicleThrustersOnEvent : EventBase, IDDLObjectType<VehicleThrustersOnEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xdfcdf8ceu);

	public VehicleThrustersOnEvent(DDLObject ddl) : base(ddl) {
		VehicleId = ddl.GetValue<uint>(0x62feded2u, VehicleId);
	}

	[DDLRegistration(0x62feded2u)]
	public uint VehicleId { get; set; } = 0x00000000;

	public new static VehicleThrustersOnEvent Create(DDLObject ddl) => new(ddl);
}

