// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x299f4ae2u)]
public class VehicleObstaclePrius : DDLObjectType, IDDLObjectType<VehicleObstaclePrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x299f4ae2u);

	public VehicleObstaclePrius(DDLObject ddl) : base(ddl) {
		RemoveVehicles = ddl.GetValue<bool>(0x80d67c2fu, RemoveVehicles);
	}

	[DDLRegistration(0x80d67c2fu, "Remove Vehicles While Active?", "Should we remove all vehicles within this volume while this volume actor is active?")]
	public bool RemoveVehicles { get; set; } = false;

	public static VehicleObstaclePrius Create(DDLObject ddl) => new(ddl);
}

