// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x9b7cd4f5u)]
public class VisualEffectCollapsibleGraphNode : DDLObjectType, IDDLObjectType<VisualEffectCollapsibleGraphNode> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x9b7cd4f5u);

	public VisualEffectCollapsibleGraphNode(DDLObject ddl) : base(ddl) {
		NodeId = ddl.GetValue<RivetAssetId>(0x371a59e0u, NodeId);
		XPos = ddl.GetValue<int>(0xf88aee81u, XPos);
		YPos = ddl.GetValue<int>(0x403689e4u, YPos);
		DisplayName = ddl.GetString(0xeaf33243) ?? DisplayName;
		ConnectedInputs = ddl.GetObjects<VisualEffectNodeConnectedInputPort>(0x8ca57bf5u);
		ConnectedOutputs = ddl.GetObjects<VisualEffectNodeConnectedOutputPort>(0x824bee0eu);
		Collapsed = ddl.GetValue<bool>(0xf07e7fafu, Collapsed);
	}

	[DDLRegistration(0x371a59e0u)]
	public RivetAssetId NodeId { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0xf88aee81u)]
	public int XPos { get; set; } = 0;

	[DDLRegistration(0x403689e4u)]
	public int YPos { get; set; } = 0;

	[DDLRegistration(0xeaf33243u, "Name")]
	public string? DisplayName { get; set; } = default;

	[DDLRegistration(0x8ca57bf5u)]
	public List<VisualEffectNodeConnectedInputPort?> ConnectedInputs { get; set; } = [];

	[DDLRegistration(0x824bee0eu)]
	public List<VisualEffectNodeConnectedOutputPort?> ConnectedOutputs { get; set; } = [];

	[DDLRegistration(0xf07e7fafu)]
	public bool Collapsed { get; set; } = true;

	public static VisualEffectCollapsibleGraphNode Create(DDLObject ddl) => new(ddl);
}

