// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0xb15a06c5u)]
public class VisualEffectCamAttrNode : DDLObjectType, IDDLObjectType<VisualEffectCamAttrNode> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xb15a06c5u);

	public VisualEffectCamAttrNode(DDLObject ddl) : base(ddl) {
		NodeId = ddl.GetValue<RivetAssetId>(0x371a59e0u, NodeId);
		XPos = ddl.GetValue<int>(0xf88aee81u, XPos);
		YPos = ddl.GetValue<int>(0x403689e4u, YPos);
		DisplayName = ddl.GetString(0xeaf33243) ?? DisplayName;
		ConnectedInputs = ddl.GetObjects<VisualEffectNodeConnectedInputPort>(0x8ca57bf5u);
		ConnectedOutputs = ddl.GetObjects<VisualEffectNodeConnectedOutputPort>(0x824bee0eu);
		OutputPort_Output = ddl.GetObject<VisualEffectCamAttr>(0x7778788cu);
	}

	[DDLRegistration(0xb15a06c5u)]
	public RivetAssetId NodeId { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0xb15a06c5u)]
	public int XPos { get; set; } = 0;

	[DDLRegistration(0xb15a06c5u)]
	public int YPos { get; set; } = 0;

	[DDLRegistration(0xb15a06c5u, "Name")]
	public string? DisplayName { get; set; } = default;

	[DDLRegistration(0xb15a06c5u)]
	public List<VisualEffectNodeConnectedInputPort?> ConnectedInputs { get; set; } = [];

	[DDLRegistration(0xb15a06c5u)]
	public List<VisualEffectNodeConnectedOutputPort?> ConnectedOutputs { get; set; } = [];

	[DDLRegistration(0xb15a06c5u, "Output")]
	public VisualEffectCamAttr? OutputPort_Output { get; set; } = default;

	public static VisualEffectCamAttrNode Create(DDLObject ddl) => new(ddl);
}

