// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x4ec46cc3u)]
public class VisualEffectSpawnStyleNode : DDLObjectType, IDDLObjectType<VisualEffectSpawnStyleNode> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x4ec46cc3u);

	public VisualEffectSpawnStyleNode(DDLObject ddl) : base(ddl) {
		NodeId = ddl.GetValue<RivetAssetId>(0x371a59e0u, NodeId);
		XPos = ddl.GetValue<int>(0xf88aee81u, XPos);
		YPos = ddl.GetValue<int>(0x403689e4u, YPos);
		DisplayName = ddl.GetString(0xeaf33243) ?? DisplayName;
		ConnectedInputs = ddl.GetObjects<VisualEffectNodeConnectedInputPort>(0x8ca57bf5u);
		ConnectedOutputs = ddl.GetObjects<VisualEffectNodeConnectedOutputPort>(0x824bee0eu);
		DirectionStyle = ddl.GetEnum<x3df0267a>(0x5563d999u, x3df0267aValues.Lookup);
		PositionStyle = ddl.GetEnum<xcdf4306c>(0x83b82bbeu, xcdf4306cValues.Lookup);
		ShapeStyle = ddl.GetEnum<x81b59607>(0x5e37a5fcu, x81b59607Values.Lookup);
		ShapeModel = ddl.GetValue<RivetAssetId>(0xba1f6f4fu, ShapeModel);
		Length = ddl.GetValue<float>(0x3f05d0d5u, Length);
		Radius = ddl.GetValue<float>(0x0504203du, Radius);
		BoxWidth = ddl.GetValue<float>(0x1c9beb49u, BoxWidth);
		BoxHeight = ddl.GetValue<float>(0x830e4f41u, BoxHeight);
		BoxDepth = ddl.GetValue<float>(0x6a22b20fu, BoxDepth);
		OriginOffset = ddl.GetObject<DDLVector3>(0xaa6ac71eu);
		MaxAngle = ddl.GetValue<float>(0x191f829eu, MaxAngle);
		MinAngle = ddl.GetValue<float>(0xff7f2d7fu, MinAngle);
		MaxSweep = ddl.GetValue<float>(0x91b5d5a5u, MaxSweep);
		MinSweep = ddl.GetValue<float>(0x77d57a44u, MinSweep);
		SphericalPitch = ddl.GetValue<float>(0x8e576947u, SphericalPitch);
		DirectionSpread = ddl.GetValue<float>(0x8a653232u, DirectionSpread);
		SpawnDirections = ddl.GetObject<SpawnDirections>(0x4dec0a2eu);
		InputPort_UDTransform = ddl.GetObject<VisualEffectTransform>(0x1986ab08u);
		UDSpace = ddl.GetEnum<x45f5c485>(0x988e1293u, x45f5c485Values.Lookup);
	}

	[DDLRegistration(0x4ec46cc3u)]
	public RivetAssetId NodeId { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0x4ec46cc3u)]
	public int XPos { get; set; } = 0;

	[DDLRegistration(0x4ec46cc3u)]
	public int YPos { get; set; } = 0;

	[DDLRegistration(0x4ec46cc3u, "Name")]
	public string? DisplayName { get; set; } = default;

	[DDLRegistration(0x4ec46cc3u)]
	public List<VisualEffectNodeConnectedInputPort?> ConnectedInputs { get; set; } = [];

	[DDLRegistration(0x4ec46cc3u)]
	public List<VisualEffectNodeConnectedOutputPort?> ConnectedOutputs { get; set; } = [];

	[DDLRegistration(0x4ec46cc3u)]
	public x3df0267a DirectionStyle { get; set; } = x3df0267a.Out;

	[DDLRegistration(0x4ec46cc3u)]
	public xcdf4306c PositionStyle { get; set; } = xcdf4306c.Fill;

	[DDLRegistration(0x4ec46cc3u)]
	public x81b59607 ShapeStyle { get; set; } = x81b59607.Cone;

	[DDLRegistration(0x4ec46cc3u, description: "If set to a valid model, this will override the shape style")]
	public RivetAssetId ShapeModel { get; set; } = default;

	[DDLRegistration(0x4ec46cc3u)]
	public float Length { get; set; } = 0.00f;

	[DDLRegistration(0x4ec46cc3u)]
	public float Radius { get; set; } = 1.00f;

	[DDLRegistration(0x4ec46cc3u, "Width", "Box Width")]
	public float BoxWidth { get; set; } = 1.00f;

	[DDLRegistration(0x4ec46cc3u, "Height", "Box Height")]
	public float BoxHeight { get; set; } = 1.00f;

	[DDLRegistration(0x4ec46cc3u, "Depth", "Box Depth")]
	public float BoxDepth { get; set; } = 1.00f;

	[DDLRegistration(0x4ec46cc3u, "Origin Offset", "Offset the spawn style origin and take Width/Height/Length/Radius as well as key-framed scales into consideration")]
	public DDLVector3? OriginOffset { get; set; } = default;

	[DDLRegistration(0x4ec46cc3u, "Max Pitch")]
	public float MaxAngle { get; set; } = 180.00f;

	[DDLRegistration(0x4ec46cc3u, "Min Pitch")]
	public float MinAngle { get; set; } = 0.00f;

	[DDLRegistration(0x4ec46cc3u, "Max Sweep")]
	public float MaxSweep { get; set; } = 180.00f;

	[DDLRegistration(0x4ec46cc3u, "Min Sweep")]
	public float MinSweep { get; set; } = -180.00f;

	[DDLRegistration(0x4ec46cc3u, "Spherical Pitch")]
	public float SphericalPitch { get; set; } = 0.00f;

	[DDLRegistration(0x4ec46cc3u, "Direction Spread")]
	public float DirectionSpread { get; set; } = 0.00f;

	[DDLRegistration(0x4ec46cc3u, "Spawn Directions")]
	public SpawnDirections? SpawnDirections { get; set; } = default;

	[DDLRegistration(0x4ec46cc3u, "Uniform Direction")]
	public VisualEffectTransform? InputPort_UDTransform { get; set; } = default;

	[DDLRegistration(0x4ec46cc3u, "Uniform Direction Space")]
	public x45f5c485 UDSpace { get; set; } = x45f5c485.Off;

	public static VisualEffectSpawnStyleNode Create(DDLObject ddl) => new(ddl);
}

