// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x8f243e92u)]
public class VisualEffectCamAttr : DDLObjectType, IDDLObjectType<VisualEffectCamAttr> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x8f243e92u);

	public VisualEffectCamAttr(DDLObject ddl) : base(ddl) {
		Enable = ddl.GetValue<bool>(0xcdd88655u, Enable);
		KillCulled = ddl.GetValue<bool>(0xf0bf3a73u, KillCulled);
		SpawnCulled = ddl.GetValue<bool>(0x9b403caau, SpawnCulled);
		Source = ddl.GetEnum<x21f55189>(0x61f23114u, x21f55189Values.Lookup);
		MaterialLoDDistance = ddl.GetValue<float>(0xc08563c1u, MaterialLoDDistance);
		FarClip = ddl.GetValue<float>(0x180cce8cu, FarClip);
		FarFadeStart = ddl.GetValue<float>(0x12418a7bu, FarFadeStart);
		NearFadeStart = ddl.GetValue<float>(0x199cd49du, NearFadeStart);
		NearClip = ddl.GetValue<float>(0xef20b8c7u, NearClip);
	}

	[DDLRegistration(0x8f243e92u)]
	public bool Enable { get; set; } = false;

	[DDLRegistration(0x8f243e92u, "Kill Out of View")]
	public bool KillCulled { get; set; } = false;

	[DDLRegistration(0x8f243e92u, "Spawn Out of View")]
	public bool SpawnCulled { get; set; } = true;

	[DDLRegistration(0x8f243e92u)]
	public x21f55189 Source { get; set; } = x21f55189.Self;

	[DDLRegistration(0x8f243e92u, "Material LoD Dist")]
	public float MaterialLoDDistance { get; set; } = 40.00f;

	[DDLRegistration(0x8f243e92u, "Far Clip")]
	public float FarClip { get; set; } = 60.00f;

	[DDLRegistration(0x8f243e92u, "Far Fade Start")]
	public float FarFadeStart { get; set; } = 40.00f;

	[DDLRegistration(0x8f243e92u, "Near Fade Start")]
	public float NearFadeStart { get; set; } = 1.00f;

	[DDLRegistration(0x8f243e92u, "Near Clip")]
	public float NearClip { get; set; } = 0.00f;

	public static VisualEffectCamAttr Create(DDLObject ddl) => new(ddl);
}

