// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x872eed51u)]
public class VisualEffectRenderNode : DDLObjectType, IDDLObjectType<VisualEffectRenderNode> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x872eed51u);

	public VisualEffectRenderNode(DDLObject ddl) : base(ddl) {
		NodeId = ddl.GetValue<RivetAssetId>(0x371a59e0u, NodeId);
		XPos = ddl.GetValue<int>(0xf88aee81u, XPos);
		YPos = ddl.GetValue<int>(0x403689e4u, YPos);
		DisplayName = ddl.GetString(0xeaf33243) ?? DisplayName;
		ConnectedInputs = ddl.GetObjects<VisualEffectNodeConnectedInputPort>(0x8ca57bf5u);
		ConnectedOutputs = ddl.GetObjects<VisualEffectNodeConnectedOutputPort>(0x824bee0eu);
		Collapsed = ddl.GetValue<bool>(0xf07e7fafu, Collapsed);
		Type = ddl.GetString(0xbc4e9799) ?? Type;
		RenderStyle = ddl.GetEnum<RenderStyle>(0x1ce19fbdu, RenderStyleValues.Lookup);
		Platforms = ddl.GetObject<VisualEffectPlatforms>(0x957c19efu);
		EditorOnly = ddl.GetValue<bool>(0xc2612b29u, EditorOnly);
		Space = ddl.GetEnum<xfe5100b1>(0x30210dfbu, xfe5100b1Values.Lookup);
		RenderAttributes = ddl.GetObject<RenderAttributes>(0x8633b21au);
		ConduitAttributes = ddl.GetObject<ConduitAttributes>(0xecb72241u);
		DecalTrailAttributes = ddl.GetObject<DecalTrailAttributes>(0xd5354488u);
		UV0Tiling = ddl.GetObject<UVTiling>(0xf8890730u);
		UV1Tiling = ddl.GetObject<UVTiling>(0x5efe0c84u);
		RadialBlur = ddl.GetObject<RadialBlurInfo>(0xc86e2898u);
		InputPort_Transform = ddl.GetObject<VisualEffectTransform>(0x98a0c43au);
		InputPort_LensFlare = ddl.GetObject<VisualEffectLensFlare>(0xb2ff0f67u);
		InputPort_SphericalNormal = ddl.GetObject<VisualEffectFloat>(0x9e6e7998u);
		InputPort_Height = ddl.GetObject<VisualEffectFloat>(0xb49f8627u);
		InputPort_Width = ddl.GetObject<VisualEffectFloat>(0x55697da2u);
		InputPort_Depth = ddl.GetObject<VisualEffectFloat>(0x23d024e4u);
		PostEffect = ddl.GetObject<PostEffect>(0x77d9aa8eu);
		SplineStyle = ddl.GetEnum<SplineStyle>(0xb5cf515fu, SplineStyleValues.Lookup);
		BeamOffset = ddl.GetObject<DDLVector2>(0xe21ec5acu);
		TrailAttributes = ddl.GetObject<TrailAttributes>(0xf205bf26u);
		SwipeScale = ddl.GetEnum<SwipeScale>(0x2150ae07u, SwipeScaleValues.Lookup);
		SwipeOffset = ddl.GetObject<DDLVector3>(0xff74e14cu);
		InputPort_LightAttr = ddl.GetObject<VisualEffectLightAttr>(0x5f04727cu);
		InputPort_LifeTime = ddl.GetObject<VisualEffectMinMax>(0x55ea52d3u);
		InputPort_SpawnDelay = ddl.GetObject<VisualEffectMinMax>(0x00d8163fu);
		UVFlips = ddl.GetObject<SeparateUVFlips>(0xff77e4adu);
		FloatKeyFrames_Luminance = ddl.GetObject<VisualEffectFloatKeyFrames>(0xa719d434u);
		ColorKeyFrames_Color = ddl.GetObject<VisualEffectColorKeyFrames>(0x848dcbf9u);
		Float2KeyFrames_Alpha = ddl.GetObject<VisualEffectFloat2KeyFrames>(0x54d4ba7du);
		FloatKeyFrames_AlphaMultiplier = ddl.GetObject<VisualEffectFloatKeyFrames>(0xf8073360u);
		Float3KeyFrames_Rotation = ddl.GetObject<VisualEffectRotationKeyFrames>(0x29ac4bf7u);
		Float3KeyFrames_Scales = ddl.GetObject<VisualEffectFloat3KeyFrames>(0x27c45b9du);
		Float3KeyFrames_Custom = ddl.GetObject<VisualEffectFloat3KeyFrames>(0x23778311u);
		InputPort_CameraOffset = ddl.GetObject<VisualEffectFloat>(0xd2d4783du);
		InputPort_RandomSeed = ddl.GetObject<VisualEffectFloat>(0x01c11433u);
		ForceFieldAttributes = ddl.GetObject<ForceFieldAttributes>(0x8def880cu);
		TurbulenceAttributes = ddl.GetObject<TurbulenceAttributes>(0x39ddadb1u);
		TrailAgeKeyframe = ddl.GetObject<TrailAgeKeyframe>(0x7d558cbbu);
		DecalAttributes = ddl.GetObject<DecalAttributes>(0xd3487570u);
		FloatKeyFrames_Acceleration = ddl.GetObject<VisualEffectAccelerationKeyFrames>(0xdd3e607du);
		ExternalForces = ddl.GetObject<VisualEffectExternalForces>(0xc3ad64ffu);
		InputPort_PerfAttrOverrides = ddl.GetObject<VisualEffectPerfAttrOverride>(0xd24cc1bau);
		InputPort_LumAttrOverrides = ddl.GetObject<VisualEffectLumAttr>(0x548add56u);
		InputPort_CamAttrOverrides = ddl.GetObject<VisualEffectCamAttr>(0x147e4040u);
	}

	[DDLRegistration(0x872eed51u)]
	public RivetAssetId NodeId { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0x872eed51u)]
	public int XPos { get; set; } = 0;

	[DDLRegistration(0x872eed51u)]
	public int YPos { get; set; } = 0;

	[DDLRegistration(0x872eed51u, "Name")]
	public string? DisplayName { get; set; } = default;

	[DDLRegistration(0x872eed51u)]
	public List<VisualEffectNodeConnectedInputPort?> ConnectedInputs { get; set; } = [];

	[DDLRegistration(0x872eed51u)]
	public List<VisualEffectNodeConnectedOutputPort?> ConnectedOutputs { get; set; } = [];

	[DDLRegistration(0x872eed51u)]
	public bool Collapsed { get; set; } = true;

	[DDLRegistration(0x872eed51u)]
	public string? Type { get; set; } = default;

	[DDLRegistration(0x872eed51u)]
	public RenderStyle RenderStyle { get; set; } = RenderStyle.SingleQuad;

	[DDLRegistration(0x872eed51u, description: "Pick what platform this render node is active on")]
	public VisualEffectPlatforms? Platforms { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Editor Only", "When set to true, the render node will only display in the VFX editor")]
	public bool EditorOnly { get; set; } = false;

	[DDLRegistration(0x872eed51u)]
	public xfe5100b1 Space { get; set; } = xfe5100b1.Local;

	[DDLRegistration(0x872eed51u, "Render Attributes")]
	public RenderAttributes? RenderAttributes { get; set; } = default;

	[DDLRegistration(0x872eed51u, "ConduitVFXEvent", "Conduit event to generate")]
	public ConduitAttributes? ConduitAttributes { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Decal Trail Attributes")]
	public DecalTrailAttributes? DecalTrailAttributes { get; set; } = default;

	[DDLRegistration(0x872eed51u, "UV0 Tiling")]
	public UVTiling? UV0Tiling { get; set; } = default;

	[DDLRegistration(0x872eed51u, "UV1 Tiling")]
	public UVTiling? UV1Tiling { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Radial Blur")]
	public RadialBlurInfo? RadialBlur { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Transform")]
	public VisualEffectTransform? InputPort_Transform { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Lens Flare")]
	public VisualEffectLensFlare? InputPort_LensFlare { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Spherical Normal")]
	public VisualEffectFloat? InputPort_SphericalNormal { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Height")]
	public VisualEffectFloat? InputPort_Height { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Width")]
	public VisualEffectFloat? InputPort_Width { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Depth")]
	public VisualEffectFloat? InputPort_Depth { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Post Effect")]
	public PostEffect? PostEffect { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Spline Style")]
	public SplineStyle SplineStyle { get; set; } = SplineStyle.Standard;

	[DDLRegistration(0x872eed51u, "Beam Offset")]
	public DDLVector2? BeamOffset { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Trail/Swipe Attributes")]
	public TrailAttributes? TrailAttributes { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Swipe Scale Reference")]
	public SwipeScale SwipeScale { get; set; } = SwipeScale.Origin;

	[DDLRegistration(0x872eed51u, "Swipe Offset")]
	public DDLVector3? SwipeOffset { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Light Attributes")]
	public VisualEffectLightAttr? InputPort_LightAttr { get; set; } = default;

	[DDLRegistration(0x872eed51u, "LifeTime")]
	public VisualEffectMinMax? InputPort_LifeTime { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Spawn Delay")]
	public VisualEffectMinMax? InputPort_SpawnDelay { get; set; } = default;

	[DDLRegistration(0x872eed51u, "UV  Flips")]
	public SeparateUVFlips? UVFlips { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Luminance")]
	public VisualEffectFloatKeyFrames? FloatKeyFrames_Luminance { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Color")]
	public VisualEffectColorKeyFrames? ColorKeyFrames_Color { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Alpha")]
	public VisualEffectFloat2KeyFrames? Float2KeyFrames_Alpha { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Alpha Multiplier")]
	public VisualEffectFloatKeyFrames? FloatKeyFrames_AlphaMultiplier { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Rotation")]
	public VisualEffectRotationKeyFrames? Float3KeyFrames_Rotation { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Scales")]
	public VisualEffectFloat3KeyFrames? Float3KeyFrames_Scales { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Custom")]
	public VisualEffectFloat3KeyFrames? Float3KeyFrames_Custom { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Camera Offset")]
	public VisualEffectFloat? InputPort_CameraOffset { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Random Seed")]
	public VisualEffectFloat? InputPort_RandomSeed { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Force Field Attributes")]
	public ForceFieldAttributes? ForceFieldAttributes { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Turbulence Attributes")]
	public TurbulenceAttributes? TurbulenceAttributes { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Age Keyframe Override", "Use the age of the head particle to evaluate keyframes")]
	public TrailAgeKeyframe? TrailAgeKeyframe { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Decal Attributes")]
	public DecalAttributes? DecalAttributes { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Acceleration")]
	public VisualEffectAccelerationKeyFrames? FloatKeyFrames_Acceleration { get; set; } = default;

	[DDLRegistration(0x872eed51u, "External Forces")]
	public VisualEffectExternalForces? ExternalForces { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Performance Attributes")]
	public VisualEffectPerfAttrOverride? InputPort_PerfAttrOverrides { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Unlit Lighting Controls")]
	public VisualEffectLumAttr? InputPort_LumAttrOverrides { get; set; } = default;

	[DDLRegistration(0x872eed51u, "Camera Attributes")]
	public VisualEffectCamAttr? InputPort_CamAttrOverrides { get; set; } = default;

	public static VisualEffectRenderNode Create(DDLObject ddl) => new(ddl);
}

