// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x80f6608au)]
public class WeaponPickupAttachment : DDLObjectType, IDDLObjectType<WeaponPickupAttachment> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x80f6608au);

	public WeaponPickupAttachment(DDLObject ddl) : base(ddl) {
		Locator = ddl.GetString(0x7bac1d57) ?? Locator;
		OffsetFromLocator = ddl.GetObject<DDLVector3>(0xb1c76511u);
		PickupSpacing = ddl.GetObject<DDLVector3>(0x32272c38u);
	}

	[DDLRegistration(0x7bac1d57u, description: "Where to attach pickups to this weapon. Leave empty to use the weapon actor's root instead.")]
	public string? Locator { get; set; } = default;

	[DDLRegistration(0xb1c76511u, "Offset from Locator", "Offset from the locator to position the pickup. (in locator space)")]
	public DDLVector3? OffsetFromLocator { get; set; } = default;

	[DDLRegistration(0x32272c38u, "Pickup Spacing", "If multiple pickups are attached to the weapon, what kind of spacing should there be between each? (in locator space)")]
	public DDLVector3? PickupSpacing { get; set; } = default;

	public static WeaponPickupAttachment Create(DDLObject ddl) => new(ddl);
}

