// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.Models;
using Rivet.DDL.Enums;

[DDLRegistration(0x3bffe14du)]
public class ZoneInstantiatedEvent : EventBase, IDDLObjectType<ZoneInstantiatedEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x3bffe14du);

	public ZoneInstantiatedEvent(DDLObject ddl) : base(ddl) {
		ZoneId = ddl.GetValue<RivetAssetId>(0xc0e0f909u, ZoneId);
	}

	[DDLRegistration(0x3bffe14du)]
	public RivetAssetId ZoneId { get; set; } = new RivetAssetId(0x0000000000000000);

	public new static ZoneInstantiatedEvent Create(DDLObject ddl) => new(ddl);
}

