// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x4d5592abu)]
public class ActionControlConfirmationControl : DDLObjectType, IDDLObjectType<ActionControlConfirmationControl> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x4d5592abu);

	public ActionControlConfirmationControl(DDLObject ddl) : base(ddl) {
		Control = ddl.GetEnum<x93d78ad3>(0xec314f73u, x93d78ad3Values.Lookup);
	}

	[DDLRegistration(0xec314f73u)]
	public x93d78ad3 Control { get; set; } = x93d78ad3.ConfirmYes;

	public static ActionControlConfirmationControl Create(DDLObject ddl) => new(ddl);
}

