// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xf3b99ec5u)]
public class ActivityMetadataConfig : ConfigBase, IDDLObjectType<ActivityMetadataConfig> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xf3b99ec5u);

	public ActivityMetadataConfig(DDLObject ddl) : base(ddl) {
		SubCategories = ddl.GetObjects<ActivitySubCategoryInfo>(0x1546408eu);
		ArenaCheckpoint = ddl.GetString(0xc4ce3932) ?? ArenaCheckpoint;
		BronzeCup = ddl.GetObject<ArenaCupActivityData>(0x781fd602u);
		SilverCup = ddl.GetObject<ArenaCupActivityData>(0x13665853u);
		GoldenCup = ddl.GetObject<ArenaCupActivityData>(0x70f4091eu);
		RynoActivityData = ddl.GetObject<RynoActivityData>(0xbae9f85cu);
		FallbackSmallImage = ddl.GetValue<RivetAssetId>(0xc3541300u, FallbackSmallImage);
		FallbackLargeImage = ddl.GetValue<RivetAssetId>(0x24f9098bu, FallbackLargeImage);
	}

	[DDLRegistration(0x1546408eu)]
	public List<ActivitySubCategoryInfo?> SubCategories { get; set; } = [];

	[DDLRegistration(0xc4ce3932u, "Arena Game Intent Checkpoint", "Name of the checkpoint to warp to when triggered by game intent.")]
	public string? ArenaCheckpoint { get; set; } = default;

	[DDLRegistration(0x781fd602u)]
	public ArenaCupActivityData? BronzeCup { get; set; } = default;

	[DDLRegistration(0x13665853u)]
	public ArenaCupActivityData? SilverCup { get; set; } = default;

	[DDLRegistration(0x70f4091eu)]
	public ArenaCupActivityData? GoldenCup { get; set; } = default;

	[DDLRegistration(0xbae9f85cu)]
	public RynoActivityData? RynoActivityData { get; set; } = default;

	[DDLRegistration(0xc3541300u, "Fallback Small Image", "Path to a small image of size 864 x 1040 PNG 24-bit non-interlaced. This image will be shown on the card itself when no small image is defined for that card.")]
	public RivetAssetId FallbackSmallImage { get; set; } = default;

	[DDLRegistration(0x24f9098bu, "Fallback Large Image", "Path to a large image of size 3840 x 2160 PNG 24-bit non-interlaced. This image will be shown when the card is 'maximized' and no large image is defined for that card.")]
	public RivetAssetId FallbackLargeImage { get; set; } = default;

	public new static ActivityMetadataConfig Create(DDLObject ddl) => new(ddl);
}

