// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x0024db04u)]
public class ActorPositionNodeDef : ActorNodeBaseDef, IDDLObjectType<ActorPositionNodeDef> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x0024db04u);

	public ActorPositionNodeDef(DDLObject ddl) : base(ddl) {
		Actor = ddl.GetObject<InputPlugActor>(0x5d269a38u);
		Pos = ddl.GetObject<OutputPlugVec3>(0xaa8ccf65u);
	}

	[DDLRegistration(0x5d269a38u)]
	public InputPlugActor? Actor { get; set; } = default;

	[DDLRegistration(0xaa8ccf65u)]
	public OutputPlugVec3? Pos { get; set; } = default;

	public new static ActorPositionNodeDef Create(DDLObject ddl) => new(ddl);
}

