// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x0e1722c0u)]
public class AimAssistBoxProcessData : AimAssistCurveData, IDDLObjectType<AimAssistBoxProcessData> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x0e1722c0u);

	public AimAssistBoxProcessData(DDLObject ddl) : base(ddl) {
		BoxSlideFactor = ddl.GetValue<float>(0xe9abd634u, BoxSlideFactor);
	}

	[DDLRegistration(0xe9abd634u, "Slide Factor", "How much the Aim Assist Box around a target should slide towards the reticule as the reticule approaches the target.  Helps catch the player's reticule before reaching the target to improve feel/responsiveness.")]
	public float BoxSlideFactor { get; set; } = 0.50f;

	public new static AimAssistBoxProcessData Create(DDLObject ddl) => new(ddl);
}

