// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x05196c70u)]
public class AndOverlayOperatorPrius : BaseCustomOverlayTriggerPrius, IDDLObjectType<AndOverlayOperatorPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x05196c70u);

	public AndOverlayOperatorPrius(DDLObject ddl) : base(ddl) {
		Triggers = ddl.GetObjects<TriggerArray>(0xf4cf343du);
	}

	[DDLRegistration(0xf4cf343du, description: "All triggers in this array must be true for this And trigger to be true")]
	public List<TriggerArray?> Triggers { get; set; } = [];

	public new static AndOverlayOperatorPrius Create(DDLObject ddl) => new(ddl);
}

