// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xb4506392u)]
public class AnimDamageAttackStylePrim : AnimDamageAttackStyleBase, IDDLObjectType<AnimDamageAttackStylePrim> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xb4506392u);

	public AnimDamageAttackStylePrim(DDLObject ddl) : base(ddl) {
		PrimType = ddl.GetEnum<xaabf8cd7>(0x0b75f8eeu, xaabf8cd7Values.Lookup);
		DamageJoint = ddl.GetString(0x0520e489) ?? DamageJoint;
		LocalOffset = ddl.GetObject<DDLVector3>(0x46a4eea5u);
		DamageJointSecondary = ddl.GetString(0x2db7d7b8) ?? DamageJointSecondary;
		LocalOffsetSecondary = ddl.GetObject<DDLVector3>(0x2d270ce4u);
		SweepFromLastPosition = ddl.GetValue<bool>(0x192a2205u, SweepFromLastPosition);
		DamageRadius = ddl.GetValue<float>(0xe3e6fa68u, DamageRadius);
		LerpRadius = ddl.GetValue<bool>(0x6a9c9a53u, LerpRadius);
		DamagePrimLength = ddl.GetValue<float>(0xdb9a6d43u, DamagePrimLength);
		LerpLength = ddl.GetValue<bool>(0x509d6abbu, LerpLength);
		DamageType = ddl.GetEnum<DamageTypesGame>(0x840c154du, DamageTypesGameValues.Lookup);
		DamageAmount = ddl.GetValue<float>(0x563be470u, DamageAmount);
		ArmorPassThroughPercentage = ddl.GetValue<float>(0x0cea0f4fu, ArmorPassThroughPercentage);
		Knockback = ddl.GetEnum<KnockbackLevels>(0x2e553fddu, KnockbackLevelsValues.Lookup);
		KnockbackAmount = ddl.GetValue<float>(0x7b1e600bu, KnockbackAmount);
		KnockbackForce = ddl.GetValue<float>(0x28d6ed59u, KnockbackForce);
		FriendlyKnockback = ddl.GetValue<bool>(0x776e0c27u, FriendlyKnockback);
		Condition = ddl.GetEnum<x257872aa>(0x3f2b174fu, x257872aaValues.Lookup);
		ConditionDuration = ddl.GetValue<float>(0x06d5955cu, ConditionDuration);
		StatusAmount = ddl.GetValue<float>(0x37e1f098u, StatusAmount);
		DurationOverride = ddl.GetValue<float>(0x0bb3cda6u, DurationOverride);
		HitPauseTime = ddl.GetValue<float>(0xa0fb18acu, HitPauseTime);
		RequestFlags = ddl.GetBitset<DamageRequestFlags>(0x2bc801dfu, DamageRequestFlagsValues.Lookup);
	}

	[DDLRegistration(0x0b75f8eeu, "Prim Type")]
	public xaabf8cd7 PrimType { get; set; } = xaabf8cd7.Sphere;

	[DDLRegistration(0x0520e489u, "Primary Locator")]
	public string? DamageJoint { get; set; } = default;

	[DDLRegistration(0x46a4eea5u, "Local Offset", "This is an offset in model space.")]
	public DDLVector3? LocalOffset { get; set; } = default;

	[DDLRegistration(0x2db7d7b8u, "Secondary Locator")]
	public string? DamageJointSecondary { get; set; } = default;

	[DDLRegistration(0x2d270ce4u, "Secondary Local Offset", "This is an offset in model space.")]
	public DDLVector3? LocalOffsetSecondary { get; set; } = default;

	[DDLRegistration(0x192a2205u, "Sweep From Last Position", "Do line/swept-sphere checks from last damage position to current position, instead of doing it from Primary to Secondary Locators.")]
	public bool SweepFromLastPosition { get; set; } = false;

	[DDLRegistration(0xe3e6fa68u, "Damage Radius")]
	public float DamageRadius { get; set; } = 1.00f;

	[DDLRegistration(0x6a9c9a53u, "Lerp Radius", "Lerp the damage radius from 0 - Damag eRadius based on Primary Locator's z-axis")]
	public bool LerpRadius { get; set; } = false;

	[DDLRegistration(0xdb9a6d43u, "Prim Length", "How long the line or swept sphere is if there is no Secondary Locator.")]
	public float DamagePrimLength { get; set; } = 1.00f;

	[DDLRegistration(0x509d6abbu, "Lerp Length", "Lerp the damage length from 0 - Prim Length based on Primary Locator's x-axis")]
	public bool LerpLength { get; set; } = false;

	[DDLRegistration(0x840c154du, "Damage Type")]
	public DamageTypesGame DamageType { get; set; } = DamageTypesGame.Melee;

	[DDLRegistration(0x563be470u, "Damage Amount")]
	public float DamageAmount { get; set; } = 1.00f;

	[DDLRegistration(0x0cea0f4fu, "Armor Pass-Through")]
	public float ArmorPassThroughPercentage { get; set; } = 0.00f;

	[DDLRegistration(0x2e553fddu)]
	public KnockbackLevels Knockback { get; set; } = KnockbackLevels.None;

	[DDLRegistration(0x7b1e600bu)]
	public float KnockbackAmount { get; set; } = -1.00f;

	[DDLRegistration(0x28d6ed59u)]
	public float KnockbackForce { get; set; } = -1.00f;

	[DDLRegistration(0x776e0c27u, description: "Should this attack knock around friendlies even if it doens't hurt them")]
	public bool FriendlyKnockback { get; set; } = false;

	[DDLRegistration(0x3f2b174fu)]
	public x257872aa Condition { get; set; } = x257872aa.None;

	[DDLRegistration(0x06d5955cu)]
	public float ConditionDuration { get; set; } = 2.50f;

	[DDLRegistration(0x37e1f098u)]
	public float StatusAmount { get; set; } = 0.00f;

	[DDLRegistration(0x0bb3cda6u, "Duration Override")]
	public float DurationOverride { get; set; } = 0.00f;

	[DDLRegistration(0xa0fb18acu, "Hit Pause Time")]
	public float HitPauseTime { get; set; } = -1.00f;

	[DDLRegistration(0x2bc801dfu)]
	public DamageRequestFlags RequestFlags { get; set; } = (DamageRequestFlags) 0x00000000;

	public new static AnimDamageAttackStylePrim Create(DDLObject ddl) => new(ddl);
}

