// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x8da8290cu)]
public class AnimDriverSequenceNodeDef : DDLObjectType, IDDLObjectType<AnimDriverSequenceNodeDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x8da8290cu);

	public AnimDriverSequenceNodeDef(DDLObject ddl) : base(ddl) {
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		DisplayName = ddl.GetString(0xeaf33243) ?? DisplayName;
		X = ddl.GetValue<float>(0x655d6145u, X);
		Y = ddl.GetValue<float>(0x125a51d3u, Y);
		Type = ddl.GetEnum<xe5615bda>(0xbc4e9799u, xe5615bdaValues.Lookup);
		Rate = ddl.GetValue<float>(0xef7cff89u, Rate);
		Time = ddl.GetValue<float>(0x5f0458f5u, Time);
		Overlap = ddl.GetValue<float>(0xc1c9e722u, Overlap);
		Connections = ddl.GetObjects<AnimDriverConnectionDef>(0x322aadceu);
	}

	[DDLRegistration(0x6eb3beb6u)]
	public string? Name { get; set; } = default;

	[DDLRegistration(0xeaf33243u)]
	public string? DisplayName { get; set; } = "";

	[DDLRegistration(0x655d6145u)]
	public float X { get; set; } = 0.00f;

	[DDLRegistration(0x125a51d3u)]
	public float Y { get; set; } = 0.00f;

	[DDLRegistration(0xbc4e9799u)]
	public xe5615bda Type { get; set; } = xe5615bda.SequenceNodeTypeDefault;

	[DDLRegistration(0xef7cff89u)]
	public float Rate { get; set; } = 1.00f;

	[DDLRegistration(0x5f0458f5u)]
	public float Time { get; set; } = 0.00f;

	[DDLRegistration(0xc1c9e722u)]
	public float Overlap { get; set; } = 0.00f;

	[DDLRegistration(0x322aadceu)]
	public List<AnimDriverConnectionDef?> Connections { get; set; } = [];

	public static AnimDriverSequenceNodeDef Create(DDLObject ddl) => new(ddl);
}

