// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x5264054au)]
public class AnimDriverVarDef : DDLObjectType, IDDLObjectType<AnimDriverVarDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x5264054au);

	public AnimDriverVarDef(DDLObject ddl) : base(ddl) {
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		X = ddl.GetValue<float>(0x655d6145u, X);
		Y = ddl.GetValue<float>(0x125a51d3u, Y);
		Type = ddl.GetEnum<xdf8f8d7a>(0xbc4e9799u, xdf8f8d7aValues.Lookup);
		Connections = ddl.GetObjects<AnimDriverVarConnection>(0x322aadceu);
	}

	[DDLRegistration(0x6eb3beb6u)]
	public string? Name { get; set; } = default;

	[DDLRegistration(0x655d6145u)]
	public float X { get; set; } = 0.00f;

	[DDLRegistration(0x125a51d3u)]
	public float Y { get; set; } = 0.00f;

	[DDLRegistration(0xbc4e9799u)]
	public xdf8f8d7a Type { get; set; } = xdf8f8d7a.FloatOutput;

	[DDLRegistration(0x322aadceu)]
	public List<AnimDriverVarConnection?> Connections { get; set; } = [];

	public static AnimDriverVarDef Create(DDLObject ddl) => new(ddl);
}

