// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xf3b1e1a6u)]
public class AnimCompleteAutoEvent : EventBase, IDDLObjectType<AnimCompleteAutoEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xf3b1e1a6u);

	public AnimCompleteAutoEvent(DDLObject ddl) : base(ddl) {
		AnimDriverNameHash = ddl.GetValue<uint>(0xcbef3f39u, AnimDriverNameHash);
	}

	[DDLRegistration(0xcbef3f39u, description: "Hash of the anim driver's name that has completed.")]
	public uint AnimDriverNameHash { get; set; } = 0x00000000;

	public new static AnimCompleteAutoEvent Create(DDLObject ddl) => new(ddl);
}

