// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xd293eb88u)]
public class AnimDriverTransitionEvent : EventBase, IDDLObjectType<AnimDriverTransitionEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xd293eb88u);

	public AnimDriverTransitionEvent(DDLObject ddl) : base(ddl) {
		LayerId = ddl.GetValue<uint>(0xd7132e94u, LayerId);
		PrevDriver = ddl.GetString(0xa01bcb06) ?? PrevDriver;
		NextDriver = ddl.GetString(0x21fc6036) ?? NextDriver;
	}

	[DDLRegistration(0xd7132e94u, "Layer Id", "Id of the layer whose active driver was changed.")]
	public uint LayerId { get; set; } = 0x00000000;

	[DDLRegistration(0xa01bcb06u, "Previous Driver", "Name of the driver on this layer that just got deactivated. Empty if there was no previous driver for this layer.")]
	public string? PrevDriver { get; set; } = default;

	[DDLRegistration(0x21fc6036u, "Next Driver", "Name of the driver on this layer that just got activated. Empty if there is no new driver (i.e. the layer deactivated)")]
	public string? NextDriver { get; set; } = default;

	public new static AnimDriverTransitionEvent Create(DDLObject ddl) => new(ddl);
}

