// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x283fba77u)]
public class AOEWaterHazardExplosionEvent : EventBase, IDDLObjectType<AOEWaterHazardExplosionEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x283fba77u);

	public AOEWaterHazardExplosionEvent(DDLObject ddl) : base(ddl) { }

	public new static AOEWaterHazardExplosionEvent Create(DDLObject ddl) => new(ddl);
}

