// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xafc2f617u)]
public class AssetMigrationDef : DDLObjectType, IDDLObjectType<AssetMigrationDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xafc2f617u);

	public AssetMigrationDef(DDLObject ddl) : base(ddl) {
		Host = ddl.GetString(0xffb7d34d) ?? Host;
		Port = ddl.GetString(0x73019d7c) ?? Port;
		Extensions = ddl.GetStrings(0x0ec6c290u);
		Projects = ddl.GetObjects<AssetMigrationProject>(0xa6920ed4u);
	}

	[DDLRegistration(0xffb7d34du)]
	public string? Host { get; set; } = default;

	[DDLRegistration(0x73019d7cu)]
	public string? Port { get; set; } = default;

	[DDLRegistration(0x0ec6c290u)]
	public List<string?> Extensions { get; set; } = [];

	[DDLRegistration(0xa6920ed4u)]
	public List<AssetMigrationProject?> Projects { get; set; } = [];

	public static AssetMigrationDef Create(DDLObject ddl) => new(ddl);
}

