// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x785b9296u)]
public class AudioBusMaterialStartListeningEvent : EventBase, IDDLObjectType<AudioBusMaterialStartListeningEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x785b9296u);

	public AudioBusMaterialStartListeningEvent(DDLObject ddl) : base(ddl) { }

	public new static AudioBusMaterialStartListeningEvent Create(DDLObject ddl) => new(ddl);
}

