// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x4f187eb0u)]
public class AuthFailureDevstatsEvent : EventBase, IDDLObjectType<AuthFailureDevstatsEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x4f187eb0u);

	public AuthFailureDevstatsEvent(DDLObject ddl) : base(ddl) {
		ID = ddl.GetString(0xb13f6a45) ?? ID;
	}

	[DDLRegistration(0xb13f6a45u)]
	public string? ID { get; set; } = default;

	public new static AuthFailureDevstatsEvent Create(DDLObject ddl) => new(ddl);
}

