// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x4a4a9e1fu)]
public class AwardEntry : DDLObjectType, IDDLObjectType<AwardEntry> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x4a4a9e1fu);

	public AwardEntry(DDLObject ddl) : base(ddl) {
		Award = ddl.GetObject<AwardBasePrius>(0x9308e226u);
	}

	[DDLRegistration(0x9308e226u, description: "Contains information about how to track progress towards this award.")]
	public AwardBasePrius? Award { get; set; } = default;

	public static AwardEntry Create(DDLObject ddl) => new(ddl);
}

