// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xc4483ad1u)]
public class BeamOutConfig : IncinerateConfig, IDDLObjectType<BeamOutConfig> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xc4483ad1u);

	public BeamOutConfig(DDLObject ddl) : base(ddl) {
		SourceJoint = ddl.GetString(0x8d47f7c0) ?? SourceJoint;
	}

	[DDLRegistration(0x8d47f7c0u)]
	public string? SourceJoint { get; set; } = default;

	public new static BeamOutConfig Create(DDLObject ddl) => new(ddl);
}

