// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x47d9134bu)]
public class BeginRotationEvent : EventBase, IDDLObjectType<BeginRotationEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x47d9134bu);

	public BeginRotationEvent(DDLObject ddl) : base(ddl) { }

	public new static BeginRotationEvent Create(DDLObject ddl) => new(ddl);
}

