// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x3a9c2ad0u)]
public class BossBotNefariousFinalePrius : BotPrius, IDDLObjectType<BossBotNefariousFinalePrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x3a9c2ad0u);

	public BossBotNefariousFinalePrius(DDLObject ddl) : base(ddl) {
		AllowCelebrates = ddl.GetValue<bool>(0x6a3ad847u, AllowCelebrates);
		HoverShuffleData = ddl.GetObject<HoverShuffleData>(0x5d8cb773u);
		UseFirepointFacingForShuffle = ddl.GetValue<bool>(0xafd04b08u, UseFirepointFacingForShuffle);
		EmpNefariousPilotAsset = ddl.GetValue<RivetAssetId>(0x4fbfd7c8u, EmpNefariousPilotAsset);
		DocNefariousPilotAsset = ddl.GetValue<RivetAssetId>(0xf33c549au, DocNefariousPilotAsset);
		DamageStates_Eye_LF = ddl.GetValue<RivetAssetId>(0xff454979u, DamageStates_Eye_LF);
		DamageStates_Eye_RT = ddl.GetValue<RivetAssetId>(0xd8bd07eeu, DamageStates_Eye_RT);
		DamageStates_Arm_LF = ddl.GetValue<RivetAssetId>(0xd6b01291u, DamageStates_Arm_LF);
		DamageStates_Arm_RT = ddl.GetValue<RivetAssetId>(0xf1485c06u, DamageStates_Arm_RT);
	}

	[DDLRegistration(0x6a3ad847u)]
	public bool AllowCelebrates { get; set; } = true;

	[DDLRegistration(0x5d8cb773u)]
	public HoverShuffleData? HoverShuffleData { get; set; } = default;

	[DDLRegistration(0xafd04b08u)]
	public bool UseFirepointFacingForShuffle { get; set; } = false;

	[DDLRegistration(0x4fbfd7c8u)]
	public RivetAssetId EmpNefariousPilotAsset { get; set; } = default;

	[DDLRegistration(0xf33c549au)]
	public RivetAssetId DocNefariousPilotAsset { get; set; } = default;

	[DDLRegistration(0xff454979u, description: "Type: Damage State Manager Config")]
	public RivetAssetId DamageStates_Eye_LF { get; set; } = default;

	[DDLRegistration(0xd8bd07eeu, description: "Type: Damage State Manager Config")]
	public RivetAssetId DamageStates_Eye_RT { get; set; } = default;

	[DDLRegistration(0xd6b01291u, description: "Type: Damage State Manager Config")]
	public RivetAssetId DamageStates_Arm_LF { get; set; } = default;

	[DDLRegistration(0xf1485c06u, description: "Type: Damage State Manager Config")]
	public RivetAssetId DamageStates_Arm_RT { get; set; } = default;

	public new static BossBotNefariousFinalePrius Create(DDLObject ddl) => new(ddl);
}

