// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xa36ed144u)]
public class BotConfigAnimFilterSelector : ConfigBase, IDDLObjectType<BotConfigAnimFilterSelector> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xa36ed144u);

	public BotConfigAnimFilterSelector(DDLObject ddl) : base(ddl) {
		Data = ddl.GetObject<BotAnimFilterSelectorData>(0x9d6333d3u);
	}

	[DDLRegistration(0x9d6333d3u)]
	public BotAnimFilterSelectorData? Data { get; set; } = default;

	public new static BotConfigAnimFilterSelector Create(DDLObject ddl) => new(ddl);
}

