// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x8c4df813u)]
public class BotCommandZordoomCisternJumpActionPrius : DDLObjectType, IDDLObjectType<BotCommandZordoomCisternJumpActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x8c4df813u);

	public BotCommandZordoomCisternJumpActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		Anim = ddl.GetString(0x573ba4eb) ?? Anim;
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Boss;

	[DDLRegistration(0x573ba4ebu, description: "Name of the driver that the bot should play. This anim will be motion scaled to cover the full distance.")]
	public string? Anim { get; set; } = default;

	public static BotCommandZordoomCisternJumpActionPrius Create(DDLObject ddl) => new(ddl);
}

