// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xd165f780u)]
public class BotCommandShooterAttackTargetScriptActionPrius : DDLObjectType, IDDLObjectType<BotCommandShooterAttackTargetScriptActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xd165f780u);

	public BotCommandShooterAttackTargetScriptActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.EnemyBot;

	public static BotCommandShooterAttackTargetScriptActionPrius Create(DDLObject ddl) => new(ddl);
}

