// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x97d1bf43u)]
public class BotOnTranslationCancelEvent : EventBase, IDDLObjectType<BotOnTranslationCancelEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x97d1bf43u);

	public BotOnTranslationCancelEvent(DDLObject ddl) : base(ddl) {
		TargetHandle = ddl.GetValue<uint>(0x63316affu, TargetHandle);
	}

	[DDLRegistration(0x63316affu)]
	public uint TargetHandle { get; set; } = 0x00000000;

	public new static BotOnTranslationCancelEvent Create(DDLObject ddl) => new(ddl);
}

