// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x97d753e4u)]
public class CameraSplineMotionPathFollowPrius : CameraSplineMotionBasePrius, IDDLObjectType<CameraSplineMotionPathFollowPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x97d753e4u);

	public CameraSplineMotionPathFollowPrius(DDLObject ddl) : base(ddl) {
		TravelForward = ddl.GetValue<bool>(0xcccca932u, TravelForward);
	}

	[DDLRegistration(0xcccca932u, "Travel Forward")]
	public bool TravelForward { get; set; } = true;

	public new static CameraSplineMotionPathFollowPrius Create(DDLObject ddl) => new(ddl);
}

