// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xe078469du)]
public class CameraSplineMotionProximityPrius : CameraSplineMotionBasePrius, IDDLObjectType<CameraSplineMotionProximityPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xe078469du);

	public CameraSplineMotionProximityPrius(DDLObject ddl) : base(ddl) {
		ProximityTarget = ddl.GetValue<RivetAssetId>(0x8c0b1736u, ProximityTarget);
		OffsetDistance = ddl.GetValue<float>(0x4d543176u, OffsetDistance);
		OffsetPath = ddl.GetValue<RivetAssetId>(0x2264d1ddu, OffsetPath);
		OffsetAccel = ddl.GetValue<float>(0xe70a5acau, OffsetAccel);
		OffsetDecel = ddl.GetValue<float>(0x0a818a66u, OffsetDecel);
		OffsetSpeed = ddl.GetValue<float>(0xb5d092d9u, OffsetSpeed);
	}

	[DDLRegistration(0x8c0b1736u, "Proximity Target")]
	public RivetAssetId ProximityTarget { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0x4d543176u, "Offset Distance")]
	public float OffsetDistance { get; set; } = 0.00f;

	[DDLRegistration(0x2264d1ddu, "Offset Path")]
	public RivetAssetId OffsetPath { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0xe70a5acau, "Offset Accel")]
	public float OffsetAccel { get; set; } = 10.00f;

	[DDLRegistration(0x0a818a66u, "Offset Decel")]
	public float OffsetDecel { get; set; } = 5.00f;

	[DDLRegistration(0xb5d092d9u, "Offset Speed")]
	public float OffsetSpeed { get; set; } = 5.00f;

	public new static CameraSplineMotionProximityPrius Create(DDLObject ddl) => new(ddl);
}

