// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xefa7bd02u)]
public class CanceledEvent : EventBase, IDDLObjectType<CanceledEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xefa7bd02u);

	public CanceledEvent(DDLObject ddl) : base(ddl) { }

	public new static CanceledEvent Create(DDLObject ddl) => new(ddl);
}

