// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xca8bf775u)]
public class CaptureGridInfo2 : DDLObjectType, IDDLObjectType<CaptureGridInfo2> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xca8bf775u);

	public CaptureGridInfo2(DDLObject ddl) : base(ddl) {
		LightbinFullPath = ddl.GetValue<RivetAssetId>(0xd4afead4u, LightbinFullPath);
		GBufferPath = ddl.GetValue<RivetAssetId>(0x10243403u, GBufferPath);
		Position = ddl.GetObject<DDLVector3>(0xbc2d5985u);
	}

	[DDLRegistration(0xd4afead4u)]
	public RivetAssetId LightbinFullPath { get; set; } = default;

	[DDLRegistration(0x10243403u)]
	public RivetAssetId GBufferPath { get; set; } = default;

	[DDLRegistration(0xbc2d5985u)]
	public DDLVector3? Position { get; set; } = default;

	public static CaptureGridInfo2 Create(DDLObject ddl) => new(ddl);
}

