// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x125b33f6u)]
public class CarpetBomberShellPopOffEvent : EventBase, IDDLObjectType<CarpetBomberShellPopOffEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x125b33f6u);

	public CarpetBomberShellPopOffEvent(DDLObject ddl) : base(ddl) { }

	public new static CarpetBomberShellPopOffEvent Create(DDLObject ddl) => new(ddl);
}

