// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x2e6f0680u)]
public class Cinematic2CameraOrphanTrackDef : DDLObjectType, IDDLObjectType<Cinematic2CameraOrphanTrackDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x2e6f0680u);

	public Cinematic2CameraOrphanTrackDef(DDLObject ddl) : base(ddl) {
		Id = ddl.GetValue<RivetAssetId>(0x8a514a8du, Id);
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		PlatformFilter = ddl.GetBitset<xb52df7e7>(0x92542397u, xb52df7e7Values.Lookup);
		Tags = ddl.GetObject<Cinematic2TrackTagsDef>(0x5f2c5496u);
		Global = ddl.GetValue<bool>(0xd67dc5e4u, Global);
		PlayAnimActions = ddl.GetDictionary<RivetAssetId, Cinematic2BehaviorPlayAnimClipActionDef>(0x2a95c808, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2BehaviorPlayAnimClipActionDef>(mapId));
		BehaviorGoToActions = ddl.GetDictionary<RivetAssetId, Cinematic2BehaviorGoToActionDef>(0x1a0c8f02, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2BehaviorGoToActionDef>(mapId));
		PlayDriverActions = ddl.GetDictionary<RivetAssetId, Cinematic2BehaviorPlayDriverActionDef>(0x0f706a76, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2BehaviorPlayDriverActionDef>(mapId));
		DialogActions = ddl.GetDictionary<RivetAssetId, Cinematic2DialogActionDef>(0x1f501f9a, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2DialogActionDef>(mapId));
		LookAtActions = ddl.GetDictionary<RivetAssetId, Cinematic2LookAtActionDef>(0xa2c33691, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2LookAtActionDef>(mapId));
		BlinkActions = ddl.GetDictionary<RivetAssetId, Cinematic2BlinkActionDef>(0x45b7d6eb, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2BlinkActionDef>(mapId));
		MovieActions = ddl.GetDictionary<RivetAssetId, Cinematic2MovieActionDef>(0x098f8a05, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2MovieActionDef>(mapId));
		AtmosphereActions = ddl.GetDictionary<RivetAssetId, Cinematic2AtmosphereActionDef>(0xf4cfc0ee, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2AtmosphereActionDef>(mapId));
		AudioActions = ddl.GetDictionary<RivetAssetId, Cinematic2AudioActionDef>(0xf24716d6, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2AudioActionDef>(mapId));
		AudioGameSyncGroupActions = ddl.GetDictionary<RivetAssetId, Cinematic2AudioGameSyncGroupActionDef>(0xda497481, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2AudioGameSyncGroupActionDef>(mapId));
		AudioGameSyncActions = ddl.GetDictionary<RivetAssetId, Cinematic2AudioGameSyncActionDef>(0xa2a94853, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2AudioGameSyncActionDef>(mapId));
		FollowActions = ddl.GetDictionary<RivetAssetId, Cinematic2CameraDofFollowActionDef>(0x271e731d, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2CameraDofFollowActionDef>(mapId));
		HideActions = ddl.GetDictionary<RivetAssetId, Cinematic2HideActionDef>(0xefa3d18a, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2HideActionDef>(mapId));
		TextureOverrideActions = ddl.GetDictionary<RivetAssetId, Cinematic2MaterialOverrideTextureActionDef>(0xd5e966f9, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2MaterialOverrideTextureActionDef>(mapId));
		MaterialOverrideActions = ddl.GetDictionary<RivetAssetId, Cinematic2MaterialOverrideMaterialActionDef>(0xd3e6413c, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2MaterialOverrideMaterialActionDef>(mapId));
		PreCompositeMaterialActions = ddl.GetDictionary<RivetAssetId, Cinematic2PreCompositeMaterialActionDef>(0x2ebd96a8, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2PreCompositeMaterialActionDef>(mapId));
		PostCompositeMaterialActions = ddl.GetDictionary<RivetAssetId, Cinematic2PostCompositeMaterialActionDef>(0x874a8f12, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2PostCompositeMaterialActionDef>(mapId));
		SyncActions = ddl.GetDictionary<RivetAssetId, Cinematic2SyncActionDef>(0x169b90f4, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2SyncActionDef>(mapId));
		VfxActions = ddl.GetDictionary<RivetAssetId, Cinematic2VfxActionDef>(0xc4bea696, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2VfxActionDef>(mapId));
		LightAttachActions = ddl.GetDictionary<RivetAssetId, Cinematic2LightAttachActionDef>(0x920a6fd9, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2LightAttachActionDef>(mapId));
		Events = ddl.GetDictionary<RivetAssetId, AnimTriggerEventDef>(0x6dff192d, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<AnimTriggerEventDef>(mapId));
		CharacterActions = ddl.GetDictionary<RivetAssetId, Cinematic2CharacterLookActionDef>(0xd18c17a3, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2CharacterLookActionDef>(mapId));
		OptInActions = ddl.GetDictionary<RivetAssetId, Cinematic2OptInLookActionDef>(0x03d46a5f, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2OptInLookActionDef>(mapId));
		ToggleLookActions = ddl.GetDictionary<RivetAssetId, Cinematic2ToggleLookActionDef>(0x9134f197, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2ToggleLookActionDef>(mapId));
		ToggleGroupActions = ddl.GetDictionary<RivetAssetId, Cinematic2ToggleLookGroupActionDef>(0x9b27e500, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2ToggleLookGroupActionDef>(mapId));
		ApplyGroupActions = ddl.GetDictionary<RivetAssetId, Cinematic2ApplyLookGroupActionDef>(0xb55ca35c, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2ApplyLookGroupActionDef>(mapId));
		TagActions = ddl.GetDictionary<RivetAssetId, Cinematic2TagActionDef>(0x01b138e5, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2TagActionDef>(mapId));
		WindActions = ddl.GetDictionary<RivetAssetId, Cinematic2WindActionDef>(0x8b296b87, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2WindActionDef>(mapId));
		TextureActions = ddl.GetDictionary<RivetAssetId, Cinematic2TextureActionDef>(0x0ee61756, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<Cinematic2TextureActionDef>(mapId));
	}

	[DDLRegistration(0x8a514a8du)]
	public RivetAssetId Id { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0x6eb3beb6u)]
	public string? Name { get; set; } = default;

	[DDLRegistration(0x92542397u, description: "Track will only run on the defined platform(s)")]
	public xb52df7e7 PlatformFilter { get; set; } = (xb52df7e7) 0x00000007;

	[DDLRegistration(0x5f2c5496u, description: "A set of gameplay-defined values to determine if this track should be processed.")]
	public Cinematic2TrackTagsDef? Tags { get; set; } = default;

	[DDLRegistration(0xd67dc5e4u, description: "If set to true, actions on this track will not move when shots are reordered.")]
	public bool Global { get; set; } = false;

	[DDLRegistration(0x2a95c808u)]
	public Dictionary<RivetAssetId, Cinematic2BehaviorPlayAnimClipActionDef?> PlayAnimActions { get; set; } = [];

	[DDLRegistration(0x1a0c8f02u)]
	public Dictionary<RivetAssetId, Cinematic2BehaviorGoToActionDef?> BehaviorGoToActions { get; set; } = [];

	[DDLRegistration(0x0f706a76u)]
	public Dictionary<RivetAssetId, Cinematic2BehaviorPlayDriverActionDef?> PlayDriverActions { get; set; } = [];

	[DDLRegistration(0x1f501f9au)]
	public Dictionary<RivetAssetId, Cinematic2DialogActionDef?> DialogActions { get; set; } = [];

	[DDLRegistration(0xa2c33691u)]
	public Dictionary<RivetAssetId, Cinematic2LookAtActionDef?> LookAtActions { get; set; } = [];

	[DDLRegistration(0x45b7d6ebu)]
	public Dictionary<RivetAssetId, Cinematic2BlinkActionDef?> BlinkActions { get; set; } = [];

	[DDLRegistration(0x098f8a05u)]
	public Dictionary<RivetAssetId, Cinematic2MovieActionDef?> MovieActions { get; set; } = [];

	[DDLRegistration(0xf4cfc0eeu)]
	public Dictionary<RivetAssetId, Cinematic2AtmosphereActionDef?> AtmosphereActions { get; set; } = [];

	[DDLRegistration(0xf24716d6u)]
	public Dictionary<RivetAssetId, Cinematic2AudioActionDef?> AudioActions { get; set; } = [];

	[DDLRegistration(0xda497481u)]
	public Dictionary<RivetAssetId, Cinematic2AudioGameSyncGroupActionDef?> AudioGameSyncGroupActions { get; set; } = [];

	[DDLRegistration(0xa2a94853u)]
	public Dictionary<RivetAssetId, Cinematic2AudioGameSyncActionDef?> AudioGameSyncActions { get; set; } = [];

	[DDLRegistration(0x271e731du)]
	public Dictionary<RivetAssetId, Cinematic2CameraDofFollowActionDef?> FollowActions { get; set; } = [];

	[DDLRegistration(0xefa3d18au)]
	public Dictionary<RivetAssetId, Cinematic2HideActionDef?> HideActions { get; set; } = [];

	[DDLRegistration(0xd5e966f9u)]
	public Dictionary<RivetAssetId, Cinematic2MaterialOverrideTextureActionDef?> TextureOverrideActions { get; set; } = [];

	[DDLRegistration(0xd3e6413cu)]
	public Dictionary<RivetAssetId, Cinematic2MaterialOverrideMaterialActionDef?> MaterialOverrideActions { get; set; } = [];

	[DDLRegistration(0x2ebd96a8u)]
	public Dictionary<RivetAssetId, Cinematic2PreCompositeMaterialActionDef?> PreCompositeMaterialActions { get; set; } = [];

	[DDLRegistration(0x874a8f12u)]
	public Dictionary<RivetAssetId, Cinematic2PostCompositeMaterialActionDef?> PostCompositeMaterialActions { get; set; } = [];

	[DDLRegistration(0x169b90f4u)]
	public Dictionary<RivetAssetId, Cinematic2SyncActionDef?> SyncActions { get; set; } = [];

	[DDLRegistration(0xc4bea696u)]
	public Dictionary<RivetAssetId, Cinematic2VfxActionDef?> VfxActions { get; set; } = [];

	[DDLRegistration(0x920a6fd9u)]
	public Dictionary<RivetAssetId, Cinematic2LightAttachActionDef?> LightAttachActions { get; set; } = [];

	[DDLRegistration(0x6dff192du)]
	public Dictionary<RivetAssetId, AnimTriggerEventDef?> Events { get; set; } = [];

	[DDLRegistration(0xd18c17a3u)]
	public Dictionary<RivetAssetId, Cinematic2CharacterLookActionDef?> CharacterActions { get; set; } = [];

	[DDLRegistration(0x03d46a5fu)]
	public Dictionary<RivetAssetId, Cinematic2OptInLookActionDef?> OptInActions { get; set; } = [];

	[DDLRegistration(0x9134f197u)]
	public Dictionary<RivetAssetId, Cinematic2ToggleLookActionDef?> ToggleLookActions { get; set; } = [];

	[DDLRegistration(0x9b27e500u)]
	public Dictionary<RivetAssetId, Cinematic2ToggleLookGroupActionDef?> ToggleGroupActions { get; set; } = [];

	[DDLRegistration(0xb55ca35cu)]
	public Dictionary<RivetAssetId, Cinematic2ApplyLookGroupActionDef?> ApplyGroupActions { get; set; } = [];

	[DDLRegistration(0x01b138e5u)]
	public Dictionary<RivetAssetId, Cinematic2TagActionDef?> TagActions { get; set; } = [];

	[DDLRegistration(0x8b296b87u)]
	public Dictionary<RivetAssetId, Cinematic2WindActionDef?> WindActions { get; set; } = [];

	[DDLRegistration(0x0ee61756u)]
	public Dictionary<RivetAssetId, Cinematic2TextureActionDef?> TextureActions { get; set; } = [];

	public static Cinematic2CameraOrphanTrackDef Create(DDLObject ddl) => new(ddl);
}

