// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x4ec592e3u)]
public class CinematicExitFreezeCameraEvent : EventBase, IDDLObjectType<CinematicExitFreezeCameraEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x4ec592e3u);

	public CinematicExitFreezeCameraEvent(DDLObject ddl) : base(ddl) {
		FreezeTime = ddl.GetValue<float>(0x6e1c5a4bu, FreezeTime);
		FreezeMoveDistance = ddl.GetValue<float>(0x87c82301u, FreezeMoveDistance);
		AllowInputBreak = ddl.GetValue<bool>(0xef615b9du, AllowInputBreak);
	}

	[DDLRegistration(0x6e1c5a4bu, description: "Time to stay in-place before going to gameplay")]
	public float FreezeTime { get; set; } = 0.25f;

	[DDLRegistration(0x87c82301u, description: "Distance hero must move before camera blends out")]
	public float FreezeMoveDistance { get; set; } = 0.00f;

	[DDLRegistration(0xef615b9du, description: "Allow camera stick input to break the freeze")]
	public bool AllowInputBreak { get; set; } = false;

	public new static CinematicExitFreezeCameraEvent Create(DDLObject ddl) => new(ddl);
}

