// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x73705c13u)]
public class ClankPuzzleFanBlowTargetPrius : DDLObjectType, IDDLObjectType<ClankPuzzleFanBlowTargetPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x73705c13u);

	public ClankPuzzleFanBlowTargetPrius(DDLObject ddl) : base(ddl) { }

	public static ClankPuzzleFanBlowTargetPrius Create(DDLObject ddl) => new(ddl);
}

