// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x287ecab9u)]
public class ClosestTargetingPrius : TargetingBasePrius, IDDLObjectType<ClosestTargetingPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x287ecab9u);

	public ClosestTargetingPrius(DDLObject ddl) : base(ddl) {
		MaxDistance = ddl.GetValue<float>(0x88831235u, MaxDistance);
	}

	[DDLRegistration(0x88831235u)]
	public float MaxDistance { get; set; } = 0.00f;

	public new static ClosestTargetingPrius Create(DDLObject ddl) => new(ddl);
}

