// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xc5155e4bu)]
public class CompareFloatsNodeDef : MathNodeBaseDef, IDDLObjectType<CompareFloatsNodeDef> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xc5155e4bu);

	public CompareFloatsNodeDef(DDLObject ddl) : base(ddl) {
		Compare = ddl.GetObject<InputPlugSignal>(0xbc236b65u);
		A = ddl.GetObject<InputPlugFloat>(0x3a58e94du);
		B = ddl.GetObject<InputPlugFloat>(0xa351b8f7u);
		LessThan = ddl.GetObject<OutputPlugSignal>(0x266a450bu);
		EqualTo = ddl.GetObject<OutputPlugSignal>(0x75c92864u);
		GreaterThan = ddl.GetObject<OutputPlugSignal>(0x70f69f4du);
	}

	[DDLRegistration(0xbc236b65u)]
	public InputPlugSignal? Compare { get; set; } = default;

	[DDLRegistration(0x3a58e94du)]
	public InputPlugFloat? A { get; set; } = default;

	[DDLRegistration(0xa351b8f7u)]
	public InputPlugFloat? B { get; set; } = default;

	[DDLRegistration(0x266a450bu, "A < B")]
	public OutputPlugSignal? LessThan { get; set; } = default;

	[DDLRegistration(0x75c92864u, "A = B")]
	public OutputPlugSignal? EqualTo { get; set; } = default;

	[DDLRegistration(0x70f69f4du, "A > B")]
	public OutputPlugSignal? GreaterThan { get; set; } = default;

	public new static CompareFloatsNodeDef Create(DDLObject ddl) => new(ddl);
}

