// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x246c0d56u)]
public class ConstantResponseEvent : ResponseEvent, IDDLObjectType<ConstantResponseEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x246c0d56u);

	public ConstantResponseEvent(DDLObject ddl) : base(ddl) {
		ConstantName = ddl.GetString(0xc6991700) ?? ConstantName;
		MaterialMappingName = ddl.GetString(0x981e6927) ?? MaterialMappingName;
		XStartValue = ddl.GetValue<float>(0xb04752ceu, XStartValue);
		YStartValue = ddl.GetValue<float>(0x71c98d0eu, YStartValue);
		ZStartValue = ddl.GetValue<float>(0xe82beb0fu, ZStartValue);
		WStartValue = ddl.GetValue<float>(0x23bfa608u, WStartValue);
		XEndValue = ddl.GetValue<float>(0x1c8adc3fu, XEndValue);
		YEndValue = ddl.GetValue<float>(0x0bf1c87cu, YEndValue);
		ZEndValue = ddl.GetValue<float>(0x327cf4b9u, ZEndValue);
		WEndValue = ddl.GetValue<float>(0xc33313eeu, WEndValue);
		TransitionTime = ddl.GetValue<float>(0xf115e357u, TransitionTime);
		Reset = ddl.GetValue<bool>(0x49ce738cu, Reset);
	}

	[DDLRegistration(0xc6991700u, description: "The name of the render constant to set.")]
	public string? ConstantName { get; set; } = default;

	[DDLRegistration(0x981e6927u, description: "The Maya material mapping to apply this setting to.")]
	public string? MaterialMappingName { get; set; } = default;

	[DDLRegistration(0xb04752ceu)]
	public float XStartValue { get; set; } = 0.00f;

	[DDLRegistration(0x71c98d0eu)]
	public float YStartValue { get; set; } = 0.00f;

	[DDLRegistration(0xe82beb0fu)]
	public float ZStartValue { get; set; } = 0.00f;

	[DDLRegistration(0x23bfa608u)]
	public float WStartValue { get; set; } = 0.00f;

	[DDLRegistration(0x1c8adc3fu)]
	public float XEndValue { get; set; } = 0.00f;

	[DDLRegistration(0x0bf1c87cu)]
	public float YEndValue { get; set; } = 0.00f;

	[DDLRegistration(0x327cf4b9u)]
	public float ZEndValue { get; set; } = 0.00f;

	[DDLRegistration(0xc33313eeu)]
	public float WEndValue { get; set; } = 0.00f;

	[DDLRegistration(0xf115e357u)]
	public float TransitionTime { get; set; } = 0.00f;

	[DDLRegistration(0x49ce738cu, description: "Reset the Constant to its original value(s)")]
	public bool Reset { get; set; } = false;

	public new static ConstantResponseEvent Create(DDLObject ddl) => new(ddl);
}

