// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xfefe3b1bu)]
public class CrowdSpawnerDisallowVolumePrius : DDLObjectType, IDDLObjectType<CrowdSpawnerDisallowVolumePrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xfefe3b1bu);

	public CrowdSpawnerDisallowVolumePrius(DDLObject ddl) : base(ddl) { }

	public static CrowdSpawnerDisallowVolumePrius Create(DDLObject ddl) => new(ddl);
}

