// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x56a464dau)]
public class CurveUsage : DDLObjectType, IDDLObjectType<CurveUsage> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x56a464dau);

	public CurveUsage(DDLObject ddl) : base(ddl) {
		Houdini = ddl.GetValue<bool>(0xd01d63dau, Houdini);
		TerrainRoad = ddl.GetValue<bool>(0x9fc017b0u, TerrainRoad);
	}

	[DDLRegistration(0xd01d63dau, "Houdini", "Show properties for generating rivers with Houdini")]
	public bool Houdini { get; set; } = false;

	[DDLRegistration(0x9fc017b0u, "Terrain Road", "Show properties that can be used with roads on terrain.")]
	public bool TerrainRoad { get; set; } = false;

	public static CurveUsage Create(DDLObject ddl) => new(ddl);
}

