// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xc690d25fu)]
public class DamageModAddOutgoingPrius : DamageModifierOutgoingPrius, IDDLObjectType<DamageModAddOutgoingPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xc690d25fu);

	public DamageModAddOutgoingPrius(DDLObject ddl) : base(ddl) {
		Add = ddl.GetValue<float>(0xd74f5a2eu, Add);
	}

	[DDLRegistration(0xd74f5a2eu)]
	public float Add { get; set; } = 1.00f;

	public new static DamageModAddOutgoingPrius Create(DDLObject ddl) => new(ddl);
}

