// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x7096a833u)]
public class DamageModifierPixelizerResistancePrius : DamageModifierIncomingPrius, IDDLObjectType<DamageModifierPixelizerResistancePrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x7096a833u);

	public DamageModifierPixelizerResistancePrius(DDLObject ddl) : base(ddl) {
		StatusAmountMultiplier = ddl.GetValue<float>(0x6e797759u, StatusAmountMultiplier);
	}

	[DDLRegistration(0x6e797759u)]
	public float StatusAmountMultiplier { get; set; } = 1.00f;

	public new static DamageModifierPixelizerResistancePrius Create(DDLObject ddl) => new(ddl);
}

