// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xf76079cdu)]
public class DDLDoubleVector3 : DDLObjectType, IDDLObjectType<DDLDoubleVector3> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xf76079cdu);

	public DDLDoubleVector3(DDLObject ddl) : base(ddl) {
		X = ddl.GetValue<double>(0x5e33418du, X);
		Y = ddl.GetValue<double>(0x2934711bu, Y);
		Z = ddl.GetValue<double>(0xb03d20a1u, Z);
	}

	[DDLRegistration(0x5e33418du)]
	public double X { get; set; } = 0.00d;

	[DDLRegistration(0x2934711bu)]
	public double Y { get; set; } = 0.00d;

	[DDLRegistration(0xb03d20a1u)]
	public double Z { get; set; } = 0.00d;

	public static DDLDoubleVector3 Create(DDLObject ddl) => new(ddl);
}

