// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x54a47ec4u)]
public class DebugChainEndNodeDef : MissionSystemLogicNodeDef, IDDLObjectType<DebugChainEndNodeDef> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x54a47ec4u);

	public DebugChainEndNodeDef(DDLObject ddl) : base(ddl) {
		DebugOnlyOutput = ddl.GetObject<OutputPlugBoolean>(0xc0b99ef8u);
	}

	[DDLRegistration(0xc0b99ef8u)]
	public OutputPlugBoolean? DebugOnlyOutput { get; set; } = default;

	public new static DebugChainEndNodeDef Create(DDLObject ddl) => new(ddl);
}

