// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xe3cedd6bu)]
public class DevstatsSetColorblindFilterEvent : EventBase, IDDLObjectType<DevstatsSetColorblindFilterEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xe3cedd6bu);

	public DevstatsSetColorblindFilterEvent(DDLObject ddl) : base(ddl) {
		EventId = ddl.GetString(0x2ac4d854) ?? EventId;
		PlayerPosInfo = ddl.GetObject<DevstatsPlayerPositionInfo>(0xeadcc3e4u);
		PrimarySegmentInfo = ddl.GetObject<DevstatsPrimarySegmentInfo>(0x9e8725dbu);
		FilterMode = ddl.GetString(0x46712e84) ?? FilterMode;
		FilterStrength = ddl.GetValue<float>(0xbe4fe432u, FilterStrength);
	}

	[DDLRegistration(0x2ac4d854u)]
	public string? EventId { get; set; } = default;

	[DDLRegistration(0xeadcc3e4u)]
	public DevstatsPlayerPositionInfo? PlayerPosInfo { get; set; } = default;

	[DDLRegistration(0x9e8725dbu)]
	public DevstatsPrimarySegmentInfo? PrimarySegmentInfo { get; set; } = default;

	[DDLRegistration(0x46712e84u)]
	public string? FilterMode { get; set; } = default;

	[DDLRegistration(0xbe4fe432u)]
	public float FilterStrength { get; set; } = 0.00f;

	public new static DevstatsSetColorblindFilterEvent Create(DDLObject ddl) => new(ddl);
}

