// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x6ebaf6b1u)]
public class DisableBirdsCineEvent : EventBase, IDDLObjectType<DisableBirdsCineEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x6ebaf6b1u);

	public DisableBirdsCineEvent(DDLObject ddl) : base(ddl) {
		FadeOutTime = ddl.GetValue<float>(0xf2879affu, FadeOutTime);
	}

	[DDLRegistration(0xf2879affu)]
	public float FadeOutTime { get; set; } = 1.00f;

	public new static DisableBirdsCineEvent Create(DDLObject ddl) => new(ddl);
}

