// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x34e5bdabu)]
public class DisablePoolsResponseMessage : DDLObjectType, IDDLObjectType<DisablePoolsResponseMessage> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x34e5bdabu);

	public DisablePoolsResponseMessage(DDLObject ddl) : base(ddl) {
		RequestId = ddl.GetValue<ushort>(0x239eef0du, RequestId);
		LastMessage = ddl.GetValue<byte>(0x87e83d61u, LastMessage);
	}

	[DDLRegistration(0x239eef0du)]
	public ushort RequestId { get; set; } = 0x0000;

	[DDLRegistration(0x87e83d61u)]
	public byte LastMessage { get; set; } = 0x00;

	public static DisablePoolsResponseMessage Create(DDLObject ddl) => new(ddl);
}

