// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x540ff495u)]
public class DisplayInteractIconEvent : EventBase, IDDLObjectType<DisplayInteractIconEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x540ff495u);

	public DisplayInteractIconEvent(DDLObject ddl) : base(ddl) { }

	public new static DisplayInteractIconEvent Create(DDLObject ddl) => new(ddl);
}

