// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x45ae6ddcu)]
public class EnableParryEvent : EventBase, IDDLObjectType<EnableParryEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x45ae6ddcu);

	public EnableParryEvent(DDLObject ddl) : base(ddl) {
		TargetParryTime = ddl.GetValue<float>(0x58a7b768u, TargetParryTime);
		NextAnim = ddl.GetString(0x8e326e08) ?? NextAnim;
		NextAnimRate = ddl.GetValue<float>(0x3e177b88u, NextAnimRate);
	}

	[DDLRegistration(0x58a7b768u, description: "How long the target can block with the shield to parry this attack")]
	public float TargetParryTime { get; set; } = 0.25f;

	[DDLRegistration(0x8e326e08u, description: "Animation to play if attack was parried")]
	public string? NextAnim { get; set; } = default;

	[DDLRegistration(0x3e177b88u, description: "Time scale of next animation")]
	public float NextAnimRate { get; set; } = 1.00f;

	public new static EnableParryEvent Create(DDLObject ddl) => new(ddl);
}

