// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x185fa542u)]
public class EnableBirdsCineEvent : EventBase, IDDLObjectType<EnableBirdsCineEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x185fa542u);

	public EnableBirdsCineEvent(DDLObject ddl) : base(ddl) { }

	public new static EnableBirdsCineEvent Create(DDLObject ddl) => new(ddl);
}

