// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x122f1f48u)]
public class EventListElement : DDLObjectType, IDDLObjectType<EventListElement> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x122f1f48u);

	public EventListElement(DDLObject ddl) : base(ddl) {
		OutputEvent = ddl.GetObject<EventBase>(0x26a6adb9u);
		PlayOnce = ddl.GetValue<bool>(0xba3988abu, PlayOnce);
	}

	[DDLRegistration(0x26a6adb9u, "Output Event")]
	public EventBase? OutputEvent { get; set; } = default;

	[DDLRegistration(0xba3988abu, description: "Fire this event only once.")]
	public bool PlayOnce { get; set; } = false;

	public static EventListElement Create(DDLObject ddl) => new(ddl);
}

