// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xf69c049au)]
public class FadeOverTimePrius : DDLObjectType, IDDLObjectType<FadeOverTimePrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xf69c049au);

	public FadeOverTimePrius(DDLObject ddl) : base(ddl) {
		SlotIndex = ddl.GetValue<byte>(0x40430d85u, SlotIndex);
		LifeTime = ddl.GetValue<float>(0x67d422c6u, LifeTime);
		FadeTime = ddl.GetValue<float>(0x8833d162u, FadeTime);
	}

	[DDLRegistration(0x40430d85u, description: "What slot to count this type of component to, and compare to guideline of number of allowed for that type.")]
	public byte SlotIndex { get; set; } = 0x00;

	[DDLRegistration(0x67d422c6u, description: "How long before we start fading")]
	public float LifeTime { get; set; } = 0.00f;

	[DDLRegistration(0x8833d162u, description: "How long does the fade last")]
	public float FadeTime { get; set; } = 0.00f;

	public static FadeOverTimePrius Create(DDLObject ddl) => new(ddl);
}

