// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xbddd3e0fu)]
public class FilterSignalActionPrius : DDLObjectType, IDDLObjectType<FilterSignalActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xbddd3e0fu);

	public FilterSignalActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		FilterBehavior = ddl.GetEnum<xb1e939f4>(0x535da55au, xb1e939f4Values.Lookup);
		FilterTime = ddl.GetValue<float>(0xbe2ff16au, FilterTime);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Logic;

	[DDLRegistration(0x535da55au)]
	public xb1e939f4 FilterBehavior { get; set; } = xb1e939f4.FilterByTime;

	[DDLRegistration(0xbe2ff16au, "Filter Period", "Don't allow a signal to pass through through more than once per this period. If 'Filter By Frame' is checked, this value is ignored.")]
	public float FilterTime { get; set; } = 1.00f;

	public static FilterSignalActionPrius Create(DDLObject ddl) => new(ddl);
}

