// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x7dd00c5bu)]
public class FloatOutNodeDef : NodeBaseDef, IDDLObjectType<FloatOutNodeDef> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x7dd00c5bu);

	public FloatOutNodeDef(DDLObject ddl) : base(ddl) {
		Out = ddl.GetObject<OutputPlugFloat>(0x93bf4450u);
	}

	[DDLRegistration(0x93bf4450u)]
	public OutputPlugFloat? Out { get; set; } = default;

	public new static FloatOutNodeDef Create(DDLObject ddl) => new(ddl);
}

