// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xd727f3b0u)]
public class FollowModifierTargetFacingPrius : DDLObjectType, IDDLObjectType<FollowModifierTargetFacingPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xd727f3b0u);

	public FollowModifierTargetFacingPrius(DDLObject ddl) : base(ddl) {
		Priority = ddl.GetEnum<xf94df176>(0x98a76157u, xf94df176Values.Lookup);
		VectorMode = ddl.GetEnum<x531b18aa>(0xff506db2u, x531b18aaValues.Lookup);
		TargetVector = ddl.GetObject<DDLVector3>(0xe9df027du);
		TargetActorHandle = ddl.GetValue<uint>(0xa68ca01fu, TargetActorHandle);
		TargetYaw = ddl.GetValue<float>(0xdf99230eu, TargetYaw);
		TargetPitch = ddl.GetValue<float>(0xfbbfa6acu, TargetPitch);
		TargetTolerance = ddl.GetValue<float>(0x121a236fu, TargetTolerance);
		AccelOrGain = ddl.GetValue<float>(0xd0dd75a7u, AccelOrGain);
		DecelOrDamp = ddl.GetValue<float>(0x2042fe2bu, DecelOrDamp);
		SpeedMaxYaw = ddl.GetValue<float>(0xee2137e5u, SpeedMaxYaw);
		SpeedMaxPitch = ddl.GetValue<float>(0x5cef694eu, SpeedMaxPitch);
		ApplyDelay = ddl.GetValue<float>(0x8f28295eu, ApplyDelay);
		LockBlendTime = ddl.GetValue<float>(0x00b39182u, LockBlendTime);
		PeakAngle = ddl.GetValue<float>(0x44ccc370u, PeakAngle);
		BackDeadAngle = ddl.GetValue<float>(0xafd78f02u, BackDeadAngle);
		DestroyOnBlock = ddl.GetValue<bool>(0xde5d2683u, DestroyOnBlock);
		DestroyOnInput = ddl.GetValue<bool>(0x856e8376u, DestroyOnInput);
		DestroyOnComplete = ddl.GetValue<bool>(0x07fd4567u, DestroyOnComplete);
		UseYawInput = ddl.GetValue<bool>(0xcce09cfdu, UseYawInput);
		UsePitchInput = ddl.GetValue<bool>(0x057d1da2u, UsePitchInput);
		ApplyWithInput = ddl.GetValue<bool>(0xa6c1b50fu, ApplyWithInput);
		MotionMode = ddl.GetEnum<x79dd0c33>(0x6057228cu, x79dd0c33Values.Lookup);
	}

	[DDLRegistration(0x98a76157u, "Priority")]
	public xf94df176 Priority { get; set; } = xf94df176.Default;

	[DDLRegistration(0xff506db2u, "Vector Apply")]
	public x531b18aa VectorMode { get; set; } = x531b18aa.None;

	[DDLRegistration(0xe9df027du)]
	public DDLVector3? TargetVector { get; set; } = default;

	[DDLRegistration(0xa68ca01fu)]
	public uint TargetActorHandle { get; set; } = 0x00000000;

	[DDLRegistration(0xdf99230eu)]
	public float TargetYaw { get; set; } = 9999.00f;

	[DDLRegistration(0xfbbfa6acu)]
	public float TargetPitch { get; set; } = 9999.00f;

	[DDLRegistration(0x121a236fu)]
	public float TargetTolerance { get; set; } = 0.00f;

	[DDLRegistration(0xd0dd75a7u)]
	public float AccelOrGain { get; set; } = 30.00f;

	[DDLRegistration(0x2042fe2bu)]
	public float DecelOrDamp { get; set; } = 8.00f;

	[DDLRegistration(0xee2137e5u)]
	public float SpeedMaxYaw { get; set; } = 230.00f;

	[DDLRegistration(0x5cef694eu)]
	public float SpeedMaxPitch { get; set; } = 57.00f;

	[DDLRegistration(0x8f28295eu)]
	public float ApplyDelay { get; set; } = 0.00f;

	[DDLRegistration(0x00b39182u)]
	public float LockBlendTime { get; set; } = 0.00f;

	[DDLRegistration(0x44ccc370u)]
	public float PeakAngle { get; set; } = 3.14f;

	[DDLRegistration(0xafd78f02u)]
	public float BackDeadAngle { get; set; } = 31.51f;

	[DDLRegistration(0xde5d2683u)]
	public bool DestroyOnBlock { get; set; } = true;

	[DDLRegistration(0x856e8376u)]
	public bool DestroyOnInput { get; set; } = false;

	[DDLRegistration(0x07fd4567u)]
	public bool DestroyOnComplete { get; set; } = false;

	[DDLRegistration(0xcce09cfdu)]
	public bool UseYawInput { get; set; } = false;

	[DDLRegistration(0x057d1da2u)]
	public bool UsePitchInput { get; set; } = false;

	[DDLRegistration(0xa6c1b50fu)]
	public bool ApplyWithInput { get; set; } = true;

	[DDLRegistration(0x6057228cu)]
	public x79dd0c33 MotionMode { get; set; } = x79dd0c33.Default;

	public static FollowModifierTargetFacingPrius Create(DDLObject ddl) => new(ddl);
}

