// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x9444087du)]
public class FormationAttackAction : DDLObjectType, IDDLObjectType<FormationAttackAction> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x9444087du);

	public FormationAttackAction(DDLObject ddl) : base(ddl) {
		Action = ddl.GetEnum<xbf382bc0>(0x79b4c2f5u, xbf382bc0Values.Lookup);
		Value = ddl.GetValue<float>(0x042494f5u, Value);
	}

	[DDLRegistration(0x79b4c2f5u)]
	public xbf382bc0 Action { get; set; } = xbf382bc0.Wait;

	[DDLRegistration(0x042494f5u, description: "General purpose value for the actions")]
	public float Value { get; set; } = 1.00f;

	public static FormationAttackAction Create(DDLObject ddl) => new(ddl);
}

