// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xdcc547deu)]
public class FossilizeHoleTrackerPrius : DDLObjectType, IDDLObjectType<FossilizeHoleTrackerPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xdcc547deu);

	public FossilizeHoleTrackerPrius(DDLObject ddl) : base(ddl) {
		PreApplyMaterial = ddl.GetValue<RivetAssetId>(0x19334b06u, PreApplyMaterial);
		PostApplyMaterial = ddl.GetValue<RivetAssetId>(0x7a77becdu, PostApplyMaterial);
		PostAlwaysOn = ddl.GetValue<bool>(0x6933104bu, PostAlwaysOn);
		HoleTrackActor = ddl.GetValue<RivetAssetId>(0xf02f47a1u, HoleTrackActor);
		HitFadeTime = ddl.GetValue<float>(0x6297fb04u, HitFadeTime);
		FadeOutTime = ddl.GetValue<float>(0xf2879affu, FadeOutTime);
		CurrentHitScale = ddl.GetValue<float>(0x27cc0938u, CurrentHitScale);
		LastHitScale = ddl.GetValue<float>(0x2b2858f8u, LastHitScale);
		IdleWaveSpeed = ddl.GetValue<float>(0x2a093990u, IdleWaveSpeed);
		IdleWaveScale = ddl.GetValue<float>(0xc969e2e2u, IdleWaveScale);
		MinimumScale = ddl.GetValue<float>(0xb0a09377u, MinimumScale);
		DeathPreApplyMaterial = ddl.GetValue<RivetAssetId>(0xe59fe9d3u, DeathPreApplyMaterial);
		DeathPostApplyMaterial = ddl.GetValue<RivetAssetId>(0x8c323434u, DeathPostApplyMaterial);
		DeathPostAlwaysOn = ddl.GetValue<bool>(0x56926a11u, DeathPostAlwaysOn);
		DeathDisolveDelay = ddl.GetValue<float>(0xfc2f9d1fu, DeathDisolveDelay);
		DeathDisolveDuration = ddl.GetValue<float>(0xdb45c1dfu, DeathDisolveDuration);
		HoleSize = ddl.GetValue<float>(0xb981864fu, HoleSize);
		SmallDeathDisolveDelay = ddl.GetValue<float>(0xf2fd9b18u, SmallDeathDisolveDelay);
		SmallDeathDisolveSpeed = ddl.GetValue<float>(0x4f41e575u, SmallDeathDisolveSpeed);
		SmallHoleSize = ddl.GetValue<float>(0xbecc800du, SmallHoleSize);
		DeathUseJointCrawl = ddl.GetValue<bool>(0x53d62856u, DeathUseJointCrawl);
	}

	[DDLRegistration(0x19334b06u)]
	public RivetAssetId PreApplyMaterial { get; set; } = default;

	[DDLRegistration(0x7a77becdu)]
	public RivetAssetId PostApplyMaterial { get; set; } = default;

	[DDLRegistration(0x6933104bu, description: "A render flag to allow the post apply material to draw on pixels that were hidden in the pre apply material.")]
	public bool PostAlwaysOn { get; set; } = false;

	[DDLRegistration(0xf02f47a1u)]
	public RivetAssetId HoleTrackActor { get; set; } = default;

	[DDLRegistration(0x6297fb04u, description: "After a shot, how long does it take to go back to the idle size.")]
	public float HitFadeTime { get; set; } = 1.00f;

	[DDLRegistration(0xf2879affu, description: "After we reach 4 shots, how long until the first shot fades out.")]
	public float FadeOutTime { get; set; } = 1.00f;

	[DDLRegistration(0x27cc0938u, description: "What scale do we add for the current hit.")]
	public float CurrentHitScale { get; set; } = 0.30f;

	[DDLRegistration(0x2b2858f8u, description: "What scale do we add for all hits.")]
	public float LastHitScale { get; set; } = 0.40f;

	[DDLRegistration(0x2a093990u, description: "How fast does the sin wave cycle (radians per second)")]
	public float IdleWaveSpeed { get; set; } = 1.00f;

	[DDLRegistration(0xc969e2e2u, description: "What scale do we apply in a sin wave over time.")]
	public float IdleWaveScale { get; set; } = 0.10f;

	[DDLRegistration(0xb0a09377u, description: "What scale do we apply as a minimum amount.")]
	public float MinimumScale { get; set; } = 0.20f;

	[DDLRegistration(0xe59fe9d3u)]
	public RivetAssetId DeathPreApplyMaterial { get; set; } = default;

	[DDLRegistration(0x8c323434u)]
	public RivetAssetId DeathPostApplyMaterial { get; set; } = default;

	[DDLRegistration(0x56926a11u, description: "A render flag to allow the post apply material to draw on pixels that were hidden in the pre apply material.")]
	public bool DeathPostAlwaysOn { get; set; } = false;

	[DDLRegistration(0xfc2f9d1fu)]
	public float DeathDisolveDelay { get; set; } = 0.00f;

	[DDLRegistration(0xdb45c1dfu)]
	public float DeathDisolveDuration { get; set; } = 2.50f;

	[DDLRegistration(0xb981864fu)]
	public float HoleSize { get; set; } = 1.00f;

	[DDLRegistration(0xf2fd9b18u)]
	public float SmallDeathDisolveDelay { get; set; } = 0.00f;

	[DDLRegistration(0x4f41e575u)]
	public float SmallDeathDisolveSpeed { get; set; } = 1.00f;

	[DDLRegistration(0xbecc800du)]
	public float SmallHoleSize { get; set; } = 1.00f;

	[DDLRegistration(0x53d62856u)]
	public bool DeathUseJointCrawl { get; set; } = true;

	public static FossilizeHoleTrackerPrius Create(DDLObject ddl) => new(ddl);
}

