// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x7c199893u)]
public class GalacticMapShipLandFinishEvent : EventBase, IDDLObjectType<GalacticMapShipLandFinishEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x7c199893u);

	public GalacticMapShipLandFinishEvent(DDLObject ddl) : base(ddl) { }

	public new static GalacticMapShipLandFinishEvent Create(DDLObject ddl) => new(ddl);
}

