// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x44ccdf52u)]
public class GameBotShooterSheepPrius : GameBotShooterPrius, IDDLObjectType<GameBotShooterSheepPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x44ccdf52u);

	public GameBotShooterSheepPrius(DDLObject ddl) : base(ddl) {
		Upgraded = ddl.GetValue<bool>(0x9f0968b2u, Upgraded);
		Horns = ddl.GetValue<RivetAssetId>(0x70713a94u, Horns);
	}

	[DDLRegistration(0x9f0968b2u, description: "Upgraded ally sheep (level 5 Sheepinator)")]
	public bool Upgraded { get; set; } = false;

	[DDLRegistration(0x70713a94u)]
	public RivetAssetId Horns { get; set; } = default;

	public new static GameBotShooterSheepPrius Create(DDLObject ddl) => new(ddl);
}

