// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x424284aeu)]
public class GameAwardStatusEffectKillCountPrius : AwardBasePrius, IDDLObjectType<GameAwardStatusEffectKillCountPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x424284aeu);

	public GameAwardStatusEffectKillCountPrius(DDLObject ddl) : base(ddl) {
		RequiredStatusEffect = ddl.GetObject<StatusEffectBasePrius>(0xedfb7a1bu);
	}

	[DDLRegistration(0xedfb7a1bu)]
	public StatusEffectBasePrius? RequiredStatusEffect { get; set; } = default;

	public new static GameAwardStatusEffectKillCountPrius Create(DDLObject ddl) => new(ddl);
}

