// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xba217d9du)]
public class GetItemCountActionPrius : DDLObjectType, IDDLObjectType<GetItemCountActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xba217d9du);

	public GetItemCountActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		ItemConfig = ddl.GetValue<RivetAssetId>(0xa88f833fu, ItemConfig);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Inventory;

	[DDLRegistration(0xa88f833fu)]
	public RivetAssetId ItemConfig { get; set; } = default;

	public static GetItemCountActionPrius Create(DDLObject ddl) => new(ddl);
}

