// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x4dba16b9u)]
public class GrenadeExplosionMode : DDLObjectType, IDDLObjectType<GrenadeExplosionMode> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x4dba16b9u);

	public GrenadeExplosionMode(DDLObject ddl) : base(ddl) { }

	public static GrenadeExplosionMode Create(DDLObject ddl) => new(ddl);
}

