// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x3760a488u)]
public class GroundDashEndEvent : EventBase, IDDLObjectType<GroundDashEndEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x3760a488u);

	public GroundDashEndEvent(DDLObject ddl) : base(ddl) {
		DodgeActorHandle = ddl.GetValue<uint>(0xd5fe2c1bu, DodgeActorHandle);
		IsPhaseDash = ddl.GetValue<bool>(0x4a5de148u, IsPhaseDash);
	}

	[DDLRegistration(0xd5fe2c1bu)]
	public uint DodgeActorHandle { get; set; } = 0x00000000;

	[DDLRegistration(0x4a5de148u)]
	public bool IsPhaseDash { get; set; } = false;

	public new static GroundDashEndEvent Create(DDLObject ddl) => new(ddl);
}

