// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x9710d78fu)]
public class GroundTriggerInvalidUserEvent : EventBase, IDDLObjectType<GroundTriggerInvalidUserEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x9710d78fu);

	public GroundTriggerInvalidUserEvent(DDLObject ddl) : base(ddl) {
		UserHandle = ddl.GetValue<uint>(0x25e06c12u, UserHandle);
	}

	[DDLRegistration(0x25e06c12u)]
	public uint UserHandle { get; set; } = 0x00000000;

	public new static GroundTriggerInvalidUserEvent Create(DDLObject ddl) => new(ddl);
}

