// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x9315dcceu)]
public class HeadRetractEvent : EventBase, IDDLObjectType<HeadRetractEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x9315dcceu);

	public HeadRetractEvent(DDLObject ddl) : base(ddl) { }

	public new static HeadRetractEvent Create(DDLObject ddl) => new(ddl);
}

