// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x927d9edau)]
public class HeroDefaultVanityLoadedEvent : EventBase, IDDLObjectType<HeroDefaultVanityLoadedEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x927d9edau);

	public HeroDefaultVanityLoadedEvent(DDLObject ddl) : base(ddl) { }

	public new static HeroDefaultVanityLoadedEvent Create(DDLObject ddl) => new(ddl);
}

