// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xa82c9abdu)]
public class HeroSpaceshipPrius : DDLObjectType, IDDLObjectType<HeroSpaceshipPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xa82c9abdu);

	public HeroSpaceshipPrius(DDLObject ddl) : base(ddl) { }

	public static HeroSpaceshipPrius Create(DDLObject ddl) => new(ddl);
}

