// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x30925603u)]
public class HeroCinematicTransitionDataSkyDive : HeroCinematicTransitionDataBase, IDDLObjectType<HeroCinematicTransitionDataSkyDive> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x30925603u);

	public HeroCinematicTransitionDataSkyDive(DDLObject ddl) : base(ddl) { }

	public new static HeroCinematicTransitionDataSkyDive Create(DDLObject ddl) => new(ddl);
}

