// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xb16ec39au)]
public class HeroLockActionPrius : DDLObjectType, IDDLObjectType<HeroLockActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xb16ec39au);

	public HeroLockActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Hero;

	public static HeroLockActionPrius Create(DDLObject ddl) => new(ddl);
}

