// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xbb4c617eu)]
public class HoverStartEvent : EventBase, IDDLObjectType<HoverStartEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xbb4c617eu);

	public HoverStartEvent(DDLObject ddl) : base(ddl) { }

	public new static HoverStartEvent Create(DDLObject ddl) => new(ddl);
}

