// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x2fc42423u)]
public class InitAnimFilterPrius : DDLObjectType, IDDLObjectType<InitAnimFilterPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x2fc42423u);

	public InitAnimFilterPrius(DDLObject ddl) : base(ddl) {
		FilterList = ddl.GetObjects<InitAnimFilterElement>(0x95739137u);
	}

	[DDLRegistration(0x95739137u)]
	public List<InitAnimFilterElement?> FilterList { get; set; } = [];

	public static InitAnimFilterPrius Create(DDLObject ddl) => new(ddl);
}

