// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x363de5f3u)]
public class InputPlugBaseDef : NodeGraphItemDef, IDDLObjectType<InputPlugBaseDef> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x363de5f3u);

	public InputPlugBaseDef(DDLObject ddl) : base(ddl) { }

	public new static InputPlugBaseDef Create(DDLObject ddl) => new(ddl);
}

