// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xf2c99c32u)]
public class InteractConditionPriusItem : DDLObjectType, IDDLObjectType<InteractConditionPriusItem> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xf2c99c32u);

	public InteractConditionPriusItem(DDLObject ddl) : base(ddl) {
		ConditionData = ddl.GetObject<InteractUserConditionBasePrius>(0x368dae8bu);
	}

	[DDLRegistration(0x368dae8bu)]
	public InteractUserConditionBasePrius? ConditionData { get; set; } = default;

	public static InteractConditionPriusItem Create(DDLObject ddl) => new(ddl);
}

