// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x34ae1692u)]
public class InteractExplodedEvent : EventBase, IDDLObjectType<InteractExplodedEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x34ae1692u);

	public InteractExplodedEvent(DDLObject ddl) : base(ddl) { }

	public new static InteractExplodedEvent Create(DDLObject ddl) => new(ddl);
}

