// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x09997d84u)]
public class ItemComponentAmmoPrius : BaseComponentAmmoPrius, IDDLObjectType<ItemComponentAmmoPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x09997d84u);

	public ItemComponentAmmoPrius(DDLObject ddl) : base(ddl) {
		AmmoItemConfig = ddl.GetValue<RivetAssetId>(0x7151e5a4u, AmmoItemConfig);
		ClipMax = ddl.GetValue<float>(0xfc892dc4u, ClipMax);
	}

	[DDLRegistration(0x7151e5a4u, "Ammo Item")]
	public RivetAssetId AmmoItemConfig { get; set; } = default;

	[DDLRegistration(0xfc892dc4u)]
	public float ClipMax { get; set; } = 0.00f;

	public new static ItemComponentAmmoPrius Create(DDLObject ddl) => new(ddl);
}

