// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x7ed272f2u)]
public class JointToBodyFilter : DDLObjectType, IDDLObjectType<JointToBodyFilter> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x7ed272f2u);

	public JointToBodyFilter(DDLObject ddl) : base(ddl) {
		JointName = ddl.GetString(0x5ba51db8) ?? JointName;
		BodyPartFilter = ddl.GetEnum<xfdd79442>(0xa41c7d7fu, xfdd79442Values.Lookup);
	}

	[DDLRegistration(0x5ba51db8u)]
	public string? JointName { get; set; } = "head";

	[DDLRegistration(0xa41c7d7fu)]
	public xfdd79442 BodyPartFilter { get; set; } = xfdd79442.HitLocationHead;

	public static JointToBodyFilter Create(DDLObject ddl) => new(ddl);
}

