// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x0a615951u)]
public class KnockdownData : DDLObjectType, IDDLObjectType<KnockdownData> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x0a615951u);

	public KnockdownData(DDLObject ddl) : base(ddl) {
		Driver = ddl.GetString(0x2f1e32be) ?? Driver;
		Normal = ddl.GetObject<ScaleData>(0x1ffd2683u);
		Blast = ddl.GetObject<ScaleData>(0x571c694du);
	}

	[DDLRegistration(0x2f1e32beu)]
	public string? Driver { get; set; } = "React_Knockdown";

	[DDLRegistration(0x1ffd2683u)]
	public ScaleData? Normal { get; set; } = default;

	[DDLRegistration(0x571c694du)]
	public ScaleData? Blast { get; set; } = default;

	public static KnockdownData Create(DDLObject ddl) => new(ddl);
}

