// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x7a67923fu)]
public class LevelDefAux : DDLObjectType, IDDLObjectType<LevelDefAux> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x7a67923fu);

	public LevelDefAux(DDLObject ddl) : base(ddl) {
		OverlayFolders = ddl.GetDictionary<RivetAssetId, RegionFolderNode>(0xca3e2e80, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<RegionFolderNode>(mapId));
	}

	[DDLRegistration(0xca3e2e80u)]
	public Dictionary<RivetAssetId, RegionFolderNode?> OverlayFolders { get; set; } = [];

	public static LevelDefAux Create(DDLObject ddl) => new(ddl);
}

