// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xbfa7fda3u)]
public class LocTagTableDef : DDLObjectType, IDDLObjectType<LocTagTableDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xbfa7fda3u);

	public LocTagTableDef(DDLObject ddl) : base(ddl) {
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		GroupName = ddl.GetString(0xb215bfb7) ?? GroupName;
		Flags = ddl.GetEnum<LocalizationFlags>(0x12568d7bu, LocalizationFlagsValues.Lookup);
		LanguageText = ddl.GetObjects<LocTagLanguageDef>(0xc4da86afu);
	}

	[DDLRegistration(0x6eb3beb6u, "Name", "Loc Tag Name")]
	public string? Name { get; set; } = default;

	[DDLRegistration(0xb215bfb7u, "GroupName", "Loc Tag Group Name")]
	public string? GroupName { get; set; } = default;

	[DDLRegistration(0x12568d7bu, "Flags", "Loc Tag Flags")]
	public LocalizationFlags Flags { get; set; } = LocalizationFlags.None;

	[DDLRegistration(0xc4da86afu, "Language Text", "Table of localized text per language.")]
	public List<LocTagLanguageDef?> LanguageText { get; set; } = [];

	public static LocTagTableDef Create(DDLObject ddl) => new(ddl);
}

