// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xd4d7848eu)]
public class LogAimAssistStartActionPrius : DDLObjectType, IDDLObjectType<LogAimAssistStartActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xd4d7848eu);

	public LogAimAssistStartActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		TaskNumber = ddl.GetValue<uint>(0x0796b3e7u, TaskNumber);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Debug;

	[DDLRegistration(0x0796b3e7u)]
	public uint TaskNumber { get; set; } = 0x00000000;

	public static LogAimAssistStartActionPrius Create(DDLObject ddl) => new(ddl);
}

