// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x15bfc955u)]
public class LookDef : DDLObjectType, IDDLObjectType<LookDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x15bfc955u);

	public LookDef(DDLObject ddl) : base(ddl) {
		LookName = ddl.GetString(0xad8c1e16) ?? LookName;
	}

	[DDLRegistration(0xad8c1e16u, description: "Name of this look.")]
	public string? LookName { get; set; } = "Default";

	public static LookDef Create(DDLObject ddl) => new(ddl);
}

