// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x8389942eu)]
public class MannableTurretGrindRopeTargetPrius : DDLObjectType, IDDLObjectType<MannableTurretGrindRopeTargetPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x8389942eu);

	public MannableTurretGrindRopeTargetPrius(DDLObject ddl) : base(ddl) { }

	public static MannableTurretGrindRopeTargetPrius Create(DDLObject ddl) => new(ddl);
}

