// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x1d9bc567u)]
public class MeshUvDef : DDLObjectType, IDDLObjectType<MeshUvDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x1d9bc567u);

	public MeshUvDef(DDLObject ddl) : base(ddl) {
		Uv = ddl.GetValues<float>(0x9f9f6698u);
	}

	[DDLRegistration(0x9f9f6698u)]
	public List<float> Uv { get; set; } = [];

	public static MeshUvDef Create(DDLObject ddl) => new(ddl);
}

