// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xa5f634eau)]
public class MeshDef : DDLObjectType, IDDLObjectType<MeshDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xa5f634eau);

	public MeshDef(DDLObject ddl) : base(ddl) {
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		Positions = ddl.GetObjects<MeshPosDef>(0x54627a70u);
		Normals = ddl.GetObjects<MeshNormalDef>(0xbda20f3au);
		UVs = ddl.GetObjects<MeshUvDef>(0xa2c38034u);
		UV2s = ddl.GetObjects<MeshUvDef>(0x017869f7u);
		Colors = ddl.GetObjects<MeshUColorDef>(0xfcc68df8u);
		SkinVerts = ddl.GetObjects<MeshSkinVertDef>(0x620ab253u);
		Tris = ddl.GetObjects<MeshTriDef>(0xdfcf6431u);
	}

	[DDLRegistration(0x6eb3beb6u)]
	public string? Name { get; set; } = default;

	[DDLRegistration(0x54627a70u)]
	public List<MeshPosDef?> Positions { get; set; } = [];

	[DDLRegistration(0xbda20f3au)]
	public List<MeshNormalDef?> Normals { get; set; } = [];

	[DDLRegistration(0xa2c38034u)]
	public List<MeshUvDef?> UVs { get; set; } = [];

	[DDLRegistration(0x017869f7u)]
	public List<MeshUvDef?> UV2s { get; set; } = [];

	[DDLRegistration(0xfcc68df8u)]
	public List<MeshUColorDef?> Colors { get; set; } = [];

	[DDLRegistration(0x620ab253u)]
	public List<MeshSkinVertDef?> SkinVerts { get; set; } = [];

	[DDLRegistration(0xdfcf6431u)]
	public List<MeshTriDef?> Tris { get; set; } = [];

	public static MeshDef Create(DDLObject ddl) => new(ddl);
}

