// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xcc580b11u)]
public class MissionCompleteEvent : EventBase, IDDLObjectType<MissionCompleteEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xcc580b11u);

	public MissionCompleteEvent(DDLObject ddl) : base(ddl) {
		MissionName = ddl.GetString(0xa5c30e60) ?? MissionName;
		SilentMode = ddl.GetValue<bool>(0xa3d8f631u, SilentMode);
		IsSkipping = ddl.GetValue<bool>(0x5cc05663u, IsSkipping);
	}

	[DDLRegistration(0xa5c30e60u)]
	public string? MissionName { get; set; } = default;

	[DDLRegistration(0xa3d8f631u, description: "True if we shouldn't show the mission-complete dialog.")]
	public bool SilentMode { get; set; } = false;

	[DDLRegistration(0x5cc05663u, description: "True if the objective is being set to 'complete' as a prerequisite for loading straight into a mission from the frontend.")]
	public bool IsSkipping { get; set; } = false;

	public new static MissionCompleteEvent Create(DDLObject ddl) => new(ddl);
}

