// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xd3a52239u)]
public class ModelSplineEnvelopeFloatDef : DDLObjectType, IDDLObjectType<ModelSplineEnvelopeFloatDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xd3a52239u);

	public ModelSplineEnvelopeFloatDef(DDLObject ddl) : base(ddl) {
		BaseValue = ddl.GetValue<float>(0x950d56d7u, BaseValue);
		Envelope = ddl.GetObject<EnvelopeFloatDef>(0x7094c518u);
	}

	[DDLRegistration(0x950d56d7u)]
	public float BaseValue { get; set; } = 1.00f;

	[DDLRegistration(0x7094c518u)]
	public EnvelopeFloatDef? Envelope { get; set; } = default;

	public static ModelSplineEnvelopeFloatDef Create(DDLObject ddl) => new(ddl);
}

