// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x1eb2e383u)]
public class ModelSplineEnvelopeVec2Def : DDLObjectType, IDDLObjectType<ModelSplineEnvelopeVec2Def> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x1eb2e383u);

	public ModelSplineEnvelopeVec2Def(DDLObject ddl) : base(ddl) {
		BaseValue = ddl.GetObject<DDLVector2>(0x950d56d7u);
		Envelope = ddl.GetObject<EnvelopeVec2Def>(0x7094c518u);
	}

	[DDLRegistration(0x950d56d7u)]
	public DDLVector2? BaseValue { get; set; } = default;

	[DDLRegistration(0x7094c518u)]
	public EnvelopeVec2Def? Envelope { get; set; } = default;

	public static ModelSplineEnvelopeVec2Def Create(DDLObject ddl) => new(ddl);
}

