// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x58612f37u)]
public class MountConfig : ConfigBase, IDDLObjectType<MountConfig> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x58612f37u);

	public MountConfig(DDLObject ddl) : base(ddl) {
		HeroData = ddl.GetObject<HeroMountData>(0x34ae7542u);
		BotData = ddl.GetObject<BotMountData>(0x59da994bu);
		MountCameraConfig = ddl.GetValue<RivetAssetId>(0x1bf25fc0u, MountCameraConfig);
		CameraStickConfig = ddl.GetValue<RivetAssetId>(0xb3806672u, CameraStickConfig);
		CameraStickAltConfig = ddl.GetValue<RivetAssetId>(0x6427a241u, CameraStickAltConfig);
		Abilities = ddl.GetObjects<MountAbilityContainer>(0x3ac512a8u);
	}

	[DDLRegistration(0x34ae7542u)]
	public HeroMountData? HeroData { get; set; } = default;

	[DDLRegistration(0x59da994bu)]
	public BotMountData? BotData { get; set; } = default;

	[DDLRegistration(0x1bf25fc0u)]
	public RivetAssetId MountCameraConfig { get; set; } = default;

	[DDLRegistration(0xb3806672u, "Camera Stick Config")]
	public RivetAssetId CameraStickConfig { get; set; } = default;

	[DDLRegistration(0x6427a241u, "Camera Stick Alternate Config")]
	public RivetAssetId CameraStickAltConfig { get; set; } = default;

	[DDLRegistration(0x3ac512a8u)]
	public List<MountAbilityContainer?> Abilities { get; set; } = [];

	public new static MountConfig Create(DDLObject ddl) => new(ddl);
}

