// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x45c54833u)]
public class MountImpactEvent : EventBase, IDDLObjectType<MountImpactEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x45c54833u);

	public MountImpactEvent(DDLObject ddl) : base(ddl) { }

	public new static MountImpactEvent Create(DDLObject ddl) => new(ddl);
}

