// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x0fcd16ceu)]
public class MountBoostLaunchStartEvent : EventBase, IDDLObjectType<MountBoostLaunchStartEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x0fcd16ceu);

	public MountBoostLaunchStartEvent(DDLObject ddl) : base(ddl) { }

	public new static MountBoostLaunchStartEvent Create(DDLObject ddl) => new(ddl);
}

