// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xd99b6b66u)]
public class MouseOverEngineItem : DDLObjectType, IDDLObjectType<MouseOverEngineItem> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xd99b6b66u);

	public MouseOverEngineItem(DDLObject ddl) : base(ddl) {
		Valid = ddl.GetValue<bool>(0x9554f93eu, Valid);
		NodeId = ddl.GetValue<RivetAssetId>(0x371a59e0u, NodeId);
		WorldPosition = ddl.GetObject<DDLVector3>(0x1b2eab1cu);
		WorldNormal = ddl.GetObject<DDLVector3>(0xa0ad029au);
		SubsetIndex = ddl.GetValue<int>(0x0f1c36c5u, SubsetIndex);
		TriangleIndex = ddl.GetValue<int>(0x4abd9e69u, TriangleIndex);
	}

	[DDLRegistration(0x9554f93eu)]
	public bool Valid { get; set; } = false;

	[DDLRegistration(0x371a59e0u)]
	public RivetAssetId NodeId { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0x1b2eab1cu)]
	public DDLVector3? WorldPosition { get; set; } = default;

	[DDLRegistration(0xa0ad029au)]
	public DDLVector3? WorldNormal { get; set; } = default;

	[DDLRegistration(0x0f1c36c5u)]
	public int SubsetIndex { get; set; } = 0;

	[DDLRegistration(0x4abd9e69u)]
	public int TriangleIndex { get; set; } = 0;

	public static MouseOverEngineItem Create(DDLObject ddl) => new(ddl);
}

