// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x1e181976u)]
public class MrFunGuyAwarenessPrius : BotAreaAwarenessPrius, IDDLObjectType<MrFunGuyAwarenessPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x1e181976u);

	public MrFunGuyAwarenessPrius(DDLObject ddl) : base(ddl) { }

	public new static MrFunGuyAwarenessPrius Create(DDLObject ddl) => new(ddl);
}

