// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xc9631cceu)]
public class MrFunGuyAppearEvent : EventBase, IDDLObjectType<MrFunGuyAppearEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xc9631cceu);

	public MrFunGuyAppearEvent(DDLObject ddl) : base(ddl) { }

	public new static MrFunGuyAppearEvent Create(DDLObject ddl) => new(ddl);
}

