// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xd5a4f79bu)]
public class NodeGraphActorContextAttachmentDebugMessage : DDLObjectType, IDDLObjectType<NodeGraphActorContextAttachmentDebugMessage> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xd5a4f79bu);

	public NodeGraphActorContextAttachmentDebugMessage(DDLObject ddl) : base(ddl) {
		AssetId = ddl.GetValue<RivetAssetId>(0xb6e788d7u, AssetId);
		ActorContextId = ddl.GetValue<uint>(0x55ffc909u, ActorContextId);
	}

	[DDLRegistration(0xb6e788d7u)]
	public RivetAssetId AssetId { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0x55ffc909u)]
	public uint ActorContextId { get; set; } = 0x00000000;

	public static NodeGraphActorContextAttachmentDebugMessage Create(DDLObject ddl) => new(ddl);
}

