// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x5eebcec9u)]
public class NoMissionsActiveTriggerPrius : BaseCustomOverlayTriggerPrius, IDDLObjectType<NoMissionsActiveTriggerPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x5eebcec9u);

	public NoMissionsActiveTriggerPrius(DDLObject ddl) : base(ddl) { }

	public new static NoMissionsActiveTriggerPrius Create(DDLObject ddl) => new(ddl);
}

