// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xc05216a9u)]
public class OnAttachParentMoved : EventBase, IDDLObjectType<OnAttachParentMoved> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xc05216a9u);

	public OnAttachParentMoved(DDLObject ddl) : base(ddl) { }

	public new static OnAttachParentMoved Create(DDLObject ddl) => new(ddl);
}

