// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xb716915au)]
public class OnInventoryChangedActionPrius : DDLObjectType, IDDLObjectType<OnInventoryChangedActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xb716915au);

	public OnInventoryChangedActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		ItemConfig = ddl.GetValue<RivetAssetId>(0xa88f833fu, ItemConfig);
		InitListening = ddl.GetValue<bool>(0xf387b27au, InitListening);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Events;

	[DDLRegistration(0xa88f833fu)]
	public RivetAssetId ItemConfig { get; set; } = default;

	[DDLRegistration(0xf387b27au, description: "Whether to start listening immediately when the script it loaded.")]
	public bool InitListening { get; set; } = true;

	public static OnInventoryChangedActionPrius Create(DDLObject ddl) => new(ddl);
}

