// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xf94f2bbcu)]
public class OnPassMaxRangeNodeDef : NodalShotEventNodeBaseDef, IDDLObjectType<OnPassMaxRangeNodeDef> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xf94f2bbcu);

	public OnPassMaxRangeNodeDef(DDLObject ddl) : base(ddl) { }

	public new static OnPassMaxRangeNodeDef Create(DDLObject ddl) => new(ddl);
}

