// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xe21e4b9fu)]
public class OverrideHeroSpaceshipSpeedActionPrius : DDLObjectType, IDDLObjectType<OverrideHeroSpaceshipSpeedActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xe21e4b9fu);

	public OverrideHeroSpaceshipSpeedActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		NonFireSpeed = ddl.GetValue<float>(0x3c1dafddu, NonFireSpeed);
		FireSpeed = ddl.GetValue<float>(0xaf22b118u, FireSpeed);
		ThrustSpeed = ddl.GetValue<float>(0x158352ebu, ThrustSpeed);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Hero;

	[DDLRegistration(0x3c1dafddu)]
	public float NonFireSpeed { get; set; } = 28.00f;

	[DDLRegistration(0xaf22b118u)]
	public float FireSpeed { get; set; } = -1.00f;

	[DDLRegistration(0x158352ebu)]
	public float ThrustSpeed { get; set; } = 40.00f;

	public static OverrideHeroSpaceshipSpeedActionPrius Create(DDLObject ddl) => new(ddl);
}

