// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xd987e484u)]
public class PerfProfileLodMaxBase : DDLObjectType, IDDLObjectType<PerfProfileLodMaxBase> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xd987e484u);

	public PerfProfileLodMaxBase(DDLObject ddl) : base(ddl) { }

	public static PerfProfileLodMaxBase Create(DDLObject ddl) => new(ddl);
}

