// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x9432c468u)]
public class PhotomodeSelfieActivateEvent : EventBase, IDDLObjectType<PhotomodeSelfieActivateEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x9432c468u);

	public PhotomodeSelfieActivateEvent(DDLObject ddl) : base(ddl) { }

	public new static PhotomodeSelfieActivateEvent Create(DDLObject ddl) => new(ddl);
}

