// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xaaeac3c2u)]
public class PhysicsLauncherPrius : DDLObjectType, IDDLObjectType<PhysicsLauncherPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xaaeac3c2u);

	public PhysicsLauncherPrius(DDLObject ddl) : base(ddl) {
		LaunchTargets = ddl.GetObjects<PhysicsLauncherEntry>(0xcc9ad339u);
	}

	[DDLRegistration(0xcc9ad339u)]
	public List<PhysicsLauncherEntry?> LaunchTargets { get; set; } = [];

	public static PhysicsLauncherPrius Create(DDLObject ddl) => new(ddl);
}

