// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xe26ce1a5u)]
public class PickupShipMissilePrius : GamePickupItemPrius, IDDLObjectType<PickupShipMissilePrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xe26ce1a5u);

	public PickupShipMissilePrius(DDLObject ddl) : base(ddl) {
		AmmoAmount = ddl.GetValue<uint>(0xa56a6243u, AmmoAmount);
	}

	[DDLRegistration(0xa56a6243u)]
	public uint AmmoAmount { get; set; } = 0x00000001;

	public new static PickupShipMissilePrius Create(DDLObject ddl) => new(ddl);
}

