// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x57883b24u)]
public class PickupArachnodroidPrius : GamePickupItemPrius, IDDLObjectType<PickupArachnodroidPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x57883b24u);

	public PickupArachnodroidPrius(DDLObject ddl) : base(ddl) {
		PickupType = ddl.GetEnum<x6310440e>(0x467560d9u, x6310440eValues.Lookup);
		Duration = ddl.GetValue<float>(0x7c5e3db0u, Duration);
	}

	[DDLRegistration(0x467560d9u)]
	public x6310440e PickupType { get; set; } = x6310440e.Health;

	[DDLRegistration(0x7c5e3db0u)]
	public float Duration { get; set; } = 5.00f;

	public new static PickupArachnodroidPrius Create(DDLObject ddl) => new(ddl);
}

