// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xd1fccb5bu)]
public class POIAttributeDistanceTextNone : POIAttributeDistanceTextBase, IDDLObjectType<POIAttributeDistanceTextNone> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xd1fccb5bu);

	public POIAttributeDistanceTextNone(DDLObject ddl) : base(ddl) { }

	public new static POIAttributeDistanceTextNone Create(DDLObject ddl) => new(ddl);
}

