// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x062dfee2u)]
public class PressurePlateResetEvent : EventBase, IDDLObjectType<PressurePlateResetEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x062dfee2u);

	public PressurePlateResetEvent(DDLObject ddl) : base(ddl) { }

	public new static PressurePlateResetEvent Create(DDLObject ddl) => new(ddl);
}

