// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x22b993a6u)]
public class PrimStyleProgramatic : PrimStyleBase, IDDLObjectType<PrimStyleProgramatic> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x22b993a6u);

	public PrimStyleProgramatic(DDLObject ddl) : base(ddl) {
		Style = ddl.GetValue<uint>(0x2aee74abu, Style);
		PosA = ddl.GetObject<DDLVector3>(0x3ca9681eu);
		PosB = ddl.GetObject<DDLVector3>(0xa5a039a4u);
		Radius = ddl.GetValue<float>(0x0504203du, Radius);
	}

	[DDLRegistration(0x2aee74abu)]
	public uint Style { get; set; } = 0x00000000;

	[DDLRegistration(0x3ca9681eu)]
	public DDLVector3? PosA { get; set; } = default;

	[DDLRegistration(0xa5a039a4u)]
	public DDLVector3? PosB { get; set; } = default;

	[DDLRegistration(0x0504203du)]
	public float Radius { get; set; } = 0.00f;

	public new static PrimStyleProgramatic Create(DDLObject ddl) => new(ddl);
}

