// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xfbf05adfu)]
public class ProjectileBouncedEvent : ProjectileHitEvent, IDDLObjectType<ProjectileBouncedEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xfbf05adfu);

	public ProjectileBouncedEvent(DDLObject ddl) : base(ddl) { }

	public new static ProjectileBouncedEvent Create(DDLObject ddl) => new(ddl);
}

