// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x3d550502u)]
public class ProtoShotgunTendrilImpactEvent : EventBase, IDDLObjectType<ProtoShotgunTendrilImpactEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x3d550502u);

	public ProtoShotgunTendrilImpactEvent(DDLObject ddl) : base(ddl) {
		ReflectionDir = ddl.GetObject<DDLTransform>(0xeb9e8212u);
	}

	[DDLRegistration(0xeb9e8212u)]
	public DDLTransform? ReflectionDir { get; set; } = default;

	public new static ProtoShotgunTendrilImpactEvent Create(DDLObject ddl) => new(ddl);
}

