// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x394bde05u)]
public class PukeEndEvent : EventBase, IDDLObjectType<PukeEndEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x394bde05u);

	public PukeEndEvent(DDLObject ddl) : base(ddl) {
		Locator = ddl.GetString(0x7bac1d57) ?? Locator;
	}

	[DDLRegistration(0x7bac1d57u)]
	public string? Locator { get; set; } = default;

	public new static PukeEndEvent Create(DDLObject ddl) => new(ddl);
}

