// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xb3c1d029u)]
public class PulseMineSpawnData : AttachableShotSpawnData, IDDLObjectType<PulseMineSpawnData> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xb3c1d029u);

	public PulseMineSpawnData(DDLObject ddl) : base(ddl) {
		ConfigPath = ddl.GetValue<uint>(0x227a02fdu, ConfigPath);
		SubShotAsset = ddl.GetValue<uint>(0x1138b034u, SubShotAsset);
		ShotsToSpawn = ddl.GetValue<byte>(0x1731e614u, ShotsToSpawn);
		ShotInterval = ddl.GetValue<float>(0x09a94546u, ShotInterval);
	}

	[DDLRegistration(0x227a02fdu)]
	public uint ConfigPath { get; set; } = 0x00000000;

	[DDLRegistration(0x1138b034u)]
	public uint SubShotAsset { get; set; } = 0x00000000;

	[DDLRegistration(0x1731e614u)]
	public byte ShotsToSpawn { get; set; } = 0x03;

	[DDLRegistration(0x09a94546u)]
	public float ShotInterval { get; set; } = 1.00f;

	public new static PulseMineSpawnData Create(DDLObject ddl) => new(ddl);
}

