// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x5623c292u)]
public class PythonFunctionDocumentation : DDLObjectType, IDDLObjectType<PythonFunctionDocumentation> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x5623c292u);

	public PythonFunctionDocumentation(DDLObject ddl) : base(ddl) {
		Description = ddl.GetString(0xe03811fd) ?? Description;
		Label = ddl.GetString(0x17f49c29) ?? Label;
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		Type = ddl.GetString(0xbc4e9799) ?? Type;
		ParameterNames = ddl.GetStrings(0x9381e4feu, ParameterNames);
		ParametersSignature = ddl.GetString(0x17313259) ?? ParametersSignature;
		ParameterTypes = ddl.GetStrings(0x3882248eu, ParameterTypes);
		ReturnType = ddl.GetString(0x27fe850a) ?? ReturnType;
	}

	[DDLRegistration(0xe03811fdu)]
	public string? Description { get; set; } = default;

	[DDLRegistration(0x17f49c29u)]
	public string? Label { get; set; } = default;

	[DDLRegistration(0x6eb3beb6u)]
	public string? Name { get; set; } = default;

	[DDLRegistration(0xbc4e9799u)]
	public string? Type { get; set; } = default;

	[DDLRegistration(0x9381e4feu)]
	public List<string?> ParameterNames { get; set; } = [];

	[DDLRegistration(0x17313259u)]
	public string? ParametersSignature { get; set; } = default;

	[DDLRegistration(0x3882248eu)]
	public List<string?> ParameterTypes { get; set; } = [];

	[DDLRegistration(0x27fe850au)]
	public string? ReturnType { get; set; } = default;

	public static PythonFunctionDocumentation Create(DDLObject ddl) => new(ddl);
}

