// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x26714bf7u)]
public class RecoilCameraShakeItem : DDLObjectType, IDDLObjectType<RecoilCameraShakeItem> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x26714bf7u);

	public RecoilCameraShakeItem(DDLObject ddl) : base(ddl) {
		CameraShake = ddl.GetObject<RecoilCameraShake>(0xefd546cau);
	}

	[DDLRegistration(0xefd546cau)]
	public RecoilCameraShake? CameraShake { get; set; } = default;

	public static RecoilCameraShakeItem Create(DDLObject ddl) => new(ddl);
}

