// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xd292fe83u)]
public class RecoveryLedgeLowerClearanceParams : DDLObjectType, IDDLObjectType<RecoveryLedgeLowerClearanceParams> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xd292fe83u);

	public RecoveryLedgeLowerClearanceParams(DDLObject ddl) : base(ddl) {
		MinHeight = ddl.GetValue<float>(0x9ed620e3u, MinHeight);
		MinRearHeight = ddl.GetValue<float>(0x410b47b3u, MinRearHeight);
	}

	[DDLRegistration(0x9ed620e3u, description: "Only enable auto recovery ledges when the surface is at least this far below the wall check.")]
	public float MinHeight { get; set; } = 1.75f;

	[DDLRegistration(0x410b47b3u, description: "Only enable auto recovery ledges when ground is at least this far below the wall check and the ledge is behind us.")]
	public float MinRearHeight { get; set; } = 1.75f;

	public static RecoveryLedgeLowerClearanceParams Create(DDLObject ddl) => new(ddl);
}

