// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xdbc47693u)]
public class RegionNamedLink : DDLObjectType, IDDLObjectType<RegionNamedLink> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xdbc47693u);

	public RegionNamedLink(DDLObject ddl) : base(ddl) {
		Id = ddl.GetValue<RivetAssetId>(0x8a514a8du, Id);
		Order = ddl.GetValue<float>(0xec7a5f59u, Order);
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		Link = ddl.GetString(0x063c5941) ?? Link;
		GameData = ddl.GetDictionary<RivetAssetId, DDLStructInst>(0xa1f1eb12, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<DDLStructInst>(mapId));
	}

	[DDLRegistration(0x8a514a8du)]
	public RivetAssetId Id { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0xec7a5f59u)]
	public float Order { get; set; } = 0.00f;

	[DDLRegistration(0x6eb3beb6u)]
	public string? Name { get; set; } = default;

	[DDLRegistration(0x063c5941u)]
	public string? Link { get; set; } = default;

	[DDLRegistration(0xa1f1eb12u)]
	public Dictionary<RivetAssetId, DDLStructInst?> GameData { get; set; } = [];

	public static RegionNamedLink Create(DDLObject ddl) => new(ddl);
}

