// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x2459666du)]
public class RenderFlags : DDLObjectType, IDDLObjectType<RenderFlags> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x2459666du);

	public RenderFlags(DDLObject ddl) : base(ddl) {
		Hibernate = ddl.GetValue<bool>(0x6f8e6b06u, Hibernate);
		SkipDecals = ddl.GetValue<bool>(0x7de13186u, SkipDecals);
		SkipStaticDecals = ddl.GetValue<bool>(0x19ffacecu, SkipStaticDecals);
		SkipEnvProbe = ddl.GetValue<bool>(0xf219f226u, SkipEnvProbe);
		OnlyLightCapture = ddl.GetValue<bool>(0x1559dec2u, OnlyLightCapture);
		NoEmbeddedSamples = ddl.GetValue<bool>(0x28b04558u, NoEmbeddedSamples);
		SkipImpostor = ddl.GetValue<bool>(0xffc4e1c0u, SkipImpostor);
		SkipShadowCast = ddl.GetValue<bool>(0x40b0e1cau, SkipShadowCast);
		IgnoreDepth = ddl.GetValue<bool>(0xbd1d2439u, IgnoreDepth);
		ReverseIndoorStatus = ddl.GetValue<bool>(0xa242edf0u, ReverseIndoorStatus);
		NeverOcclude = ddl.GetValue<bool>(0xa65f70d7u, NeverOcclude);
		RenderAsWireframe = ddl.GetValue<bool>(0x11f20a7cu, RenderAsWireframe);
	}

	[DDLRegistration(0x6f8e6b06u, description: "Allows a model to render beyond the streaming distance")]
	public bool Hibernate { get; set; } = false;

	[DDLRegistration(0x7de13186u, "Skip Decals")]
	public bool SkipDecals { get; set; } = false;

	[DDLRegistration(0x19ffacecu, "Skip Static Decals", "If set, the model will not receive static decals.")]
	public bool SkipStaticDecals { get; set; } = false;

	[DDLRegistration(0xf219f226u, "Skip Light Capture")]
	public bool SkipEnvProbe { get; set; } = false;

	[DDLRegistration(0x1559dec2u, "Only Light Capture")]
	public bool OnlyLightCapture { get; set; } = false;

	[DDLRegistration(0x28b04558u, "No Embedded Samples")]
	public bool NoEmbeddedSamples { get; set; } = false;

	[DDLRegistration(0xffc4e1c0u, "Skip Impostor")]
	public bool SkipImpostor { get; set; } = false;

	[DDLRegistration(0x40b0e1cau, "Skip Shadow Cast")]
	public bool SkipShadowCast { get; set; } = false;

	[DDLRegistration(0xbd1d2439u, "Ignore Depth When Blended", "If set and the model is blended, the model will neither test nor write depth.")]
	public bool IgnoreDepth { get; set; } = false;

	[DDLRegistration(0xa242edf0u, "Flip Indoor Status")]
	public bool ReverseIndoorStatus { get; set; } = false;

	[DDLRegistration(0xa65f70d7u, "Never Occlude")]
	public bool NeverOcclude { get; set; } = false;

	[DDLRegistration(0x11f20a7cu, "Always render as wireframe")]
	public bool RenderAsWireframe { get; set; } = false;

	public static RenderFlags Create(DDLObject ddl) => new(ddl);
}

