// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x8a5b85edu)]
public class RewardShipSkinConfig : ConfigBase, IDDLObjectType<RewardShipSkinConfig> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x8a5b85edu);

	public RewardShipSkinConfig(DDLObject ddl) : base(ddl) {
		Skins = ddl.GetObjects<ShipSkinMaterialGroup>(0xf85047c1u);
	}

	[DDLRegistration(0xf85047c1u)]
	public List<ShipSkinMaterialGroup?> Skins { get; set; } = [];

	public new static RewardShipSkinConfig Create(DDLObject ddl) => new(ddl);
}

