// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x1883f87au)]
public class RicochetReturnedEvent : RicochetBaseEvent, IDDLObjectType<RicochetReturnedEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x1883f87au);

	public RicochetReturnedEvent(DDLObject ddl) : base(ddl) { }

	public new static RicochetReturnedEvent Create(DDLObject ddl) => new(ddl);
}

