// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x6171e75du)]
public class RYNOPortalObjectImpactEvent : EventBase, IDDLObjectType<RYNOPortalObjectImpactEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x6171e75du);

	public RYNOPortalObjectImpactEvent(DDLObject ddl) : base(ddl) {
		InAir = ddl.GetValue<bool>(0xebc689d9u, InAir);
		DoesLanding = ddl.GetValue<bool>(0xaf7a201fu, DoesLanding);
		PortalSize = ddl.GetEnum<xbf5ff3c6>(0x52a18d8cu, xbf5ff3c6Values.Lookup);
		ReflectionDir = ddl.GetObject<DDLTransform>(0xeb9e8212u);
		VersionIndex = ddl.GetValue<byte>(0x6e091c9au, VersionIndex);
	}

	[DDLRegistration(0xebc689d9u)]
	public bool InAir { get; set; } = false;

	[DDLRegistration(0xaf7a201fu)]
	public bool DoesLanding { get; set; } = false;

	[DDLRegistration(0x52a18d8cu)]
	public xbf5ff3c6 PortalSize { get; set; } = xbf5ff3c6.Small;

	[DDLRegistration(0xeb9e8212u)]
	public DDLTransform? ReflectionDir { get; set; } = default;

	[DDLRegistration(0x6e091c9au)]
	public byte VersionIndex { get; set; } = 0x00;

	public new static RYNOPortalObjectImpactEvent Create(DDLObject ddl) => new(ddl);
}

