// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xa0256dc5u)]
public class ScriptGraphLibraryMimeData : DDLObjectType, IDDLObjectType<ScriptGraphLibraryMimeData> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xa0256dc5u);

	public ScriptGraphLibraryMimeData(DDLObject ddl) : base(ddl) {
		ScriptGraphData = ddl.GetObjects<ScriptGraphLibraryData>(0xaad42c74u);
	}

	[DDLRegistration(0xaad42c74u)]
	public List<ScriptGraphLibraryData?> ScriptGraphData { get; set; } = [];

	public static ScriptGraphLibraryMimeData Create(DDLObject ddl) => new(ddl);
}

