// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xa06cebf2u)]
public class ScriptVarWatchVec : DDLObjectType, IDDLObjectType<ScriptVarWatchVec> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xa06cebf2u);

	public ScriptVarWatchVec(DDLObject ddl) : base(ddl) {
		Value = ddl.GetObject<DDLVector3>(0x042494f5u);
	}

	[DDLRegistration(0x042494f5u)]
	public DDLVector3? Value { get; set; } = default;

	public static ScriptVarWatchVec Create(DDLObject ddl) => new(ddl);
}

