// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xd25e71fau)]
public class SetWeaponModCountActionPrius : DDLObjectType, IDDLObjectType<SetWeaponModCountActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xd25e71fau);

	public SetWeaponModCountActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
		WeaponConfig = ddl.GetValue<RivetAssetId>(0xb72a0e33u, WeaponConfig);
		ModTileIndex = ddl.GetEnum<x1b1e7614>(0x6623f977u, x1b1e7614Values.Lookup);
		ModCount = ddl.GetValue<uint>(0xb86c3a48u, ModCount);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.Weapon;

	[DDLRegistration(0xb72a0e33u, "Weapon Item Config")]
	public RivetAssetId WeaponConfig { get; set; } = default;

	[DDLRegistration(0x6623f977u, "Mod Tile Index", "Tile index of the mod to set. Will use the input index if one is specified on the node.")]
	public x1b1e7614 ModTileIndex { get; set; } = x1b1e7614.Empty;

	[DDLRegistration(0xb86c3a48u, "Mod Count", "The count to set the mod to. Will use the input count if one is specified on the node.")]
	public uint ModCount { get; set; } = 0x00000000;

	public static SetWeaponModCountActionPrius Create(DDLObject ddl) => new(ddl);
}

