// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xb80dcc03u)]
public class ShotTunnelerMeleePrius : BasicBulletPrius, IDDLObjectType<ShotTunnelerMeleePrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xb80dcc03u);

	public ShotTunnelerMeleePrius(DDLObject ddl) : base(ddl) { }

	public new static ShotTunnelerMeleePrius Create(DDLObject ddl) => new(ddl);
}

