// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x52e1a6a9u)]
public class ShotProtoGrenadePrius : GrenadeShotPrius, IDDLObjectType<ShotProtoGrenadePrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x52e1a6a9u);

	public ShotProtoGrenadePrius(DDLObject ddl) : base(ddl) {
		ShardDetonationData = ddl.GetObject<ShardDetonationData>(0xec3e5404u);
	}

	[DDLRegistration(0xec3e5404u)]
	public ShardDetonationData? ShardDetonationData { get; set; } = default;

	public new static ShotProtoGrenadePrius Create(DDLObject ddl) => new(ddl);
}

