// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x5b335fabu)]
public class ShotGrenadeHazardPrius : GrenadeShotGamePrius, IDDLObjectType<ShotGrenadeHazardPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x5b335fabu);

	public ShotGrenadeHazardPrius(DDLObject ddl) : base(ddl) {
		HazardDuration = ddl.GetValue<float>(0x591d8238u, HazardDuration);
		HazardRadius = ddl.GetValue<float>(0xb1b21983u, HazardRadius);
		HazardDamageAmount = ddl.GetValue<float>(0x20840b08u, HazardDamageAmount);
		HazardDamageInterval = ddl.GetValue<float>(0x955e5c2au, HazardDamageInterval);
		CameraShake = ddl.GetValue<RivetAssetId>(0xefd546cau, CameraShake);
	}

	[DDLRegistration(0x591d8238u)]
	public float HazardDuration { get; set; } = 4.00f;

	[DDLRegistration(0xb1b21983u)]
	public float HazardRadius { get; set; } = 3.00f;

	[DDLRegistration(0x20840b08u)]
	public float HazardDamageAmount { get; set; } = 5.00f;

	[DDLRegistration(0x955e5c2au)]
	public float HazardDamageInterval { get; set; } = 1.00f;

	[DDLRegistration(0xefd546cau)]
	public RivetAssetId CameraShake { get; set; } = default;

	public new static ShotGrenadeHazardPrius Create(DDLObject ddl) => new(ddl);
}

