// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x55941c57u)]
public class ShotMotionVolcanicEruptorPrius : GrenadeShotMotionPrius, IDDLObjectType<ShotMotionVolcanicEruptorPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x55941c57u);

	public ShotMotionVolcanicEruptorPrius(DDLObject ddl) : base(ddl) { }

	public new static ShotMotionVolcanicEruptorPrius Create(DDLObject ddl) => new(ddl);
}

