// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x18ae9d4bu)]
public class ShrubberyBreakoutExplosionStartEvent : EventBase, IDDLObjectType<ShrubberyBreakoutExplosionStartEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x18ae9d4bu);

	public ShrubberyBreakoutExplosionStartEvent(DDLObject ddl) : base(ddl) { }

	public new static ShrubberyBreakoutExplosionStartEvent Create(DDLObject ddl) => new(ddl);
}

