// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xbc6f4b76u)]
public class SimpleSplasherPrius : DDLObjectType, IDDLObjectType<SimpleSplasherPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xbc6f4b76u);

	public SimpleSplasherPrius(DDLObject ddl) : base(ddl) {
		CollisionRadius = ddl.GetValue<float>(0x7d546bbau, CollisionRadius);
	}

	[DDLRegistration(0x7d546bbau, description: "Radius for the collision test. (meters)")]
	public float CollisionRadius { get; set; } = 0.25f;

	public static SimpleSplasherPrius Create(DDLObject ddl) => new(ddl);
}

