// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xdaf46a95u)]
public class SoundPropagation2BezierDef : DDLObjectType, IDDLObjectType<SoundPropagation2BezierDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xdaf46a95u);

	public SoundPropagation2BezierDef(DDLObject ddl) : base(ddl) {
		Slope = ddl.GetValue<float>(0x419f8944u, Slope);
	}

	[DDLRegistration(0x419f8944u, description: "slope to use for the curve. 1 is constant full gain, 0 behaves same as linear, -1 is constant minimum gain.")]
	public float Slope { get; set; } = 0.50f;

	public static SoundPropagation2BezierDef Create(DDLObject ddl) => new(ddl);
}

