// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xb1135ca4u)]
public class StatusEffectDamageStopEvent : EventBase, IDDLObjectType<StatusEffectDamageStopEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xb1135ca4u);

	public StatusEffectDamageStopEvent(DDLObject ddl) : base(ddl) { }

	public new static StatusEffectDamageStopEvent Create(DDLObject ddl) => new(ddl);
}

