// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xaaba2dc0u)]
public class StopBlockingEvent : EventBase, IDDLObjectType<StopBlockingEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xaaba2dc0u);

	public StopBlockingEvent(DDLObject ddl) : base(ddl) {
		MovingDude = ddl.GetValue<uint>(0x8887fd09u, MovingDude);
		DesiredVelocity = ddl.GetObject<DDLVector3>(0x1442cb45u);
	}

	[DDLRegistration(0x8887fd09u)]
	public uint MovingDude { get; set; } = 0x00000000;

	[DDLRegistration(0x1442cb45u)]
	public DDLVector3? DesiredVelocity { get; set; } = default;

	public new static StopBlockingEvent Create(DDLObject ddl) => new(ddl);
}

