// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xbf0155a2u)]
public class SyncActorPosRotPrius : DDLObjectType, IDDLObjectType<SyncActorPosRotPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xbf0155a2u);

	public SyncActorPosRotPrius(DDLObject ddl) : base(ddl) {
		MaxUpdateRate = ddl.GetValue<float>(0xc7c112deu, MaxUpdateRate);
		SyncRot = ddl.GetValue<bool>(0xb88f83abu, SyncRot);
	}

	[DDLRegistration(0xc7c112deu)]
	public float MaxUpdateRate { get; set; } = 1.00f;

	[DDLRegistration(0xb88f83abu)]
	public bool SyncRot { get; set; } = true;

	public static SyncActorPosRotPrius Create(DDLObject ddl) => new(ddl);
}

