// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xe761da8eu)]
public class SyncedBoxActivateEvent : EventBase, IDDLObjectType<SyncedBoxActivateEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xe761da8eu);

	public SyncedBoxActivateEvent(DDLObject ddl) : base(ddl) { }

	public new static SyncedBoxActivateEvent Create(DDLObject ddl) => new(ddl);
}

