// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xf107c379u)]
public class TargetCheckOwnerPrius : TargetCheckBasePrius, IDDLObjectType<TargetCheckOwnerPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xf107c379u);

	public TargetCheckOwnerPrius(DDLObject ddl) : base(ddl) { }

	public new static TargetCheckOwnerPrius Create(DDLObject ddl) => new(ddl);
}

