// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x9fe809bfu)]
public class TestSubstructUsage : DDLObjectType, IDDLObjectType<TestSubstructUsage> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x9fe809bfu);

	public TestSubstructUsage(DDLObject ddl) : base(ddl) {
		SubStruct1 = ddl.GetObject<TestSubstructBase1>(0x4f04bc15u);
		SubStruct2 = ddl.GetObject<TestSubstructBase1>(0xd60dedafu);
		SubStruct3 = ddl.GetObject<TestSubstructBase2>(0xa10add39u);
		SubStruct4 = ddl.GetObject<TestSubstructBase3>(0x3f6e489au);
	}

	[DDLRegistration(0x4f04bc15u)]
	public TestSubstructBase1? SubStruct1 { get; set; } = default;

	[DDLRegistration(0xd60dedafu)]
	public TestSubstructBase1? SubStruct2 { get; set; } = default;

	[DDLRegistration(0xa10add39u)]
	public TestSubstructBase2? SubStruct3 { get; set; } = default;

	[DDLRegistration(0x3f6e489au)]
	public TestSubstructBase3? SubStruct4 { get; set; } = default;

	public static TestSubstructUsage Create(DDLObject ddl) => new(ddl);
}

