// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x07a43eafu)]
public class ThrowerODReleaseEvent : EventBase, IDDLObjectType<ThrowerODReleaseEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x07a43eafu);

	public ThrowerODReleaseEvent(DDLObject ddl) : base(ddl) { }

	public new static ThrowerODReleaseEvent Create(DDLObject ddl) => new(ddl);
}

