// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x879bd1f3u)]
public class TriggerEffectArrayItem : DDLObjectType, IDDLObjectType<TriggerEffectArrayItem> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x879bd1f3u);

	public TriggerEffectArrayItem(DDLObject ddl) : base(ddl) {
		EffectType = ddl.GetEnum<x60ab12b0>(0x609bd7dbu, x60ab12b0Values.Lookup);
		Triggers = ddl.GetEnum<x626794b4>(0xf4cf343du, x626794b4Values.Lookup);
		Enabled = ddl.GetValue<bool>(0x5113d8bcu, Enabled);
		TriggerEffectConfig = ddl.GetValue<RivetAssetId>(0x336655bau, TriggerEffectConfig);
	}

	[DDLRegistration(0x609bd7dbu)]
	public x60ab12b0 EffectType { get; set; } = x60ab12b0.None;

	[DDLRegistration(0xf4cf343du)]
	public x626794b4 Triggers { get; set; } = x626794b4.TriggerLeft;

	[DDLRegistration(0x5113d8bcu)]
	public bool Enabled { get; set; } = true;

	[DDLRegistration(0x336655bau, description: "Trigger effect config for this type")]
	public RivetAssetId TriggerEffectConfig { get; set; } = default;

	public static TriggerEffectArrayItem Create(DDLObject ddl) => new(ddl);
}

