// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xe7ca40e1u)]
public class TriggerEffectDataVibration : TriggerEffectDataBase, IDDLObjectType<TriggerEffectDataVibration> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xe7ca40e1u);

	public TriggerEffectDataVibration(DDLObject ddl) : base(ddl) {
		PositionBegin = ddl.GetValue<uint>(0xca8006c1u, PositionBegin);
		Frequency = ddl.GetValue<uint>(0xa482271fu, Frequency);
	}

	[DDLRegistration(0xca8006c1u, description: "0 = Not pressed at all. 9 = Fully pressed.")]
	public uint PositionBegin { get; set; } = 0x00000000;

	[DDLRegistration(0xa482271fu, description: "Value in Hz. Range [0, 255].")]
	public uint Frequency { get; set; } = 0x00000000;

	public new static TriggerEffectDataVibration Create(DDLObject ddl) => new(ddl);
}

