// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x07aefcd3u)]
public class TriggerConditionAlwaysPrius : DDLObjectType, IDDLObjectType<TriggerConditionAlwaysPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x07aefcd3u);

	public TriggerConditionAlwaysPrius(DDLObject ddl) : base(ddl) { }

	public static TriggerConditionAlwaysPrius Create(DDLObject ddl) => new(ddl);
}

