// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x9b171e47u)]
public class TurretIonCannonShotMotionPrius : BasicShotMotionPrius, IDDLObjectType<TurretIonCannonShotMotionPrius> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x9b171e47u);

	public TurretIonCannonShotMotionPrius(DDLObject ddl) : base(ddl) { }

	public new static TurretIonCannonShotMotionPrius Create(DDLObject ddl) => new(ddl);
}

