// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x5936807au)]
public class UDSObjectiveEndEvent : ActivityEndEvent, IDDLObjectType<UDSObjectiveEndEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x5936807au);

	public UDSObjectiveEndEvent(DDLObject ddl) : base(ddl) { }

	public new static UDSObjectiveEndEvent Create(DDLObject ddl) => new(ddl);
}

