// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x718fc688u)]
public class UI_AnimClipGroupDef : DDLObjectType, IDDLObjectType<UI_AnimClipGroupDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x718fc688u);

	public UI_AnimClipGroupDef(DDLObject ddl) : base(ddl) {
		Id = ddl.GetValue<RivetAssetId>(0x8a514a8du, Id);
		Name = ddl.GetString(0x6eb3beb6) ?? Name;
		Entries = ddl.GetObjects<UI_AnimClipGroupEntryDef>(0x2c12d0fdu);
	}

	[DDLRegistration(0x8a514a8du)]
	public RivetAssetId Id { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0x6eb3beb6u)]
	public string? Name { get; set; } = default;

	[DDLRegistration(0x2c12d0fdu)]
	public List<UI_AnimClipGroupEntryDef?> Entries { get; set; } = [];

	public static UI_AnimClipGroupDef Create(DDLObject ddl) => new(ddl);
}

