// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x1c6188d2u)]
public class UIArenaWaveActionPrius : DDLObjectType, IDDLObjectType<UIArenaWaveActionPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x1c6188d2u);

	public UIArenaWaveActionPrius(DDLObject ddl) : base(ddl) {
		ActionType = ddl.GetEnum<x10228b34>(0x874b2194u, x10228b34Values.Lookup);
	}

	[DDLRegistration(0x874b2194u)]
	public x10228b34 ActionType { get; set; } = x10228b34.UI;

	public static UIArenaWaveActionPrius Create(DDLObject ddl) => new(ddl);
}

