// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x1bdd62a1u)]
public class UIControllerDisconnectShowEvent : EventBase, IDDLObjectType<UIControllerDisconnectShowEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x1bdd62a1u);

	public UIControllerDisconnectShowEvent(DDLObject ddl) : base(ddl) { }

	public new static UIControllerDisconnectShowEvent Create(DDLObject ddl) => new(ddl);
}

