// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xce839ffbu)]
public class UITutorialAdvanceEvent : EventBase, IDDLObjectType<UITutorialAdvanceEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xce839ffbu);

	public UITutorialAdvanceEvent(DDLObject ddl) : base(ddl) { }

	public new static UITutorialAdvanceEvent Create(DDLObject ddl) => new(ddl);
}

