// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xa8fe65f6u)]
public class UserSystemSettings : DDLObjectType, IDDLObjectType<UserSystemSettings> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xa8fe65f6u);

	public UserSystemSettings(DDLObject ddl) : base(ddl) {
		MaxPerUserBindingsConfigCount = ddl.GetValue<int>(0x287bdb12u, MaxPerUserBindingsConfigCount);
		MaxPerUserControlGroupCount = ddl.GetValue<int>(0x0ec0fc20u, MaxPerUserControlGroupCount);
		MaxPerUserControlCount = ddl.GetValue<int>(0x8fc95308u, MaxPerUserControlCount);
		MaxPerUserFinalizeStepCount = ddl.GetValue<int>(0x345cdef5u, MaxPerUserFinalizeStepCount);
		MaxPlayingUsers = ddl.GetValue<byte>(0x8d01af3au, MaxPlayingUsers);
		UsePureUserName = ddl.GetValue<bool>(0xf74f691bu, UsePureUserName);
		SetSignedInAsPlaying = ddl.GetValue<bool>(0x8c914232u, SetSignedInAsPlaying);
		GuestsEnabled = ddl.GetValue<bool>(0x4e21d3d8u, GuestsEnabled);
		AllocInstanceId = ddl.GetValue<bool>(0xabdb326fu, AllocInstanceId);
		FinalUseKeyboard = ddl.GetValue<bool>(0x5717483du, FinalUseKeyboard);
		FinalUseMouse = ddl.GetValue<bool>(0x9d9990c4u, FinalUseMouse);
		UseDefaultUserName = ddl.GetValue<bool>(0xe63216f7u, UseDefaultUserName);
	}

	[DDLRegistration(0x287bdb12u)]
	public int MaxPerUserBindingsConfigCount { get; set; } = 8;

	[DDLRegistration(0x0ec0fc20u)]
	public int MaxPerUserControlGroupCount { get; set; } = 16;

	[DDLRegistration(0x8fc95308u)]
	public int MaxPerUserControlCount { get; set; } = 256;

	[DDLRegistration(0x345cdef5u)]
	public int MaxPerUserFinalizeStepCount { get; set; } = 8;

	[DDLRegistration(0x8d01af3au)]
	public byte MaxPlayingUsers { get; set; } = 0x02;

	[DDLRegistration(0xf74f691bu)]
	public bool UsePureUserName { get; set; } = false;

	[DDLRegistration(0x8c914232u)]
	public bool SetSignedInAsPlaying { get; set; } = true;

	[DDLRegistration(0x4e21d3d8u)]
	public bool GuestsEnabled { get; set; } = true;

	[DDLRegistration(0xabdb326fu)]
	public bool AllocInstanceId { get; set; } = false;

	[DDLRegistration(0x5717483du)]
	public bool FinalUseKeyboard { get; set; } = true;

	[DDLRegistration(0x9d9990c4u)]
	public bool FinalUseMouse { get; set; } = true;

	[DDLRegistration(0xe63216f7u)]
	public bool UseDefaultUserName { get; set; } = false;

	public static UserSystemSettings Create(DDLObject ddl) => new(ddl);
}

