// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xf07da320u)]
public class VanityCategoryListItem : DDLObjectType, IDDLObjectType<VanityCategoryListItem> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xf07da320u);

	public VanityCategoryListItem(DDLObject ddl) : base(ddl) {
		VanityCategory = ddl.GetEnum<xa3499465>(0x916b9072u, xa3499465Values.Lookup);
		VanityCategoryLocTag = ddl.GetString(0x09f47308) ?? VanityCategoryLocTag;
		VanityMenu = ddl.GetEnum<xca348341>(0xcbbe6a10u, xca348341Values.Lookup);
		ShowOnVendorMenu = ddl.GetValue<bool>(0x159446acu, ShowOnVendorMenu);
	}

	[DDLRegistration(0x916b9072u, "Category", "Category Type")]
	public xa3499465 VanityCategory { get; set; } = xa3499465.Head;

	[DDLRegistration(0x09f47308u, "Category LocTag", "Localization tag for category")]
	public string? VanityCategoryLocTag { get; set; } = default;

	[DDLRegistration(0xcbbe6a10u, "Category Menu", "Category Menu")]
	public xca348341 VanityMenu { get; set; } = xca348341.None;

	[DDLRegistration(0x159446acu, "Show on Vendor", "Show on Vendor Menu")]
	public bool ShowOnVendorMenu { get; set; } = true;

	public static VanityCategoryListItem Create(DDLObject ddl) => new(ddl);
}

