// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x4d121082u)]
public class VanitySetConfig : ConfigBase, IDDLObjectType<VanitySetConfig> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x4d121082u);

	public VanitySetConfig(DDLObject ddl) : base(ddl) {
		DisplayName = ddl.GetString(0xeaf33243) ?? DisplayName;
		VanityBundles = ddl.GetValues<RivetAssetId>(0x229d71b5u, VanityBundles);
		DefaultColor = ddl.GetValue<byte>(0x7ccd1470u, DefaultColor);
		IsDuplicate = ddl.GetValue<bool>(0xa6036107u, IsDuplicate);
		OriginalSet = ddl.GetValue<RivetAssetId>(0x254f8245u, OriginalSet);
		Perk = ddl.GetObject<VanityPerkBase>(0xf39e155fu);
	}

	[DDLRegistration(0xeaf33243u)]
	public string? DisplayName { get; set; } = default;

	[DDLRegistration(0x229d71b5u, "Vanity Bundle Configs")]
	public List<RivetAssetId> VanityBundles { get; set; } = [];

	[DDLRegistration(0x7ccd1470u, "Default Vanity Color")]
	public byte DefaultColor { get; set; } = 0x00;

	[DDLRegistration(0xa6036107u, "Is Duplicate")]
	public bool IsDuplicate { get; set; } = false;

	[DDLRegistration(0x254f8245u, "Original Set", "Since this is a duplicate")]
	public RivetAssetId OriginalSet { get; set; } = default;

	[DDLRegistration(0xf39e155fu)]
	public VanityPerkBase? Perk { get; set; } = default;

	public new static VanitySetConfig Create(DDLObject ddl) => new(ddl);
}

