// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x824a60d9u)]
public class VehicleMergeDistance : DDLObjectType, IDDLObjectType<VehicleMergeDistance> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0x824a60d9u);

	public VehicleMergeDistance(DDLObject ddl) : base(ddl) {
		Speed = ddl.GetValue<float>(0x16753237u, Speed);
		Distance = ddl.GetValue<float>(0xe69327f1u, Distance);
	}

	[DDLRegistration(0x16753237u, description: "When the vehicle is moving at this speed, use the corresponding distance.")]
	public float Speed { get; set; } = 0.00f;

	[DDLRegistration(0xe69327f1u, description: "The distance along the current lane's direction that a vehicle can use to merge onto another lane.")]
	public float Distance { get; set; } = 0.00f;

	public static VehicleMergeDistance Create(DDLObject ddl) => new(ddl);
}

