// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xae4502bdu)]
public class VelocityFromTrajectory : GrenadeVelocityMode, IDDLObjectType<VelocityFromTrajectory> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xae4502bdu);

	public VelocityFromTrajectory(DDLObject ddl) : base(ddl) { }

	public new static VelocityFromTrajectory Create(DDLObject ddl) => new(ddl);
}

