// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xe94a3eccu)]
public class VisualEffectPostRenderNode : DDLObjectType, IDDLObjectType<VisualEffectPostRenderNode> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xe94a3eccu);

	public VisualEffectPostRenderNode(DDLObject ddl) : base(ddl) {
		NodeId = ddl.GetValue<RivetAssetId>(0x371a59e0u, NodeId);
		XPos = ddl.GetValue<int>(0xf88aee81u, XPos);
		YPos = ddl.GetValue<int>(0x403689e4u, YPos);
		DisplayName = ddl.GetString(0xeaf33243) ?? DisplayName;
		ConnectedInputs = ddl.GetObjects<VisualEffectNodeConnectedInputPort>(0x8ca57bf5u);
		ConnectedOutputs = ddl.GetObjects<VisualEffectNodeConnectedOutputPort>(0x824bee0eu);
		RenderType = ddl.GetEnum<x9a2e0494>(0xb0ef7733u, x9a2e0494Values.Lookup);
		BlendStyle = ddl.GetEnum<BlendStyle>(0xb34024eau, BlendStyleValues.Lookup);
	}

	[DDLRegistration(0x371a59e0u)]
	public RivetAssetId NodeId { get; set; } = new RivetAssetId(0x0000000000000000);

	[DDLRegistration(0xf88aee81u)]
	public int XPos { get; set; } = 0;

	[DDLRegistration(0x403689e4u)]
	public int YPos { get; set; } = 0;

	[DDLRegistration(0xeaf33243u, "Name")]
	public string? DisplayName { get; set; } = default;

	[DDLRegistration(0x8ca57bf5u)]
	public List<VisualEffectNodeConnectedInputPort?> ConnectedInputs { get; set; } = [];

	[DDLRegistration(0x824bee0eu)]
	public List<VisualEffectNodeConnectedOutputPort?> ConnectedOutputs { get; set; } = [];

	[DDLRegistration(0xb0ef7733u, "Render Type")]
	public x9a2e0494 RenderType { get; set; } = x9a2e0494.OffscreenHalf;

	[DDLRegistration(0xb34024eau, "Blend Style")]
	public BlendStyle BlendStyle { get; set; } = BlendStyle.Alpha;

	public static VisualEffectPostRenderNode Create(DDLObject ddl) => new(ddl);
}

