// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xdbd1112au)]
public class WalkingArchivesJointIKPrius : DDLObjectType, IDDLObjectType<WalkingArchivesJointIKPrius> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xdbd1112au);

	public WalkingArchivesJointIKPrius(DDLObject ddl) : base(ddl) {
		FootJoint = ddl.GetStrings(0x351d165eu);
		IKChainID = ddl.GetStrings(0x81b8f1aeu);
		MoveDriver = ddl.GetString(0x8bc6d4e3) ?? MoveDriver;
		CameraShake = ddl.GetValue<RivetAssetId>(0xefd546cau, CameraShake);
		CameraShakeInnerRadius = ddl.GetValue<float>(0x4ca6dc25u, CameraShakeInnerRadius);
		CameraShakeOuterRadius = ddl.GetValue<float>(0x42b3a496u, CameraShakeOuterRadius);
		FootDamageRadius = ddl.GetValue<float>(0x325d203au, FootDamageRadius);
	}

	[DDLRegistration(0x351d165eu)]
	public List<string?> FootJoint { get; set; } = [];

	[DDLRegistration(0x81b8f1aeu)]
	public List<string?> IKChainID { get; set; } = [];

	[DDLRegistration(0x8bc6d4e3u)]
	public string? MoveDriver { get; set; } = default;

	[DDLRegistration(0xefd546cau)]
	public RivetAssetId CameraShake { get; set; } = default;

	[DDLRegistration(0x4ca6dc25u)]
	public float CameraShakeInnerRadius { get; set; } = 5.00f;

	[DDLRegistration(0x42b3a496u)]
	public float CameraShakeOuterRadius { get; set; } = 20.00f;

	[DDLRegistration(0x325d203au)]
	public float FootDamageRadius { get; set; } = 3.00f;

	public static WalkingArchivesJointIKPrius Create(DDLObject ddl) => new(ddl);
}

