// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xbb461b95u)]
public class WeakSpotDamagedEvent : EventBase, IDDLObjectType<WeakSpotDamagedEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0xbb461b95u);

	public WeakSpotDamagedEvent(DDLObject ddl) : base(ddl) {
		NameHash = ddl.GetValue<uint>(0xc2f561e2u, NameHash);
		WeaponNameHash = ddl.GetValue<uint>(0x42a5ee59u, WeaponNameHash);
		LocatorName = ddl.GetString(0x5814524d) ?? LocatorName;
		HealthPercent = ddl.GetValue<float>(0x13ab5436u, HealthPercent);
		DamageAmount = ddl.GetValue<float>(0x563be470u, DamageAmount);
	}

	[DDLRegistration(0xc2f561e2u, description: "Name hash of weakspot.")]
	public uint NameHash { get; set; } = 0x00000000;

	[DDLRegistration(0x42a5ee59u, description: "Name hash of the weapon")]
	public uint WeaponNameHash { get; set; } = 0x00000000;

	[DDLRegistration(0x5814524du, description: "Name of locator or joint weakspot is attached to.")]
	public string? LocatorName { get; set; } = default;

	[DDLRegistration(0x13ab5436u)]
	public float HealthPercent { get; set; } = 100.00f;

	[DDLRegistration(0x563be470u)]
	public float DamageAmount { get; set; } = 0.00f;

	public new static WeakSpotDamagedEvent Create(DDLObject ddl) => new(ddl);
}

