// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0x120aac03u)]
public class WeaponLaserChargeEndEvent : EventBase, IDDLObjectType<WeaponLaserChargeEndEvent> {
	public new static RivetTypeId TypeId { get; } = new RivetTypeId(0x120aac03u);

	public WeaponLaserChargeEndEvent(DDLObject ddl) : base(ddl) {
		BeamHash = ddl.GetValue<uint>(0x26a7db04u, BeamHash);
		Locator = ddl.GetString(0x7bac1d57) ?? Locator;
	}

	[DDLRegistration(0x26a7db04u, description: "Hash for differentiating beams")]
	public uint BeamHash { get; set; } = 0x00000000;

	[DDLRegistration(0x7bac1d57u)]
	public string? Locator { get; set; } = default;

	public new static WeaponLaserChargeEndEvent Create(DDLObject ddl) => new(ddl);
}

