// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Types;

#nullable enable

using Rivet.IO;
using Rivet.DDL.Enums;

[DDLRegistration(0xcc0e3e22u)]
public class ZoneDef : DDLObjectType, IDDLObjectType<ZoneDef> {
	public static RivetTypeId TypeId { get; } = new RivetTypeId(0xcc0e3e22u);

	public ZoneDef(DDLObject ddl) : base(ddl) {
		VaultMetaData = ddl.GetObject<VaultMetaData>(0x037889aau);
		IconPath = ddl.GetValue<RivetAssetId>(0xbf5b007fu, IconPath);
		SceneNodes = ddl.GetDictionary<RivetAssetId, SceneNode>(0x41496fde, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<SceneNode>(mapId));
		ActorGroups = ddl.GetDictionary<RivetAssetId, ActorGroupNode>(0xd4a16a95, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<ActorGroupNode>(mapId));
		MainScriptGraphId = ddl.GetValue<RivetAssetId>(0x98b21bedu, MainScriptGraphId);
		ScriptGraphs = ddl.GetDictionary<RivetAssetId, NodeGraphContents>(0xb6beea44, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<NodeGraphContents>(mapId));
		VarNodes = ddl.GetDictionary<RivetAssetId, VarNode>(0x84e9cc70, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<VarNode>(mapId));
		VertexPaintNodes = ddl.GetDictionary<RivetAssetId, VertexPaintNode>(0xb9ed55e1, DDLMapTypeHandler.VisitRivetAssetId, (mapId, mapDDL) => mapDDL.GetObject<VertexPaintNode>(mapId));
		Atmosphere = ddl.GetValue<RivetAssetId>(0x79fd859au, Atmosphere);
		LightingConditionAtmospheres = ddl.GetObjects<LightingConditionAtmosphere>(0x0b9af92fu);
		LevelLights = ddl.GetObjects<LightingConditionLL>(0x522d0f90u);
		UseSingleLightingCondition = ddl.GetValue<bool>(0x6e0c0a40u, UseSingleLightingCondition);
		SingleLightingCondition = ddl.GetEnum<LightingConditions>(0x485218fcu, LightingConditionsValues.Lookup);
		LongDistanceRayTracing = ddl.GetValue<bool>(0x68c37525u, LongDistanceRayTracing);
		SkipLightCapture = ddl.GetValue<bool>(0x64ede99au, SkipLightCapture);
		ImpostorLightCapture = ddl.GetValue<bool>(0x9e75d1f1u, ImpostorLightCapture);
		SkipHibernation = ddl.GetValue<bool>(0x00585b52u, SkipHibernation);
		HibernateDistanceOverride = ddl.GetValue<float>(0x0f560a96u, HibernateDistanceOverride);
		LightGridPriority = ddl.GetValue<byte>(0xaec38eceu, LightGridPriority);
		LightGridCompression = ddl.GetEnum<LightGridCompression>(0x845970a5u, LightGridCompressionValues.Lookup);
		LightGridStreaming = ddl.GetValue<bool>(0x2d5bc862u, LightGridStreaming);
		RemoveGridSamplesFarFromGeom = ddl.GetValue<bool>(0x1f6a7ba7u, RemoveGridSamplesFarFromGeom);
		AssetReferences = ddl.GetObjects<AssetReferenceDef>(0x730eb7e6u);
		GameplayDataReferences = ddl.GetObjects<GameplayDataReferenceDef>(0x529e91dcu);
	}

	[DDLRegistration(0x037889aau)]
	public VaultMetaData? VaultMetaData { get; set; } = default;

	[DDLRegistration(0xbf5b007fu)]
	public RivetAssetId IconPath { get; set; } = "";

	[DDLRegistration(0x41496fdeu)]
	public Dictionary<RivetAssetId, SceneNode?> SceneNodes { get; set; } = [];

	[DDLRegistration(0xd4a16a95u)]
	public Dictionary<RivetAssetId, ActorGroupNode?> ActorGroups { get; set; } = [];

	[DDLRegistration(0x98b21bedu)]
	public RivetAssetId MainScriptGraphId { get; set; } = new RivetAssetId(0xffffffffffffffff);

	[DDLRegistration(0xb6beea44u)]
	public Dictionary<RivetAssetId, NodeGraphContents?> ScriptGraphs { get; set; } = [];

	[DDLRegistration(0x84e9cc70u)]
	public Dictionary<RivetAssetId, VarNode?> VarNodes { get; set; } = [];

	[DDLRegistration(0xb9ed55e1u)]
	public Dictionary<RivetAssetId, VertexPaintNode?> VertexPaintNodes { get; set; } = [];

	[DDLRegistration(0x79fd859au, "Default Atmosphere")]
	public RivetAssetId Atmosphere { get; set; } = default;

	[DDLRegistration(0x0b9af92fu, "LC Atmospheres")]
	public List<LightingConditionAtmosphere?> LightingConditionAtmospheres { get; set; } = [];

	[DDLRegistration(0x522d0f90u)]
	public List<LightingConditionLL?> LevelLights { get; set; } = [];

	[DDLRegistration(0x6e0c0a40u, "Use Single Lighting Condition")]
	public bool UseSingleLightingCondition { get; set; } = false;

	[DDLRegistration(0x485218fcu, "Single Lighting Condition")]
	public LightingConditions SingleLightingCondition { get; set; } = LightingConditions.Day;

	[DDLRegistration(0x68c37525u, "Long Distance Ray Tracing", "If set, model instances tagged with ray tracing will not be culled when far away from the camera.")]
	public bool LongDistanceRayTracing { get; set; } = false;

	[DDLRegistration(0x64ede99au, "Skip Light Capture")]
	public bool SkipLightCapture { get; set; } = false;

	[DDLRegistration(0x9e75d1f1u, "Include for Light Capture (if a global zone)", "If set, the lighting farm will automatically load this zone during captures if the zone is in the level�s global region.")]
	public bool ImpostorLightCapture { get; set; } = false;

	[DDLRegistration(0x00585b52u, "Skip Hibernation", "If set, the zone will not generate any hibernating objects")]
	public bool SkipHibernation { get; set; } = false;

	[DDLRegistration(0x0f560a96u, "Hibernate Distance Override", "Overrides RenderSettings::HibernateDrawDistance if set to anything other than zero")]
	public float HibernateDistanceOverride { get; set; } = 0.00f;

	[DDLRegistration(0xaec38eceu, "Light Grid Priority", "Priority of the grids in this zones in relation to grids in other zones. Higher numbers result in grids from this zones replacing grids from zones with lower priority.")]
	public byte LightGridPriority { get; set; } = 0x00;

	[DDLRegistration(0x845970a5u, "Light Grid Compression", "Amount of compression applied to the light grid's on disk storage.")]
	public LightGridCompression LightGridCompression { get; set; } = LightGridCompression.LowCompression;

	[DDLRegistration(0x2d5bc862u, "Light Grid Streaming", "If checked, light grids will be streamed based on view. Otherwise they will all be loaded at zone load time.")]
	public bool LightGridStreaming { get; set; } = false;

	[DDLRegistration(0x1f6a7ba7u, "Reduce Light Grid Samples For Disk", "Removes light grid samples that are not near geometry in order to reduce the size of the data on disk. Always on in LGC1, optional in LGC2.")]
	public bool RemoveGridSamplesFarFromGeom { get; set; } = true;

	[DDLRegistration(0x730eb7e6u, description: "Asset References")]
	public List<AssetReferenceDef?> AssetReferences { get; set; } = [];

	[DDLRegistration(0x529e91dcu)]
	public List<GameplayDataReferenceDef?> GameplayDataReferences { get; set; } = [];

	public static ZoneDef Create(DDLObject ddl) => new(ddl);
}

