// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xc9120f11u)]
public enum AuthorityType : uint {
	[DDLRegistration(0x5a5b5a9fu)] Default,
	[DDLRegistration(0xe683dc3du)] Permanent,
	[DDLRegistration(0x429c20c0u)] Invalid,
}

public static class AuthorityTypeValues {
	public static Dictionary<uint, AuthorityType> Lookup = new() {
		[0x5a5b5a9fu] = AuthorityType.Default,
		[0xe683dc3du] = AuthorityType.Permanent,
		[0x429c20c0u] = AuthorityType.Invalid,
	};

	public static Dictionary<AuthorityType, uint> ReverseLookup = new() {
		[AuthorityType.Default] = 0x5a5b5a9fu,
		[AuthorityType.Permanent] = 0xe683dc3du,
		[AuthorityType.Invalid] = 0x429c20c0u,
	};

	public static uint TypeId => 0xc9120f11u;
}
