// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x6b94ddc9u)]
public enum ChangeType : uint {
	[DDLRegistration(0x349ef852u, "Other")] Other,
	[DDLRegistration(0x69418f94u, "Session")] Session,
	[DDLRegistration(0xef69972eu, "Asset")] Asset,
	[DDLRegistration(0x99d49d5cu, "Change applies to all sessions")] AllSessions,
}

public static class ChangeTypeValues {
	public static Dictionary<uint, ChangeType> Lookup = new() {
		[0x349ef852u] = ChangeType.Other,
		[0x69418f94u] = ChangeType.Session,
		[0xef69972eu] = ChangeType.Asset,
		[0x99d49d5cu] = ChangeType.AllSessions,
	};

	public static Dictionary<ChangeType, uint> ReverseLookup = new() {
		[ChangeType.Other] = 0x349ef852u,
		[ChangeType.Session] = 0x69418f94u,
		[ChangeType.Asset] = 0xef69972eu,
		[ChangeType.AllSessions] = 0x99d49d5cu,
	};

	public static uint TypeId => 0x6b94ddc9u;
}
