// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xf5bf036du)]
public enum EmitterType : uint {
	[DDLRegistration(0x8ea70b26u, "CPU")] CPU,
	[DDLRegistration(0x89aea3fau, "GPU")] GPU,
}

public static class EmitterTypeValues {
	public static Dictionary<uint, EmitterType> Lookup = new() {
		[0x8ea70b26u] = EmitterType.CPU,
		[0x89aea3fau] = EmitterType.GPU,
	};

	public static Dictionary<EmitterType, uint> ReverseLookup = new() {
		[EmitterType.CPU] = 0x8ea70b26u,
		[EmitterType.GPU] = 0x89aea3fau,
	};

	public static uint TypeId => 0xf5bf036du;
}
