// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x22e01f8du)]
public enum OptimizeUVMode : uint {
	[DDLRegistration(0x0eb42269u)] None,
	[DDLRegistration(0x87cc6f9au, "UV0 Only")] Uv0Only,
	[DDLRegistration(0xbaac462au, "UV1 Only")] Uv1Only,
	[DDLRegistration(0xdc03f730u, "UV0 And UV1")] UV0AndUV1,
}

public static class OptimizeUVModeValues {
	public static Dictionary<uint, OptimizeUVMode> Lookup = new() {
		[0x0eb42269u] = OptimizeUVMode.None,
		[0x87cc6f9au] = OptimizeUVMode.Uv0Only,
		[0xbaac462au] = OptimizeUVMode.Uv1Only,
		[0xdc03f730u] = OptimizeUVMode.UV0AndUV1,
	};

	public static Dictionary<OptimizeUVMode, uint> ReverseLookup = new() {
		[OptimizeUVMode.None] = 0x0eb42269u,
		[OptimizeUVMode.Uv0Only] = 0x87cc6f9au,
		[OptimizeUVMode.Uv1Only] = 0xbaac462au,
		[OptimizeUVMode.UV0AndUV1] = 0xdc03f730u,
	};

	public static uint TypeId => 0x22e01f8du;
}
