// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x54aa3293u)]
public enum TouchType : uint {
	[DDLRegistration(0xc9dc5be0u)] Touched,
	[DDLRegistration(0x4ef7a276u)] Untouched,
}

public static class TouchTypeValues {
	public static Dictionary<uint, TouchType> Lookup = new() {
		[0xc9dc5be0u] = TouchType.Touched,
		[0x4ef7a276u] = TouchType.Untouched,
	};

	public static Dictionary<TouchType, uint> ReverseLookup = new() {
		[TouchType.Touched] = 0xc9dc5be0u,
		[TouchType.Untouched] = 0x4ef7a276u,
	};

	public static uint TypeId => 0x54aa3293u;
}
