// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x0704d6a8u)]
public enum x0704d6a8 : uint {
	[DDLRegistration(0x0eb42269u)] None,
	[DDLRegistration(0x8b07d504u, "2 Slices")] Two,
	[DDLRegistration(0xe1e544dbu, "4 Slices")] Four,
	[DDLRegistration(0x8bccf3f4u, "8 Slices")] Eight,
	[DDLRegistration(0x077157a9u, "16 Slices")] Sixteen,
	[DDLRegistration(0xe631781du, "32 Slices")] ThirtyTwo,
	[DDLRegistration(0x70dc4941u, "64 Slices")] SixtyFour,
	[DDLRegistration(0xc97a8893u, "128 Slices")] OneTwentyEight,
	[DDLRegistration(0x178dad28u, "256 Slices")] TwoFiftySix,
	[DDLRegistration(0x1682cd3du, "512 Slices")] FiveTwelve,
}

public static class x0704d6a8Values {
	public static Dictionary<uint, x0704d6a8> Lookup = new() {
		[0x0eb42269u] = x0704d6a8.None,
		[0x8b07d504u] = x0704d6a8.Two,
		[0xe1e544dbu] = x0704d6a8.Four,
		[0x8bccf3f4u] = x0704d6a8.Eight,
		[0x077157a9u] = x0704d6a8.Sixteen,
		[0xe631781du] = x0704d6a8.ThirtyTwo,
		[0x70dc4941u] = x0704d6a8.SixtyFour,
		[0xc97a8893u] = x0704d6a8.OneTwentyEight,
		[0x178dad28u] = x0704d6a8.TwoFiftySix,
		[0x1682cd3du] = x0704d6a8.FiveTwelve,
	};

	public static Dictionary<x0704d6a8, uint> ReverseLookup = new() {
		[x0704d6a8.None] = 0x0eb42269u,
		[x0704d6a8.Two] = 0x8b07d504u,
		[x0704d6a8.Four] = 0xe1e544dbu,
		[x0704d6a8.Eight] = 0x8bccf3f4u,
		[x0704d6a8.Sixteen] = 0x077157a9u,
		[x0704d6a8.ThirtyTwo] = 0xe631781du,
		[x0704d6a8.SixtyFour] = 0x70dc4941u,
		[x0704d6a8.OneTwentyEight] = 0xc97a8893u,
		[x0704d6a8.TwoFiftySix] = 0x178dad28u,
		[x0704d6a8.FiveTwelve] = 0x1682cd3du,
	};

	public static uint TypeId => 0x0704d6a8u;
}
