// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x14738916u)]
public enum x14738916 : uint {
	[DDLRegistration(0x429c90dbu)] InOrder,
	[DDLRegistration(0x32143a49u)] Shuffle,
	[DDLRegistration(0xe42f0aacu)] Cluster,
	[DDLRegistration(0x42cdee1fu)] Spread,
	[DDLRegistration(0xbf344ea2u)] CloseToPlayers,
	[DDLRegistration(0x9c02881eu)] FarFromPlayers,
	[DDLRegistration(0xecc32324u)] CustomCode,
}

public static class x14738916Values {
	public static Dictionary<uint, x14738916> Lookup = new() {
		[0x429c90dbu] = x14738916.InOrder,
		[0x32143a49u] = x14738916.Shuffle,
		[0xe42f0aacu] = x14738916.Cluster,
		[0x42cdee1fu] = x14738916.Spread,
		[0xbf344ea2u] = x14738916.CloseToPlayers,
		[0x9c02881eu] = x14738916.FarFromPlayers,
		[0xecc32324u] = x14738916.CustomCode,
	};

	public static Dictionary<x14738916, uint> ReverseLookup = new() {
		[x14738916.InOrder] = 0x429c90dbu,
		[x14738916.Shuffle] = 0x32143a49u,
		[x14738916.Cluster] = 0xe42f0aacu,
		[x14738916.Spread] = 0x42cdee1fu,
		[x14738916.CloseToPlayers] = 0xbf344ea2u,
		[x14738916.FarFromPlayers] = 0x9c02881eu,
		[x14738916.CustomCode] = 0xecc32324u,
	};

	public static uint TypeId => 0x14738916u;
}
