// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x189ff42fu)]
public enum x189ff42f : uint {
	[DDLRegistration(0xeb0be1a1u, "Weapons")] Weapons,
	[DDLRegistration(0x52e1338eu, "Armor")] Armor,
	[DDLRegistration(0x7a60713du, "Gear")] Gear,
}

public static class x189ff42fValues {
	public static Dictionary<uint, x189ff42f> Lookup = new() {
		[0xeb0be1a1u] = x189ff42f.Weapons,
		[0x52e1338eu] = x189ff42f.Armor,
		[0x7a60713du] = x189ff42f.Gear,
	};

	public static Dictionary<x189ff42f, uint> ReverseLookup = new() {
		[x189ff42f.Weapons] = 0xeb0be1a1u,
		[x189ff42f.Armor] = 0x52e1338eu,
		[x189ff42f.Gear] = 0x7a60713du,
	};

	public static uint TypeId => 0x189ff42fu;
}
