// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x41912c18u), Flags]
public enum x41912c18 : uint {
	[DDLRegistration(0x0c8e9720u)] FlagsNone = 0x00000001u,
	[DDLRegistration(0xaedb295fu)] FlagsLooping = 0x00000002u,
	[DDLRegistration(0x01dabae4u)] FlagsBlendAdd = 0x00000004u,
	[DDLRegistration(0xe1d7081du)] FlagsCombineAdd = 0x00000008u,
	[DDLRegistration(0x80f3f68au)] FlagsAdditiveBranch = 0x00000010u,
	[DDLRegistration(0x9310d165u)] FlagsTimeBackwards = 0x00000020u,
	[DDLRegistration(0x87612c54u)] FlagsBlendEventPassThroughLayer = 0x00000040u,
	[DDLRegistration(0x6ba44692u)] FlagsMirrorYZ = 0x00000080u,
	[DDLRegistration(0x72bf77d3u)] FlagsMirrorXZ = 0x00000100u,
	[DDLRegistration(0xebb62669u)] FlagsMirrorXY = 0x00000200u,
	[DDLRegistration(0x83613be8u)] FlagsFromLoopingDriver = 0x00000400u,
	[DDLRegistration(0x967a41d9u)] FlagsFromUsesLocalTime = 0x00000800u,
	[DDLRegistration(0xa5f2ba66u)] FlagsWasAdvanced = 0x00001000u,
}

public static class x41912c18Values {
	public static Dictionary<uint, x41912c18> Lookup = new() {
		[0x0c8e9720u] = x41912c18.FlagsNone,
		[0xaedb295fu] = x41912c18.FlagsLooping,
		[0x01dabae4u] = x41912c18.FlagsBlendAdd,
		[0xe1d7081du] = x41912c18.FlagsCombineAdd,
		[0x80f3f68au] = x41912c18.FlagsAdditiveBranch,
		[0x9310d165u] = x41912c18.FlagsTimeBackwards,
		[0x87612c54u] = x41912c18.FlagsBlendEventPassThroughLayer,
		[0x6ba44692u] = x41912c18.FlagsMirrorYZ,
		[0x72bf77d3u] = x41912c18.FlagsMirrorXZ,
		[0xebb62669u] = x41912c18.FlagsMirrorXY,
		[0x83613be8u] = x41912c18.FlagsFromLoopingDriver,
		[0x967a41d9u] = x41912c18.FlagsFromUsesLocalTime,
		[0xa5f2ba66u] = x41912c18.FlagsWasAdvanced,
	};

	public static Dictionary<x41912c18, uint> ReverseLookup = new() {
		[x41912c18.FlagsNone] = 0x0c8e9720u,
		[x41912c18.FlagsLooping] = 0xaedb295fu,
		[x41912c18.FlagsBlendAdd] = 0x01dabae4u,
		[x41912c18.FlagsCombineAdd] = 0xe1d7081du,
		[x41912c18.FlagsAdditiveBranch] = 0x80f3f68au,
		[x41912c18.FlagsTimeBackwards] = 0x9310d165u,
		[x41912c18.FlagsBlendEventPassThroughLayer] = 0x87612c54u,
		[x41912c18.FlagsMirrorYZ] = 0x6ba44692u,
		[x41912c18.FlagsMirrorXZ] = 0x72bf77d3u,
		[x41912c18.FlagsMirrorXY] = 0xebb62669u,
		[x41912c18.FlagsFromLoopingDriver] = 0x83613be8u,
		[x41912c18.FlagsFromUsesLocalTime] = 0x967a41d9u,
		[x41912c18.FlagsWasAdvanced] = 0xa5f2ba66u,
	};

	public static uint TypeId => 0x41912c18u;
}
