// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x457f748bu)]
public enum x457f748b : uint {
	[DDLRegistration(0x1423fd87u, "Unknown")] Unknown,
	[DDLRegistration(0x22d55c45u, "Head")] LocationHead,
	[DDLRegistration(0x0ad71fd2u, "Torso")] LocationTorso,
	[DDLRegistration(0x5ffe1e5cu, "Weak Spot")] LocationWeakspot,
	[DDLRegistration(0x74b071efu, "Path Test")] LocationPathTest,
	[DDLRegistration(0xf59ef9e3u, "LoS Test")] LocationLoSTest,
	[DDLRegistration(0x5c686fd0u, "Named", "This location is identified by name for special cases (like for certain weapons)")] LocationNamed,
}

public static class x457f748bValues {
	public static Dictionary<uint, x457f748b> Lookup = new() {
		[0x1423fd87u] = x457f748b.Unknown,
		[0x22d55c45u] = x457f748b.LocationHead,
		[0x0ad71fd2u] = x457f748b.LocationTorso,
		[0x5ffe1e5cu] = x457f748b.LocationWeakspot,
		[0x74b071efu] = x457f748b.LocationPathTest,
		[0xf59ef9e3u] = x457f748b.LocationLoSTest,
		[0x5c686fd0u] = x457f748b.LocationNamed,
	};

	public static Dictionary<x457f748b, uint> ReverseLookup = new() {
		[x457f748b.Unknown] = 0x1423fd87u,
		[x457f748b.LocationHead] = 0x22d55c45u,
		[x457f748b.LocationTorso] = 0x0ad71fd2u,
		[x457f748b.LocationWeakspot] = 0x5ffe1e5cu,
		[x457f748b.LocationPathTest] = 0x74b071efu,
		[x457f748b.LocationLoSTest] = 0xf59ef9e3u,
		[x457f748b.LocationNamed] = 0x5c686fd0u,
	};

	public static uint TypeId => 0x457f748bu;
}
