// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x48037d3au)]
public enum x48037d3a : uint {
	[DDLRegistration(0x3df09603u)] GameTime,
	[DDLRegistration(0x87362f55u)] RealTime,
	[DDLRegistration(0x6ff40b45u)] AnimationTime,
}

public static class x48037d3aValues {
	public static Dictionary<uint, x48037d3a> Lookup = new() {
		[0x3df09603u] = x48037d3a.GameTime,
		[0x87362f55u] = x48037d3a.RealTime,
		[0x6ff40b45u] = x48037d3a.AnimationTime,
	};

	public static Dictionary<x48037d3a, uint> ReverseLookup = new() {
		[x48037d3a.GameTime] = 0x3df09603u,
		[x48037d3a.RealTime] = 0x87362f55u,
		[x48037d3a.AnimationTime] = 0x6ff40b45u,
	};

	public static uint TypeId => 0x48037d3au;
}
