// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x57689c9cu)]
public enum x57689c9c : uint {
	[DDLRegistration(0x541d3af1u, "Equals")] Equals,
	[DDLRegistration(0x2a9dc139u, "Contains")] Contains,
	[DDLRegistration(0xff55bfdeu, "Prefix")] Prefix,
	[DDLRegistration(0xd954be8eu, "Suffix")] Suffix,
	[DDLRegistration(0xafc235b8u, "Regex")] Regex,
}

public static class x57689c9cValues {
	public static Dictionary<uint, x57689c9c> Lookup = new() {
		[0x541d3af1u] = x57689c9c.Equals,
		[0x2a9dc139u] = x57689c9c.Contains,
		[0xff55bfdeu] = x57689c9c.Prefix,
		[0xd954be8eu] = x57689c9c.Suffix,
		[0xafc235b8u] = x57689c9c.Regex,
	};

	public static Dictionary<x57689c9c, uint> ReverseLookup = new() {
		[x57689c9c.Equals] = 0x541d3af1u,
		[x57689c9c.Contains] = 0x2a9dc139u,
		[x57689c9c.Prefix] = 0xff55bfdeu,
		[x57689c9c.Suffix] = 0xd954be8eu,
		[x57689c9c.Regex] = 0xafc235b8u,
	};

	public static uint TypeId => 0x57689c9cu;
}
