// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x5793ba5eu)]
public enum x5793ba5e : uint {
	[DDLRegistration(0xb2776cc0u)] Slot01,
	[DDLRegistration(0x2b7e3d7au)] Slot02,
	[DDLRegistration(0x5c790decu)] Slot03,
	[DDLRegistration(0xc21d984fu)] Slot04,
	[DDLRegistration(0xb51aa8d9u)] Slot05,
	[DDLRegistration(0x2c13f963u)] Slot06,
	[DDLRegistration(0x5b14c9f5u)] Slot07,
	[DDLRegistration(0xcbabd464u)] Slot08,
	[DDLRegistration(0xbcace4f2u)] Slot09,
	[DDLRegistration(0xdc6b6d17u)] Slot10,
	[DDLRegistration(0xab6c5d81u)] Slot11,
	[DDLRegistration(0x32650c3bu)] Slot12,
	[DDLRegistration(0x45623cadu)] Slot13,
	[DDLRegistration(0xdb06a90eu)] Slot14,
	[DDLRegistration(0xac019998u)] Slot15,
	[DDLRegistration(0x3508c822u)] Slot16,
	[DDLRegistration(0x5749322fu)] SlotNoQS01,
	[DDLRegistration(0xce406395u)] SlotNoQS02,
	[DDLRegistration(0xb9475303u)] SlotNoQS03,
	[DDLRegistration(0x2723c6a0u)] SlotNoQS04,
	[DDLRegistration(0x5024f636u)] SlotNoQS05,
	[DDLRegistration(0xc92da78cu)] SlotNoQS06,
	[DDLRegistration(0xbe2a971au)] SlotNoQS07,
	[DDLRegistration(0x2e958a8bu)] SlotNoQS08,
	[DDLRegistration(0x5992ba1du)] SlotNoQS09,
	[DDLRegistration(0xb734d23cu)] SlotMelee,
}

public static class x5793ba5eValues {
	public static Dictionary<uint, x5793ba5e> Lookup = new() {
		[0xb2776cc0u] = x5793ba5e.Slot01,
		[0x2b7e3d7au] = x5793ba5e.Slot02,
		[0x5c790decu] = x5793ba5e.Slot03,
		[0xc21d984fu] = x5793ba5e.Slot04,
		[0xb51aa8d9u] = x5793ba5e.Slot05,
		[0x2c13f963u] = x5793ba5e.Slot06,
		[0x5b14c9f5u] = x5793ba5e.Slot07,
		[0xcbabd464u] = x5793ba5e.Slot08,
		[0xbcace4f2u] = x5793ba5e.Slot09,
		[0xdc6b6d17u] = x5793ba5e.Slot10,
		[0xab6c5d81u] = x5793ba5e.Slot11,
		[0x32650c3bu] = x5793ba5e.Slot12,
		[0x45623cadu] = x5793ba5e.Slot13,
		[0xdb06a90eu] = x5793ba5e.Slot14,
		[0xac019998u] = x5793ba5e.Slot15,
		[0x3508c822u] = x5793ba5e.Slot16,
		[0x5749322fu] = x5793ba5e.SlotNoQS01,
		[0xce406395u] = x5793ba5e.SlotNoQS02,
		[0xb9475303u] = x5793ba5e.SlotNoQS03,
		[0x2723c6a0u] = x5793ba5e.SlotNoQS04,
		[0x5024f636u] = x5793ba5e.SlotNoQS05,
		[0xc92da78cu] = x5793ba5e.SlotNoQS06,
		[0xbe2a971au] = x5793ba5e.SlotNoQS07,
		[0x2e958a8bu] = x5793ba5e.SlotNoQS08,
		[0x5992ba1du] = x5793ba5e.SlotNoQS09,
		[0xb734d23cu] = x5793ba5e.SlotMelee,
	};

	public static Dictionary<x5793ba5e, uint> ReverseLookup = new() {
		[x5793ba5e.Slot01] = 0xb2776cc0u,
		[x5793ba5e.Slot02] = 0x2b7e3d7au,
		[x5793ba5e.Slot03] = 0x5c790decu,
		[x5793ba5e.Slot04] = 0xc21d984fu,
		[x5793ba5e.Slot05] = 0xb51aa8d9u,
		[x5793ba5e.Slot06] = 0x2c13f963u,
		[x5793ba5e.Slot07] = 0x5b14c9f5u,
		[x5793ba5e.Slot08] = 0xcbabd464u,
		[x5793ba5e.Slot09] = 0xbcace4f2u,
		[x5793ba5e.Slot10] = 0xdc6b6d17u,
		[x5793ba5e.Slot11] = 0xab6c5d81u,
		[x5793ba5e.Slot12] = 0x32650c3bu,
		[x5793ba5e.Slot13] = 0x45623cadu,
		[x5793ba5e.Slot14] = 0xdb06a90eu,
		[x5793ba5e.Slot15] = 0xac019998u,
		[x5793ba5e.Slot16] = 0x3508c822u,
		[x5793ba5e.SlotNoQS01] = 0x5749322fu,
		[x5793ba5e.SlotNoQS02] = 0xce406395u,
		[x5793ba5e.SlotNoQS03] = 0xb9475303u,
		[x5793ba5e.SlotNoQS04] = 0x2723c6a0u,
		[x5793ba5e.SlotNoQS05] = 0x5024f636u,
		[x5793ba5e.SlotNoQS06] = 0xc92da78cu,
		[x5793ba5e.SlotNoQS07] = 0xbe2a971au,
		[x5793ba5e.SlotNoQS08] = 0x2e958a8bu,
		[x5793ba5e.SlotNoQS09] = 0x5992ba1du,
		[x5793ba5e.SlotMelee] = 0xb734d23cu,
	};

	public static uint TypeId => 0x5793ba5eu;
}
