// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x925714c8u)]
public enum x925714c8 : uint {
	[DDLRegistration(0x4e2d1b4fu, description: "Keep the camera target on the ground below the player, only follow the player if they go offscreen.")] TrackGround,
	[DDLRegistration(0xfa2234d9u, description: "Camera tracks player motion as they bounce.")] TrackActor,
}

public static class x925714c8Values {
	public static Dictionary<uint, x925714c8> Lookup = new() {
		[0x4e2d1b4fu] = x925714c8.TrackGround,
		[0xfa2234d9u] = x925714c8.TrackActor,
	};

	public static Dictionary<x925714c8, uint> ReverseLookup = new() {
		[x925714c8.TrackGround] = 0x4e2d1b4fu,
		[x925714c8.TrackActor] = 0xfa2234d9u,
	};

	public static uint TypeId => 0x925714c8u;
}
