// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x9675aa42u)]
public enum x9675aa42 : uint {
	[DDLRegistration(0xbc45acd1u, "Standard (Head + Body)")] TypeStandard,
	[DDLRegistration(0xecda0dfeu, "Head")] TypeHead,
	[DDLRegistration(0x9081f0d0u, "Body")] TypeBody,
}

public static class x9675aa42Values {
	public static Dictionary<uint, x9675aa42> Lookup = new() {
		[0xbc45acd1u] = x9675aa42.TypeStandard,
		[0xecda0dfeu] = x9675aa42.TypeHead,
		[0x9081f0d0u] = x9675aa42.TypeBody,
	};

	public static Dictionary<x9675aa42, uint> ReverseLookup = new() {
		[x9675aa42.TypeStandard] = 0xbc45acd1u,
		[x9675aa42.TypeHead] = 0xecda0dfeu,
		[x9675aa42.TypeBody] = 0x9081f0d0u,
	};

	public static uint TypeId => 0x9675aa42u;
}
