// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xb5725fd2u)]
public enum xb5725fd2 : uint {
	[DDLRegistration(0xe743d22fu, "Scene Mode")] SceneMode,
	[DDLRegistration(0x986713eau, "Vault Mode")] VaultMode,
}

public static class xb5725fd2Values {
	public static Dictionary<uint, xb5725fd2> Lookup = new() {
		[0xe743d22fu] = xb5725fd2.SceneMode,
		[0x986713eau] = xb5725fd2.VaultMode,
	};

	public static Dictionary<xb5725fd2, uint> ReverseLookup = new() {
		[xb5725fd2.SceneMode] = 0xe743d22fu,
		[xb5725fd2.VaultMode] = 0x986713eau,
	};

	public static uint TypeId => 0xb5725fd2u;
}
