// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xba3c7381u)]
public enum xba3c7381 : uint {
	[DDLRegistration(0x2fb4a5a7u)] Inactive,
	[DDLRegistration(0xcfeaa78fu)] Passive,
	[DDLRegistration(0x785c546bu)] Engaged,
}

public static class xba3c7381Values {
	public static Dictionary<uint, xba3c7381> Lookup = new() {
		[0x2fb4a5a7u] = xba3c7381.Inactive,
		[0xcfeaa78fu] = xba3c7381.Passive,
		[0x785c546bu] = xba3c7381.Engaged,
	};

	public static Dictionary<xba3c7381, uint> ReverseLookup = new() {
		[xba3c7381.Inactive] = 0x2fb4a5a7u,
		[xba3c7381.Passive] = 0xcfeaa78fu,
		[xba3c7381.Engaged] = 0x785c546bu,
	};

	public static uint TypeId => 0xba3c7381u;
}
