// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xc2d17b4cu)]
public enum xc2d17b4c : uint {
	[DDLRegistration(0x27c2878fu, description: "This button will play ButtonPressedEvent when a wrench/hammer is slammed on it")] Slam,
	[DDLRegistration(0xa2558c45u, description: "This button will play ButtonPressedEvent when a wrench/hammer is thrown at it.")] Throw,
	[DDLRegistration(0xc01f7923u, description: "This button will play ButtonPressedEvent when a wrench/hammer is swung at it.")] Hit,
}

public static class xc2d17b4cValues {
	public static Dictionary<uint, xc2d17b4c> Lookup = new() {
		[0x27c2878fu] = xc2d17b4c.Slam,
		[0xa2558c45u] = xc2d17b4c.Throw,
		[0xc01f7923u] = xc2d17b4c.Hit,
	};

	public static Dictionary<xc2d17b4c, uint> ReverseLookup = new() {
		[xc2d17b4c.Slam] = 0x27c2878fu,
		[xc2d17b4c.Throw] = 0xa2558c45u,
		[xc2d17b4c.Hit] = 0xc01f7923u,
	};

	public static uint TypeId => 0xc2d17b4cu;
}
