// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xcc3b3a79u)]
public enum xcc3b3a79 : uint {
	[DDLRegistration(0xa015c8eau)] Editor,
	[DDLRegistration(0xd1cfe2a1u)] Zone,
	[DDLRegistration(0x76bb3b41u)] DragBegin,
	[DDLRegistration(0x1c618fcdu)] Drag,
	[DDLRegistration(0xd8297c06u)] DragEnd,
	[DDLRegistration(0x844c23ddu)] Engine,
}

public static class xcc3b3a79Values {
	public static Dictionary<uint, xcc3b3a79> Lookup = new() {
		[0xa015c8eau] = xcc3b3a79.Editor,
		[0xd1cfe2a1u] = xcc3b3a79.Zone,
		[0x76bb3b41u] = xcc3b3a79.DragBegin,
		[0x1c618fcdu] = xcc3b3a79.Drag,
		[0xd8297c06u] = xcc3b3a79.DragEnd,
		[0x844c23ddu] = xcc3b3a79.Engine,
	};

	public static Dictionary<xcc3b3a79, uint> ReverseLookup = new() {
		[xcc3b3a79.Editor] = 0xa015c8eau,
		[xcc3b3a79.Zone] = 0xd1cfe2a1u,
		[xcc3b3a79.DragBegin] = 0x76bb3b41u,
		[xcc3b3a79.Drag] = 0x1c618fcdu,
		[xcc3b3a79.DragEnd] = 0xd8297c06u,
		[xcc3b3a79.Engine] = 0x844c23ddu,
	};

	public static uint TypeId => 0xcc3b3a79u;
}
