// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xd68b2713u)]
public enum xd68b2713 : uint {
	[DDLRegistration(0xfe3ea8d6u, description: "List changelists regardless of status (the default behavior).")] Any,
	[DDLRegistration(0x6dd020f9u, description: "List only pending changelists (-s pending).")] Pending,
	[DDLRegistration(0x2818b1cfu, description: "List only submitted changelists (-s submitted).")] Submitted,
	[DDLRegistration(0x3f455c78u, description: "List only shelved changelists (-s shelved).")] Shelved,
}

public static class xd68b2713Values {
	public static Dictionary<uint, xd68b2713> Lookup = new() {
		[0xfe3ea8d6u] = xd68b2713.Any,
		[0x6dd020f9u] = xd68b2713.Pending,
		[0x2818b1cfu] = xd68b2713.Submitted,
		[0x3f455c78u] = xd68b2713.Shelved,
	};

	public static Dictionary<xd68b2713, uint> ReverseLookup = new() {
		[xd68b2713.Any] = 0xfe3ea8d6u,
		[xd68b2713.Pending] = 0x6dd020f9u,
		[xd68b2713.Submitted] = 0x2818b1cfu,
		[xd68b2713.Shelved] = 0x3f455c78u,
	};

	public static uint TypeId => 0xd68b2713u;
}
