// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xe4016569u)]
public enum xe4016569 : uint {
	[DDLRegistration(0x3f69e8afu, "Tris")] TriCount,
	[DDLRegistration(0x334133f7u, "Resident VRAM")] ResidentVram,
	[DDLRegistration(0x7d1c7d4du, "RAM usage")] Ram,
	[DDLRegistration(0x005f02beu, "Instances")] InstanceCount,
	[DDLRegistration(0x6a7a01e3u, "RAM for Collision")] CollRam,
	[DDLRegistration(0x2503eab9u, "RAM for Navigation")] NavRam,
}

public static class xe4016569Values {
	public static Dictionary<uint, xe4016569> Lookup = new() {
		[0x3f69e8afu] = xe4016569.TriCount,
		[0x334133f7u] = xe4016569.ResidentVram,
		[0x7d1c7d4du] = xe4016569.Ram,
		[0x005f02beu] = xe4016569.InstanceCount,
		[0x6a7a01e3u] = xe4016569.CollRam,
		[0x2503eab9u] = xe4016569.NavRam,
	};

	public static Dictionary<xe4016569, uint> ReverseLookup = new() {
		[xe4016569.TriCount] = 0x3f69e8afu,
		[xe4016569.ResidentVram] = 0x334133f7u,
		[xe4016569.Ram] = 0x7d1c7d4du,
		[xe4016569.InstanceCount] = 0x005f02beu,
		[xe4016569.CollRam] = 0x6a7a01e3u,
		[xe4016569.NavRam] = 0x2503eab9u,
	};

	public static uint TypeId => 0xe4016569u;
}
