// <auto-generated>
// SPDX-FileCopyrightText: 2025-2026 Neptuwunium
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xf787d865u)]
public enum xf787d865 : uint {
	[DDLRegistration(0x0eb42269u)] None,
	[DDLRegistration(0x979d0877u, "Match Previous")] Match,
	[DDLRegistration(0xbd5b723fu, "Reset To Zero")] Reset,
}

public static class xf787d865Values {
	public static Dictionary<uint, xf787d865> Lookup = new() {
		[0x0eb42269u] = xf787d865.None,
		[0x979d0877u] = xf787d865.Match,
		[0xbd5b723fu] = xf787d865.Reset,
	};

	public static Dictionary<xf787d865, uint> ReverseLookup = new() {
		[xf787d865.None] = 0x0eb42269u,
		[xf787d865.Match] = 0x979d0877u,
		[xf787d865.Reset] = 0xbd5b723fu,
	};

	public static uint TypeId => 0xf787d865u;
}
