using System.Globalization;
using Rivet.DDL.Generator.Structs;

namespace Rivet.DDL.Generator;

public static class DDLTemplate {
	public const string LabelAttributeField = ", %type%\"%label%\"";

	public const string RegistrationAttribute = "DDLRegistration(0x%hash%u%label%)";

	public const string RootAttribute = "DDLTypeRoot(0x%hash%u, \"%label%\"), ";

	public const string Header =
		"""
		// <auto-generated>
		// SPDX-FileCopyrightText: 2025 Legiayayana
		//
		// SPDX-License-Identifier: EUPL-1.2

		namespace Rivet.DDL.%type%;
		""";

	public const string DDLField = "\t[%attribute%]\n\tpublic %type% %name% { get; set; } = %default%;\n";

	public const string DDLInit = "\t\t%name% = ddl.%method%;";

	public const string DDLBody =
		"""

		#nullable enable

		using Rivet.IO;
		using Rivet.DDL.Enums;

		[%attribute%]
		public class %name% : %base-name%, IDDLObjectType<%name%> {
			public %new%static RivetTypeId TypeId { get; } = new RivetTypeId(0x%hash%u);

			public %name%(DDLObject ddl) : base(ddl) {
				%init-body%
			}

			%field-body%

			public %new%static %name% Create(DDLObject ddl) => new(ddl);
		}

		""";

	public const string DefaultArrayArgument = "0x%hash%u";

	public const string DefaultReader = "GetValue<%type%>(0x%hash%u, %name%)";
	public const string DefaultArrayReader = "GetValues<%type%>(0x%hash%u, %name%)";
	public const string DefaultMapReader = "(mapId, mapDDL) => mapDDL.GetValue<%type%>(mapId)";
	public const string DefaultMapKeyHandler = "DDLMapTypeHandler.Visit%type%";
	public const string MapReader = "GetDictionary<%map-type%, %type%>(0x%hash%, %key-handler%, %visitor%)";

	public static readonly Dictionary<DDLArrayKind, string> ArrayMapping = new() {
		[DDLArrayKind.None] = "%type%",
		[DDLArrayKind.Fixed] = "List<%type%>",
		[DDLArrayKind.Dynamic] = "List<%type%>",
		[DDLArrayKind.Map] = "Dictionary<%map-type%, %type%>",
	};

	public static readonly Dictionary<DDLTypeKind, string> TypeMapping = new() {
		[DDLTypeKind.UInt8] = "byte",
		[DDLTypeKind.UInt16] = "ushort",
		[DDLTypeKind.UInt32] = "uint",
		[DDLTypeKind.UInt64] = "ulong",
		[DDLTypeKind.Int8] = "sbyte",
		[DDLTypeKind.Int16] = "short",
		[DDLTypeKind.Int32] = "int",
		[DDLTypeKind.Int64] = "long",
		[DDLTypeKind.Float] = "float",
		[DDLTypeKind.Double] = "double",
		[DDLTypeKind.String] = "string?",
		[DDLTypeKind.Bool] = "bool",
		[DDLTypeKind.File] = "RivetAssetId",
		[DDLTypeKind.Identifier] = "RivetAssetId",
		[DDLTypeKind.Json] = "string?",
		[DDLTypeKind.Unknown] = "object?",
		[DDLTypeKind.Asset] = "RivetAssetId",
	};

	public static readonly Dictionary<DDLTypeKind, string> MapTypeMapping = new() {
		[DDLTypeKind.UInt8] = "Byte",
		[DDLTypeKind.UInt16] = "UShort",
		[DDLTypeKind.UInt32] = "UInt",
		[DDLTypeKind.UInt64] = "ULong",
		[DDLTypeKind.Int8] = "SByte",
		[DDLTypeKind.Int16] = "Short",
		[DDLTypeKind.Int32] = "Int",
		[DDLTypeKind.Int64] = "Long",
		[DDLTypeKind.Float] = "Float",
		[DDLTypeKind.Double] = "Double",
		[DDLTypeKind.String] = "String",
		[DDLTypeKind.Bool] = "Bool",
		[DDLTypeKind.File] = "RivetAssetId",
		[DDLTypeKind.Identifier] = "RivetAssetId",
		[DDLTypeKind.Json] = "String",
		[DDLTypeKind.Asset] = "RivetAssetId",
	};

	public static readonly Dictionary<DDLTypeKind, string> ArgumentMapping = new() {
		[DDLTypeKind.String] = "0x%hash%u",
		[DDLTypeKind.Json] = "0x%hash%u",
		[DDLTypeKind.Unknown] = "0x%hash%u",
	};

	public static readonly Dictionary<DDLTypeKind, string> ReaderMapping = new() {
		[DDLTypeKind.String] = "GetString(0x%hash%) ?? %name%",
		[DDLTypeKind.Json] = "GetString(0x%hash%) ?? %name%",
		[DDLTypeKind.Enum] = "GetEnum<%type%>(0x%hash%u, %type%Values.Lookup)",
		[DDLTypeKind.Bitfield] = "GetBitset<%type%>(0x%hash%u, %type%Values.Lookup)",
		[DDLTypeKind.Struct] = "GetObject<%type%>(0x%hash%u)",
		[DDLTypeKind.Unknown] = "GetField(0x%hash%)",
	};

	public static readonly Dictionary<DDLTypeKind, string?> ArrayReaderMapping = new() {
		[DDLTypeKind.String] = "GetStrings(0x%hash%u, %name%)",
		[DDLTypeKind.Json] = "GetStrings(0x%hash%u, %name%)",
		[DDLTypeKind.Enum] = "GetEnums<%type%>(0x%hash%u, %type%Values.Lookup)",
		[DDLTypeKind.Bitfield] = null,
		[DDLTypeKind.Struct] = "GetObjects<%type%>(0x%hash%u)",
		[DDLTypeKind.Unknown] = "GetFields(0x%hash%u)",
	};

	public static readonly Dictionary<DDLTypeKind, string> DictionaryReaderMapping = new() {
		[DDLTypeKind.String] = "(mapId, mapDDL) => mapDDL.GetString(mapId)",
		[DDLTypeKind.Json] = "(mapId, mapDDL) => mapDDL.GetString(mapId)",
		[DDLTypeKind.Enum] = "(mapId, mapDDL) => mapDDL.GetEnum<%type%>(mapId, %type%Values.Lookup)",
		[DDLTypeKind.Bitfield] = "(mapId, mapDDL) => mapDDL.GetBitset<%type%>(mapId, %type%Values.Lookup)",
		[DDLTypeKind.Struct] = "(mapId, mapDDL) => mapDDL.GetObject<%type%>(mapId)",
		[DDLTypeKind.Unknown] = "(mapId, mapDDL) => mapDDL.GetField(mapId)",
	};

	public static string Format(string str, Dictionary<string, object> values) {
		foreach (var (key, value_) in values) {
			var value = value_ switch {
				            ulong u => u.ToString("x16"),
				            uint u => u.ToString("x8"),
				            ushort u => u.ToString("x4"),
				            byte u => u.ToString("x2"),
				            long u => u.ToString("x"),
				            int u => u.ToString("x"),
				            short u => u.ToString("x"),
				            sbyte u => u.ToString("x"),
				            float f => f.ToString("F", CultureInfo.InvariantCulture) + "f",
				            decimal f => f.ToString("F", CultureInfo.InvariantCulture) + "d",
				            _ => value_,
			            };

			str = str.Replace($"%{key}%", value.ToString(), StringComparison.Ordinal);
		}

		return str;
	}
}
