<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>rivet-codegen-ddl</AssemblyName>
		<ApplicationIcon>../Rivet/Resources/icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Rivet.DDL.Template\Rivet.DDL.Template.csproj"/>
	</ItemGroup>

</Project>
