<!--
SPDX-FileCopyrightText: 2025 Legiayayana

SPDX-License-Identifier: EUPL-1.2
-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>rivet-codegen-ddl</AssemblyName>
		<ApplicationIcon>../Rivet/Resources/icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Serilog" Version="4.2.0" />
	  <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
	</ItemGroup>

</Project>
