// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x1e271f24u)]
public enum x1e271f24 : uint {
	[DDLRegistration(0x879ccbf2u)] Prune = 0x0u,
	[DDLRegistration(0x0b29d224u)] PruneFollow = 0x1u,
	[DDLRegistration(0x6bfbd190u)] NoPrune = 0x2u,
}

public static class x1e271f24Values {
	public static Dictionary<uint, x1e271f24> Lookup = new() {
		[0x879ccbf2u] = x1e271f24.Prune,
		[0x0b29d224u] = x1e271f24.PruneFollow,
		[0x6bfbd190u] = x1e271f24.NoPrune,
	};

	public static Dictionary<x1e271f24, uint> ReverseLookup = new() {
		[x1e271f24.Prune] = 0x879ccbf2u,
		[x1e271f24.PruneFollow] = 0x0b29d224u,
		[x1e271f24.NoPrune] = 0x6bfbd190u,
	};

	public static uint TypeId => 0x1e271f24u;
}
