// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x38fb844du)]
public enum x38fb844d : uint {
	[DDLRegistration(0xdfe58314u)] AnimClipGeomTypeNone,
	[DDLRegistration(0x400a577bu)] AnimClipGeomTypeFull,
	[DDLRegistration(0x55e06f8bu)] AnimClipGeomTypeDelta,
	[DDLRegistration(0xb2e8eb47u)] AnimClipGeomTypeDelta2,
	[DDLRegistration(0xc5efdbd1u)] AnimClipGeomTypeDelta3,
	[DDLRegistration(0x0ff81312u)] AnimClipGeomTypeDeltaUncompressed,
}

public static class x38fb844dValues {
	public static Dictionary<uint, x38fb844d> Lookup = new() {
		[0xdfe58314u] = x38fb844d.AnimClipGeomTypeNone,
		[0x400a577bu] = x38fb844d.AnimClipGeomTypeFull,
		[0x55e06f8bu] = x38fb844d.AnimClipGeomTypeDelta,
		[0xb2e8eb47u] = x38fb844d.AnimClipGeomTypeDelta2,
		[0xc5efdbd1u] = x38fb844d.AnimClipGeomTypeDelta3,
		[0x0ff81312u] = x38fb844d.AnimClipGeomTypeDeltaUncompressed,
	};

	public static Dictionary<x38fb844d, uint> ReverseLookup = new() {
		[x38fb844d.AnimClipGeomTypeNone] = 0xdfe58314u,
		[x38fb844d.AnimClipGeomTypeFull] = 0x400a577bu,
		[x38fb844d.AnimClipGeomTypeDelta] = 0x55e06f8bu,
		[x38fb844d.AnimClipGeomTypeDelta2] = 0xb2e8eb47u,
		[x38fb844d.AnimClipGeomTypeDelta3] = 0xc5efdbd1u,
		[x38fb844d.AnimClipGeomTypeDeltaUncompressed] = 0x0ff81312u,
	};

	public static uint TypeId => 0x38fb844du;
}
