// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x4bc99fe3u)]
public enum x4bc99fe3 : uint {
	[DDLRegistration(0xbea68d89u)] DoNotAutoDisable = 0x0u,
	[DDLRegistration(0xc6f5769du)] DisableOnTrigger = 0x1u,
	[DDLRegistration(0x721c19b5u)] DisableOnUnTrigger = 0x2u,
}

public static class x4bc99fe3Values {
	public static Dictionary<uint, x4bc99fe3> Lookup = new() {
		[0xbea68d89u] = x4bc99fe3.DoNotAutoDisable,
		[0xc6f5769du] = x4bc99fe3.DisableOnTrigger,
		[0x721c19b5u] = x4bc99fe3.DisableOnUnTrigger,
	};

	public static Dictionary<x4bc99fe3, uint> ReverseLookup = new() {
		[x4bc99fe3.DoNotAutoDisable] = 0xbea68d89u,
		[x4bc99fe3.DisableOnTrigger] = 0xc6f5769du,
		[x4bc99fe3.DisableOnUnTrigger] = 0x721c19b5u,
	};

	public static uint TypeId => 0x4bc99fe3u;
}
