// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x4eda4f54u)]
public enum x4eda4f54 : uint {
	[DDLRegistration(0x5e78a90au, "XYZ")] RotOrderXYZ,
	[DDLRegistration(0x9a99f1d2u, "YZX")] RotOrderYZX,
	[DDLRegistration(0xddee1d9fu, "ZXY")] RotOrderZXY,
	[DDLRegistration(0xec5cab73u, "XZY")] RotOrderXZY,
	[DDLRegistration(0x46a1f27cu, "YXZ")] RotOrderYXZ,
	[DDLRegistration(0xb3f21c48u, "ZYX")] RotOrderZYX,
}

public static class x4eda4f54Values {
	public static Dictionary<uint, x4eda4f54> Lookup = new() {
		[0x5e78a90au] = x4eda4f54.RotOrderXYZ,
		[0x9a99f1d2u] = x4eda4f54.RotOrderYZX,
		[0xddee1d9fu] = x4eda4f54.RotOrderZXY,
		[0xec5cab73u] = x4eda4f54.RotOrderXZY,
		[0x46a1f27cu] = x4eda4f54.RotOrderYXZ,
		[0xb3f21c48u] = x4eda4f54.RotOrderZYX,
	};

	public static Dictionary<x4eda4f54, uint> ReverseLookup = new() {
		[x4eda4f54.RotOrderXYZ] = 0x5e78a90au,
		[x4eda4f54.RotOrderYZX] = 0x9a99f1d2u,
		[x4eda4f54.RotOrderZXY] = 0xddee1d9fu,
		[x4eda4f54.RotOrderXZY] = 0xec5cab73u,
		[x4eda4f54.RotOrderYXZ] = 0x46a1f27cu,
		[x4eda4f54.RotOrderZYX] = 0xb3f21c48u,
	};

	public static uint TypeId => 0x4eda4f54u;
}
