// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x531b18aau)]
public enum x531b18aa : uint {
	[DDLRegistration(0x0eb42269u)] None = 0x0u,
	[DDLRegistration(0xd7b1dc31u)] World = 0x1u,
	[DDLRegistration(0xf4e5026fu)] TargetRelative = 0x2u,
	[DDLRegistration(0xe24b4fb2u)] Position = 0x3u,
	[DDLRegistration(0xa9b39b8bu)] Actor = 0x4u,
	[DDLRegistration(0xacd779c2u)] StoredPositionToActor = 0x5u,
}

public static class x531b18aaValues {
	public static Dictionary<uint, x531b18aa> Lookup = new() {
		[0x0eb42269u] = x531b18aa.None,
		[0xd7b1dc31u] = x531b18aa.World,
		[0xf4e5026fu] = x531b18aa.TargetRelative,
		[0xe24b4fb2u] = x531b18aa.Position,
		[0xa9b39b8bu] = x531b18aa.Actor,
		[0xacd779c2u] = x531b18aa.StoredPositionToActor,
	};

	public static Dictionary<x531b18aa, uint> ReverseLookup = new() {
		[x531b18aa.None] = 0x0eb42269u,
		[x531b18aa.World] = 0xd7b1dc31u,
		[x531b18aa.TargetRelative] = 0xf4e5026fu,
		[x531b18aa.Position] = 0xe24b4fb2u,
		[x531b18aa.Actor] = 0xa9b39b8bu,
		[x531b18aa.StoredPositionToActor] = 0xacd779c2u,
	};

	public static uint TypeId => 0x531b18aau;
}
