// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x8b0475d0u)]
public enum x8b0475d0 : uint {
	[DDLRegistration(0x7c3f8794u)] Manual = 0x0u,
	[DDLRegistration(0x3a5c5f9fu)] Pause = 0x1u,
	[DDLRegistration(0x0a095e87u)] WaitForRider = 0x2u,
	[DDLRegistration(0xbdbf656bu)] AllHeroes = 0x3u,
	[DDLRegistration(0x8e79e0a2u)] UseOffer = 0x4u,
	[DDLRegistration(0xbc459cc0u)] PassThrough = 0x5u,
}

public static class x8b0475d0Values {
	public static Dictionary<uint, x8b0475d0> Lookup = new() {
		[0x7c3f8794u] = x8b0475d0.Manual,
		[0x3a5c5f9fu] = x8b0475d0.Pause,
		[0x0a095e87u] = x8b0475d0.WaitForRider,
		[0xbdbf656bu] = x8b0475d0.AllHeroes,
		[0x8e79e0a2u] = x8b0475d0.UseOffer,
		[0xbc459cc0u] = x8b0475d0.PassThrough,
	};

	public static Dictionary<x8b0475d0, uint> ReverseLookup = new() {
		[x8b0475d0.Manual] = 0x7c3f8794u,
		[x8b0475d0.Pause] = 0x3a5c5f9fu,
		[x8b0475d0.WaitForRider] = 0x0a095e87u,
		[x8b0475d0.AllHeroes] = 0xbdbf656bu,
		[x8b0475d0.UseOffer] = 0x8e79e0a2u,
		[x8b0475d0.PassThrough] = 0xbc459cc0u,
	};

	public static uint TypeId => 0x8b0475d0u;
}
