// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x94fdc626u)]
public enum x94fdc626 : uint {
	[DDLRegistration(0x4f1ae5c7u)] Soft = 0x0u,
	[DDLRegistration(0x1ffd2683u)] Normal = 0x1u,
	[DDLRegistration(0x6362b69eu)] Heavy = 0x2u,
	[DDLRegistration(0x46837ec3u)] Stomp = 0x3u,
}

public static class x94fdc626Values {
	public static Dictionary<uint, x94fdc626> Lookup = new() {
		[0x4f1ae5c7u] = x94fdc626.Soft,
		[0x1ffd2683u] = x94fdc626.Normal,
		[0x6362b69eu] = x94fdc626.Heavy,
		[0x46837ec3u] = x94fdc626.Stomp,
	};

	public static Dictionary<x94fdc626, uint> ReverseLookup = new() {
		[x94fdc626.Soft] = 0x4f1ae5c7u,
		[x94fdc626.Normal] = 0x1ffd2683u,
		[x94fdc626.Heavy] = 0x6362b69eu,
		[x94fdc626.Stomp] = 0x46837ec3u,
	};

	public static uint TypeId => 0x94fdc626u;
}
