// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x96e13489u)]
public enum x96e13489 : uint {
	[DDLRegistration(0x761706c4u)] Degrees = 0x0u,
	[DDLRegistration(0xcdcd367fu)] Radians = 0x1u,
	[DDLRegistration(0xc6f8952du)] Normalized = 0x2u,
}

public static class x96e13489Values {
	public static Dictionary<uint, x96e13489> Lookup = new() {
		[0x761706c4u] = x96e13489.Degrees,
		[0xcdcd367fu] = x96e13489.Radians,
		[0xc6f8952du] = x96e13489.Normalized,
	};

	public static Dictionary<x96e13489, uint> ReverseLookup = new() {
		[x96e13489.Degrees] = 0x761706c4u,
		[x96e13489.Radians] = 0xcdcd367fu,
		[x96e13489.Normalized] = 0xc6f8952du,
	};

	public static uint TypeId => 0x96e13489u;
}
