// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x96f58b25u)]
public enum x96f58b25 : uint {
	[DDLRegistration(0x672bafc2u)] InteractEnable = 0x0u,
	[DDLRegistration(0x206edba7u)] InteractDisable = 0x1u,
	[DDLRegistration(0xb161ca7bu)] InteractToggle = 0x2u,
}

public static class x96f58b25Values {
	public static Dictionary<uint, x96f58b25> Lookup = new() {
		[0x672bafc2u] = x96f58b25.InteractEnable,
		[0x206edba7u] = x96f58b25.InteractDisable,
		[0xb161ca7bu] = x96f58b25.InteractToggle,
	};

	public static Dictionary<x96f58b25, uint> ReverseLookup = new() {
		[x96f58b25.InteractEnable] = 0x672bafc2u,
		[x96f58b25.InteractDisable] = 0x206edba7u,
		[x96f58b25.InteractToggle] = 0xb161ca7bu,
	};

	public static uint TypeId => 0x96f58b25u;
}
