// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xd7e26c97u)]
public enum xd7e26c97 : uint {
	[DDLRegistration(0x0eb42269u)] None,
	[DDLRegistration(0x5ae2dfdbu)] Windows,
	[DDLRegistration(0x815f1402u)] PS4,
	[DDLRegistration(0xf6582494u)] PS5,
}

public static class xd7e26c97Values {
	public static Dictionary<uint, xd7e26c97> Lookup = new() {
		[0x0eb42269u] = xd7e26c97.None,
		[0x5ae2dfdbu] = xd7e26c97.Windows,
		[0x815f1402u] = xd7e26c97.PS4,
		[0xf6582494u] = xd7e26c97.PS5,
	};

	public static Dictionary<xd7e26c97, uint> ReverseLookup = new() {
		[xd7e26c97.None] = 0x0eb42269u,
		[xd7e26c97.Windows] = 0x5ae2dfdbu,
		[xd7e26c97.PS4] = 0x815f1402u,
		[xd7e26c97.PS5] = 0xf6582494u,
	};

	public static uint TypeId => 0xd7e26c97u;
}
