// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xec77cf54u)]
public enum xec77cf54 : uint {
	[DDLRegistration(0xfbf6b134u)] SelOpEQ = 0x0u,
	[DDLRegistration(0x1fd85bd2u)] SelOpNEQ = 0x1u,
	[DDLRegistration(0xb9aa2739u)] SelOpGT = 0x2u,
	[DDLRegistration(0x590a9730u)] SelOpGTE = 0x3u,
	[DDLRegistration(0x5a5efef2u)] SelOpLT = 0x4u,
	[DDLRegistration(0x555f78d1u)] SelOpLTE = 0x5u,
	[DDLRegistration(0x832ec9a6u)] SelOpMABF = 0x6u,
}

public static class xec77cf54Values {
	public static Dictionary<uint, xec77cf54> Lookup = new() {
		[0xfbf6b134u] = xec77cf54.SelOpEQ,
		[0x1fd85bd2u] = xec77cf54.SelOpNEQ,
		[0xb9aa2739u] = xec77cf54.SelOpGT,
		[0x590a9730u] = xec77cf54.SelOpGTE,
		[0x5a5efef2u] = xec77cf54.SelOpLT,
		[0x555f78d1u] = xec77cf54.SelOpLTE,
		[0x832ec9a6u] = xec77cf54.SelOpMABF,
	};

	public static Dictionary<xec77cf54, uint> ReverseLookup = new() {
		[xec77cf54.SelOpEQ] = 0xfbf6b134u,
		[xec77cf54.SelOpNEQ] = 0x1fd85bd2u,
		[xec77cf54.SelOpGT] = 0xb9aa2739u,
		[xec77cf54.SelOpGTE] = 0x590a9730u,
		[xec77cf54.SelOpLT] = 0x5a5efef2u,
		[xec77cf54.SelOpLTE] = 0x555f78d1u,
		[xec77cf54.SelOpMABF] = 0x832ec9a6u,
	};

	public static uint TypeId => 0xec77cf54u;
}
