// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x8d7e44cfu)]
public enum DamageTypesGame : uint {
	[DDLRegistration(0x0eb42269u)] None = 0x0u,
	[DDLRegistration(0x2221b6d3u)] Melee = 0x1u,
	[DDLRegistration(0xd6f70925u)] Bullet = 0x2u,
	[DDLRegistration(0x29fa2b69u)] Fire = 0x3u,
	[DDLRegistration(0x4b893d09u)] Explosion = 0x4u,
	[DDLRegistration(0xd80c5c08u)] Heal = 0x5u,
	[DDLRegistration(0x7065be6au)] Script = 0x6u,
	[DDLRegistration(0x9ba52d2eu)] Kinetic = 0x7u,
	[DDLRegistration(0x4d3bb094u)] Falling = 0x8u,
	[DDLRegistration(0x16f5d9a8u)] Water = 0x9u,
	[DDLRegistration(0x1afe6f38u)] Nostalgia = 0xau,
	[DDLRegistration(0x342a1a63u)] Confuse = 0xbu,
	[DDLRegistration(0x405f04edu)] Electric = 0xcu,
	[DDLRegistration(0x5182db6cu)] Ice = 0xdu,
	[DDLRegistration(0x95902019u)] Poison = 0xeu,
	[DDLRegistration(0xfbf540c1u)] Energy = 0xfu,
	[DDLRegistration(0x3b203c47u)] LightningRod = 0x10u,
	[DDLRegistration(0xe04f1ed8u)] Fossilize = 0x11u,
	[DDLRegistration(0x3e3e9157u)] Shrubbery = 0x12u,
	[DDLRegistration(0x904d0e76u)] MagnaMissile = 0x13u,
	[DDLRegistration(0x698991ddu)] MagnaMissileImplosion = 0x14u,
	[DDLRegistration(0x9c28c571u)] LevelUp = 0x15u,
	[DDLRegistration(0x80012eaeu)] ActiveFinisher = 0x16u,
	[DDLRegistration(0x573f5154u)] WarpRifleImplosion = 0x17u,
	[DDLRegistration(0xdcaefe0au)] ProtoGrenadeExplosion = 0x18u,
	[DDLRegistration(0x340f3a42u)] Rynotize = 0x19u,
	[DDLRegistration(0x678b6d0au)] Acid = 0x1au,
}

public static class DamageTypesGameValues {
	public static Dictionary<string, DamageTypesGame> Lookup = new() {
		["kNone"] = DamageTypesGame.None,
		["kMelee"] = DamageTypesGame.Melee,
		["kBullet"] = DamageTypesGame.Bullet,
		["kFire"] = DamageTypesGame.Fire,
		["kExplosion"] = DamageTypesGame.Explosion,
		["kHeal"] = DamageTypesGame.Heal,
		["kScript"] = DamageTypesGame.Script,
		["kKinetic"] = DamageTypesGame.Kinetic,
		["kFalling"] = DamageTypesGame.Falling,
		["kWater"] = DamageTypesGame.Water,
		["kNostalgia"] = DamageTypesGame.Nostalgia,
		["kConfuse"] = DamageTypesGame.Confuse,
		["kElectric"] = DamageTypesGame.Electric,
		["kIce"] = DamageTypesGame.Ice,
		["kPoison"] = DamageTypesGame.Poison,
		["kEnergy"] = DamageTypesGame.Energy,
		["kLightningRod"] = DamageTypesGame.LightningRod,
		["kFossilize"] = DamageTypesGame.Fossilize,
		["kShrubbery"] = DamageTypesGame.Shrubbery,
		["kMagnaMissile"] = DamageTypesGame.MagnaMissile,
		["kMagnaMissileImplosion"] = DamageTypesGame.MagnaMissileImplosion,
		["kLevelUp"] = DamageTypesGame.LevelUp,
		["kActiveFinisher"] = DamageTypesGame.ActiveFinisher,
		["kWarpRifleImplosion"] = DamageTypesGame.WarpRifleImplosion,
		["kProtoGrenadeExplosion"] = DamageTypesGame.ProtoGrenadeExplosion,
		["kRynotize"] = DamageTypesGame.Rynotize,
		["kAcid"] = DamageTypesGame.Acid,
	};

	public static Dictionary<DamageTypesGame, uint> ReverseLookup = new() {
		[DamageTypesGame.None] = 0x0eb42269u,
		[DamageTypesGame.Melee] = 0x2221b6d3u,
		[DamageTypesGame.Bullet] = 0xd6f70925u,
		[DamageTypesGame.Fire] = 0x29fa2b69u,
		[DamageTypesGame.Explosion] = 0x4b893d09u,
		[DamageTypesGame.Heal] = 0xd80c5c08u,
		[DamageTypesGame.Script] = 0x7065be6au,
		[DamageTypesGame.Kinetic] = 0x9ba52d2eu,
		[DamageTypesGame.Falling] = 0x4d3bb094u,
		[DamageTypesGame.Water] = 0x16f5d9a8u,
		[DamageTypesGame.Nostalgia] = 0x1afe6f38u,
		[DamageTypesGame.Confuse] = 0x342a1a63u,
		[DamageTypesGame.Electric] = 0x405f04edu,
		[DamageTypesGame.Ice] = 0x5182db6cu,
		[DamageTypesGame.Poison] = 0x95902019u,
		[DamageTypesGame.Energy] = 0xfbf540c1u,
		[DamageTypesGame.LightningRod] = 0x3b203c47u,
		[DamageTypesGame.Fossilize] = 0xe04f1ed8u,
		[DamageTypesGame.Shrubbery] = 0x3e3e9157u,
		[DamageTypesGame.MagnaMissile] = 0x904d0e76u,
		[DamageTypesGame.MagnaMissileImplosion] = 0x698991ddu,
		[DamageTypesGame.LevelUp] = 0x9c28c571u,
		[DamageTypesGame.ActiveFinisher] = 0x80012eaeu,
		[DamageTypesGame.WarpRifleImplosion] = 0x573f5154u,
		[DamageTypesGame.ProtoGrenadeExplosion] = 0xdcaefe0au,
		[DamageTypesGame.Rynotize] = 0x340f3a42u,
		[DamageTypesGame.Acid] = 0x678b6d0au,
	};

	public static uint TypeId => 0x8d7e44cfu;
}
