// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xc723d92au)]
public enum ExistingLedgeFlockBehavior : uint {
	[DDLRegistration(0x377bde14u)] ScatterBirds = 0x0u,
	[DDLRegistration(0x8ccde7fbu)] DestroyBirds = 0x1u,
}

public static class ExistingLedgeFlockBehaviorValues {
	public static Dictionary<string, ExistingLedgeFlockBehavior> Lookup = new() {
		["kScatterBirds"] = ExistingLedgeFlockBehavior.ScatterBirds,
		["kDestroyBirds"] = ExistingLedgeFlockBehavior.DestroyBirds,
	};

	public static Dictionary<ExistingLedgeFlockBehavior, uint> ReverseLookup = new() {
		[ExistingLedgeFlockBehavior.ScatterBirds] = 0x377bde14u,
		[ExistingLedgeFlockBehavior.DestroyBirds] = 0x8ccde7fbu,
	};

	public static uint TypeId => 0xc723d92au;
}
