// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xde3cdb81u)]
public enum FollowCameraModeEnum : uint {
	[DDLRegistration(0x74308d6fu)] On = 0x0u,
	[DDLRegistration(0x54426b62u)] Fast = 0x1u,
	[DDLRegistration(0xb1710221u)] Off = 0x2u,
}

public static class FollowCameraModeEnumValues {
	public static Dictionary<string, FollowCameraModeEnum> Lookup = new() {
		["kOn"] = FollowCameraModeEnum.On,
		["kFast"] = FollowCameraModeEnum.Fast,
		["kOff"] = FollowCameraModeEnum.Off,
	};

	public static Dictionary<FollowCameraModeEnum, uint> ReverseLookup = new() {
		[FollowCameraModeEnum.On] = 0x74308d6fu,
		[FollowCameraModeEnum.Fast] = 0x54426b62u,
		[FollowCameraModeEnum.Off] = 0xb1710221u,
	};

	public static uint TypeId => 0xde3cdb81u;
}
