// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xfcb30197u)]
public enum POITypeSelect : uint {
	[DDLRegistration(0x0973b660u)] POITypeNone = 0x0u,
	[DDLRegistration(0x671baf94u)] POITypeObjective = 0x1u,
	[DDLRegistration(0x59806ce2u)] POITypeObjectiveOptional = 0x2u,
	[DDLRegistration(0x185f8021u)] POITypeInteract = 0x3u,
	[DDLRegistration(0x0f6cee57u)] POITypeMapIcon = 0x4u,
	[DDLRegistration(0x91387f58u)] POITypeNest = 0x5u,
	[DDLRegistration(0x53368b52u)] POITypePing = 0x6u,
}

public static class POITypeSelectValues {
	public static Dictionary<string, POITypeSelect> Lookup = new() {
		["POITypeNone"] = POITypeSelect.POITypeNone,
		["POITypeObjective"] = POITypeSelect.POITypeObjective,
		["POITypeObjectiveOptional"] = POITypeSelect.POITypeObjectiveOptional,
		["POITypeInteract"] = POITypeSelect.POITypeInteract,
		["POITypeMapIcon"] = POITypeSelect.POITypeMapIcon,
		["POITypeNest"] = POITypeSelect.POITypeNest,
		["POITypePing"] = POITypeSelect.POITypePing,
	};

	public static Dictionary<POITypeSelect, uint> ReverseLookup = new() {
		[POITypeSelect.POITypeNone] = 0x0973b660u,
		[POITypeSelect.POITypeObjective] = 0x671baf94u,
		[POITypeSelect.POITypeObjectiveOptional] = 0x59806ce2u,
		[POITypeSelect.POITypeInteract] = 0x185f8021u,
		[POITypeSelect.POITypeMapIcon] = 0x0f6cee57u,
		[POITypeSelect.POITypeNest] = 0x91387f58u,
		[POITypeSelect.POITypePing] = 0x53368b52u,
	};

	public static uint TypeId => 0xfcb30197u;
}
