// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x3f08814bu)]
public enum PolylineType : uint {
	[DDLRegistration(0x9685f03du)] OpenFree = 0x0u,
	[DDLRegistration(0x9cd0d602u)] OpenPlanar = 0x1u,
	[DDLRegistration(0xf07036a0u)] ClosedFree = 0x2u,
	[DDLRegistration(0x2a382325u)] ClosedPlanar = 0x3u,
	[DDLRegistration(0x378eed19u)] PolygonPlanar = 0x4u,
	[DDLRegistration(0xcade0d40u)] VolumePlanar = 0x5u,
}

public static class PolylineTypeValues {
	public static Dictionary<string, PolylineType> Lookup = new() {
		["kOpenFree"] = PolylineType.OpenFree,
		["kOpenPlanar"] = PolylineType.OpenPlanar,
		["kClosedFree"] = PolylineType.ClosedFree,
		["kClosedPlanar"] = PolylineType.ClosedPlanar,
		["kPolygonPlanar"] = PolylineType.PolygonPlanar,
		["kVolumePlanar"] = PolylineType.VolumePlanar,
	};

	public static Dictionary<PolylineType, uint> ReverseLookup = new() {
		[PolylineType.OpenFree] = 0x9685f03du,
		[PolylineType.OpenPlanar] = 0x9cd0d602u,
		[PolylineType.ClosedFree] = 0xf07036a0u,
		[PolylineType.ClosedPlanar] = 0x2a382325u,
		[PolylineType.PolygonPlanar] = 0x378eed19u,
		[PolylineType.VolumePlanar] = 0xcade0d40u,
	};

	public static uint TypeId => 0x3f08814bu;
}
