// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x1065ab66u), Flags]
public enum TestFlags : uint {
	[DDLRegistration(0x7e11ac74u)] Flag1 = 0x00000001u,
	[DDLRegistration(0xe718fdceu)] Flag2 = 0x00000002u,
}

public static class TestFlagsValues {
	public static Dictionary<string, TestFlags> Lookup = new() {
		["kFlag1"] = TestFlags.Flag1,
		["kFlag2"] = TestFlags.Flag2,
	};

	public static Dictionary<TestFlags, uint> ReverseLookup = new() {
		[TestFlags.Flag1] = 0x7e11ac74u,
		[TestFlags.Flag2] = 0xe718fdceu,
	};

	public static uint TypeId => 0x1065ab66u;
}
