// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x0d255d55u)]
public enum x0d255d55 : uint {
	[DDLRegistration(0x084527c3u)] Low = 0x0u,
	[DDLRegistration(0x8021c6f3u)] High = 0x1u,
}

public static class x0d255d55Values {
	public static Dictionary<string, x0d255d55> Lookup = new() {
		["kLow"] = x0d255d55.Low,
		["kHigh"] = x0d255d55.High,
	};

	public static Dictionary<x0d255d55, uint> ReverseLookup = new() {
		[x0d255d55.Low] = 0x084527c3u,
		[x0d255d55.High] = 0x8021c6f3u,
	};

	public static uint TypeId => 0x0d255d55u;
}
