// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x0f02da14u)]
public enum x0f02da14 : uint {
	[DDLRegistration(0xef69972eu)] Asset = 0x0u,
	[DDLRegistration(0x8046309du)] Folder = 0x1u,
	[DDLRegistration(0xff97fd25u)] GameData = 0x2u,
}

public static class x0f02da14Values {
	public static Dictionary<string, x0f02da14> Lookup = new() {
		["kAsset"] = x0f02da14.Asset,
		["kFolder"] = x0f02da14.Folder,
		["kGameData"] = x0f02da14.GameData,
	};

	public static Dictionary<x0f02da14, uint> ReverseLookup = new() {
		[x0f02da14.Asset] = 0xef69972eu,
		[x0f02da14.Folder] = 0x8046309du,
		[x0f02da14.GameData] = 0xff97fd25u,
	};

	public static uint TypeId => 0x0f02da14u;
}
