// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x27b34de0u), Flags]
public enum x27b34de0 : uint {
	[DDLRegistration(0x4e1b1639u)] DeathEvent = 0x00000001u,
	[DDLRegistration(0xc467a8d9u)] AnimEvent = 0x00000002u,
	[DDLRegistration(0x9ba23b44u)] ExplodedEvent = 0x00000004u,
}

public static class x27b34de0Values {
	public static Dictionary<string, x27b34de0> Lookup = new() {
		["kDeathEvent"] = x27b34de0.DeathEvent,
		["kAnimEvent"] = x27b34de0.AnimEvent,
		["kExplodedEvent"] = x27b34de0.ExplodedEvent,
	};

	public static Dictionary<x27b34de0, uint> ReverseLookup = new() {
		[x27b34de0.DeathEvent] = 0x4e1b1639u,
		[x27b34de0.AnimEvent] = 0xc467a8d9u,
		[x27b34de0.ExplodedEvent] = 0x9ba23b44u,
	};

	public static uint TypeId => 0x27b34de0u;
}
