// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x32cc2d2cu)]
public enum x32cc2d2c : uint {
	[DDLRegistration(0x28f1b775u)] DisableShadows = 0x0u,
	[DDLRegistration(0xba7a7ed3u)] AlwaysCastShadows = 0x1u,
	[DDLRegistration(0x3ed7b7f8u)] CanDissolveShadows = 0x2u,
}

public static class x32cc2d2cValues {
	public static Dictionary<string, x32cc2d2c> Lookup = new() {
		["kDisableShadows"] = x32cc2d2c.DisableShadows,
		["kAlwaysCastShadows"] = x32cc2d2c.AlwaysCastShadows,
		["kCanDissolveShadows"] = x32cc2d2c.CanDissolveShadows,
	};

	public static Dictionary<x32cc2d2c, uint> ReverseLookup = new() {
		[x32cc2d2c.DisableShadows] = 0x28f1b775u,
		[x32cc2d2c.AlwaysCastShadows] = 0xba7a7ed3u,
		[x32cc2d2c.CanDissolveShadows] = 0x3ed7b7f8u,
	};

	public static uint TypeId => 0x32cc2d2cu;
}
