// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0x577f103eu)]
public enum x577f103e : uint {
	[DDLRegistration(0x429c20c0u)] Invalid = 0x0u,
	[DDLRegistration(0xac4bb760u)] AssetReferenceNode = 0x1u,
	[DDLRegistration(0x06f3b654u)] BlobDef = 0x2u,
	[DDLRegistration(0x2d71082cu)] Comment = 0x3u,
	[DDLRegistration(0x9612665cu)] Connection = 0x4u,
	[DDLRegistration(0xd731d82au)] ConnectionPin = 0x5u,
	[DDLRegistration(0x44ac06cbu)] ConnectionTuid = 0x6u,
	[DDLRegistration(0x38975f69u)] EmbeddedGraphNode = 0x7u,
	[DDLRegistration(0x566a5ffcu)] InputNode = 0x8u,
	[DDLRegistration(0x593d8335u)] InputPlug = 0x9u,
	[DDLRegistration(0xf45bcae3u)] Node = 0xau,
	[DDLRegistration(0x681b8b40u)] NodeGraph = 0xbu,
	[DDLRegistration(0xb3a8b859u)] NodeGraphCollection = 0xcu,
	[DDLRegistration(0x5171a970u)] OutputNode = 0xdu,
	[DDLRegistration(0x5e2675b9u)] OutputPlug = 0xeu,
	[DDLRegistration(0xba1f5472u)] ReferencedGraphNode = 0xfu,
}

public static class x577f103eValues {
	public static Dictionary<string, x577f103e> Lookup = new() {
		["kInvalid"] = x577f103e.Invalid,
		["kAssetReferenceNode"] = x577f103e.AssetReferenceNode,
		["kBlobDef"] = x577f103e.BlobDef,
		["kComment"] = x577f103e.Comment,
		["kConnection"] = x577f103e.Connection,
		["kConnectionPin"] = x577f103e.ConnectionPin,
		["kConnectionTuid"] = x577f103e.ConnectionTuid,
		["kEmbeddedGraphNode"] = x577f103e.EmbeddedGraphNode,
		["kInputNode"] = x577f103e.InputNode,
		["kInputPlug"] = x577f103e.InputPlug,
		["kNode"] = x577f103e.Node,
		["kNodeGraph"] = x577f103e.NodeGraph,
		["kNodeGraphCollection"] = x577f103e.NodeGraphCollection,
		["kOutputNode"] = x577f103e.OutputNode,
		["kOutputPlug"] = x577f103e.OutputPlug,
		["kReferencedGraphNode"] = x577f103e.ReferencedGraphNode,
	};

	public static Dictionary<x577f103e, uint> ReverseLookup = new() {
		[x577f103e.Invalid] = 0x429c20c0u,
		[x577f103e.AssetReferenceNode] = 0xac4bb760u,
		[x577f103e.BlobDef] = 0x06f3b654u,
		[x577f103e.Comment] = 0x2d71082cu,
		[x577f103e.Connection] = 0x9612665cu,
		[x577f103e.ConnectionPin] = 0xd731d82au,
		[x577f103e.ConnectionTuid] = 0x44ac06cbu,
		[x577f103e.EmbeddedGraphNode] = 0x38975f69u,
		[x577f103e.InputNode] = 0x566a5ffcu,
		[x577f103e.InputPlug] = 0x593d8335u,
		[x577f103e.Node] = 0xf45bcae3u,
		[x577f103e.NodeGraph] = 0x681b8b40u,
		[x577f103e.NodeGraphCollection] = 0xb3a8b859u,
		[x577f103e.OutputNode] = 0x5171a970u,
		[x577f103e.OutputPlug] = 0x5e2675b9u,
		[x577f103e.ReferencedGraphNode] = 0xba1f5472u,
	};

	public static uint TypeId => 0x577f103eu;
}
