// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xa6a133d1u)]
public enum xa6a133d1 : uint {
	[DDLRegistration(0xea4ab9f3u)] NormalOnly = 0x0u,
	[DDLRegistration(0xe73b2c0eu)] ColorOnly = 0x1u,
	[DDLRegistration(0x915bf606u)] Full = 0x2u,
	[DDLRegistration(0x0eb42269u)] None = 0x3u,
}

public static class xa6a133d1Values {
	public static Dictionary<string, xa6a133d1> Lookup = new() {
		["kNormalOnly"] = xa6a133d1.NormalOnly,
		["kColorOnly"] = xa6a133d1.ColorOnly,
		["kFull"] = xa6a133d1.Full,
		["kNone"] = xa6a133d1.None,
	};

	public static Dictionary<xa6a133d1, uint> ReverseLookup = new() {
		[xa6a133d1.NormalOnly] = 0xea4ab9f3u,
		[xa6a133d1.ColorOnly] = 0xe73b2c0eu,
		[xa6a133d1.Full] = 0x915bf606u,
		[xa6a133d1.None] = 0x0eb42269u,
	};

	public static uint TypeId => 0xa6a133d1u;
}
