// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xf23aa75cu)]
public enum xf23aa75c : uint {
	[DDLRegistration(0x1dafe79au)] image = 0x0u,
	[DDLRegistration(0xa45539e9u)] video = 0x1u,
}

public static class xf23aa75cValues {
	public static Dictionary<string, xf23aa75c> Lookup = new() {
		["image"] = xf23aa75c.image,
		["video"] = xf23aa75c.video,
	};

	public static Dictionary<xf23aa75c, uint> ReverseLookup = new() {
		[xf23aa75c.image] = 0x1dafe79au,
		[xf23aa75c.video] = 0xa45539e9u,
	};

	public static uint TypeId => 0xf23aa75cu;
}
