// <auto-generated>
// SPDX-FileCopyrightText: 2025 Legiayayana
//
// SPDX-License-Identifier: EUPL-1.2

namespace Rivet.DDL.Enums;

[DDLRegistration(0xf4a2a500u)]
public enum xf4a2a500 : uint {
	[DDLRegistration(0x4e03ad2eu)] SystemPause = 0x0u,
	[DDLRegistration(0x144f5fe2u)] SystemPause2 = 0x1u,
	[DDLRegistration(0x63486f74u)] SystemPause3 = 0x2u,
}

public static class xf4a2a500Values {
	public static Dictionary<string, xf4a2a500> Lookup = new() {
		["kSystemPause"] = xf4a2a500.SystemPause,
		["kSystemPause2"] = xf4a2a500.SystemPause2,
		["kSystemPause3"] = xf4a2a500.SystemPause3,
	};

	public static Dictionary<xf4a2a500, uint> ReverseLookup = new() {
		[xf4a2a500.SystemPause] = 0x4e03ad2eu,
		[xf4a2a500.SystemPause2] = 0x144f5fe2u,
		[xf4a2a500.SystemPause3] = 0x63486f74u,
	};

	public static uint TypeId => 0xf4a2a500u;
}
