<!--
SPDX-FileCopyrightText: 2025 Legiayayana

SPDX-License-Identifier: EUPL-1.2
-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog" Version="4.2.0"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Libraries\Neptune\Pluto\Pluto.csproj"/>
		<ProjectReference Include="..\Libraries\Neptune\Charon\Charon.csproj"/>
		<ProjectReference Include="..\Rivet.DDL.RCRA\Rivet.DDL.RCRA.csproj"/>
		<ProjectReference Include="..\Rivet.DDL\Rivet.DDL.csproj"/>
		<ProjectReference Include="..\Rivet.IO\Rivet.IO.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<None Update="Resources\assets.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\tags.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
